### ISSUE TITLE
SSL not working for this site...

### ISSUE THREAD

**Issue by Ethan07Scape** [MachinePublishers/jBrowserDriver#106]
`public static void main(String[] args) {

	  JBrowserDriver driver = new JBrowserDriver(Settings.builder()
			   .timezone(Timezone.AMERICA_CHICAGO)
			   .blockAds(false)
			   .cache(true)
			   .userAgent(UserAgent.CHROME)
			   .logTrace(true)
			   .javascript(true)
			   .build());
    

    driver.get("http://www.runebet.com");

    
  

    System.out.println(driver.getPageSource());

    
    driver.quit();
  }`
`[2016-05-16T19:36:09.157][Instance 1][Port 52492] -Page-> http://www.runebet.com/ ** {timestamp: 1463427369155, state: page_started, progress: 0.1, error: none, contentType: null, frame: 14088832}
[2016-05-16T19:36:10.109][Instance 1][Port 52492] -Page-> http://runebet.com/ ** {timestamp: 1463427370109, state: page_redirected, progress: 0.1, error: none, contentType: text/html, frame: 14088832}
[2016-05-16T19:36:11.425][Instance 1][Port 52492] -Page-> https://runebet.com/ ** {timestamp: 1463427371424, state: page_redirected, progress: 0.1, error: none, contentType: text/html, frame: 14088832}
[2016-05-16T19:36:12.209][Instance 1][Port 52492] May 16, 2016 2:36:12 PM com.sun.webkit.network.URLLoader doRun
[2016-05-16T19:36:12.209][Instance 1][Port 52492] WARNING: Unexpected error
[2016-05-16T19:36:12.210][Instance 1][Port 52492] java.io.IOException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target: https://runebet.com/
[2016-05-16T19:36:12.210][Instance 1][Port 52492] 	at com.machinepublishers.jbrowserdriver.StreamConnection.exec(StreamConnection.java:373)
[2016-05-16T19:36:12.210][Instance 1][Port 52492] 	at com.machinepublishers.jbrowserdriver.StreamConnection.getResponseCode(StreamConnection.java:471)
[2016-05-16T19:36:12.210][Instance 1][Port 52492] 	at com.sun.webkit.network.URLLoader.receiveResponse(Unknown Source)
[2016-05-16T19:36:12.210][Instance 1][Port 52492] 	at com.sun.webkit.network.URLLoader.doRun(Unknown Source)
[2016-05-16T19:36:12.210][Instance 1][Port 52492] 	at com.sun.webkit.network.URLLoader.lambda$run$91(Unknown Source)
[2016-05-16T19:36:12.210][Instance 1][Port 52492] 	at java.security.AccessController.doPrivileged(Native Method)
[2016-05-16T19:36:12.210][Instance 1][Port 52492] 	at com.sun.webkit.network.URLLoader.run(Unknown Source)
[2016-05-16T19:36:12.210][Instance 1][Port 52492] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2016-05-16T19:36:12.211][Instance 1][Port 52492] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2016-05-16T19:36:12.211][Instance 1][Port 52492] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2016-05-16T19:36:12.211][Instance 1][Port 52492] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2016-05-16T19:36:12.211][Instance 1][Port 52492] 	at java.lang.Thread.run(Unknown Source)
[2016-05-16T19:36:12.211][Instance 1][Port 52492] Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[2016-05-16T19:36:12.211][Instance 1][Port 52492] 	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
[2016-05-16T19:36:12.211][Instance 1][Port 52492] 	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
[2016-05-16T19:36:12.211][Instance 1][Port 52492] 	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
[2016-05-16T19:36:12.211][Instance 1][Port 52492] 	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
[2016-05-16T19:36:12.212][Instance 1][Port 52492] 	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
[2016-05-16T19:36:12.212][Instance 1][Port 52492] 	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
[2016-05-16T19:36:12.212][Instance 1][Port 52492] 	at sun.security.ssl.Handshaker.processLoop(Unknown Source)
[2016-05-16T19:36:12.212][Instance 1][Port 52492] 	at sun.security.ssl.Handshaker.process_record(Unknown Source)
[2016-05-16T19:36:12.212][Instance 1][Port 52492] 	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
[2016-05-16T19:36:12.212][Instance 1][Port 52492] 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
[2016-05-16T19:36:12.212][Instance 1][Port 52492] 	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
[2016-05-16T19:36:12.212][Instance 1][Port 52492] 	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
[2016-05-16T19:36:12.213][Instance 1][Port 52492] 	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394)
[2016-05-16T19:36:12.213][Instance 1][Port 52492] 	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353)
[2016-05-16T19:36:12.213][Instance 1][Port 52492] 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
[2016-05-16T19:36:12.213][Instance 1][Port 52492] 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
[2016-05-16T19:36:12.213][Instance 1][Port 52492] 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
[2016-05-16T19:36:12.213][Instance 1][Port 52492] 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
[2016-05-16T19:36:12.213][Instance 1][Port 52492] 	at org.apache.http.impl.client.cache.JbdExecChain.execute(JbdExecChain.java:46)
[2016-05-16T19:36:12.213][Instance 1][Port 52492] 	at org.apache.http.impl.client.cache.CachingExec.callBackend(CachingExec.java:592)
[2016-05-16T19:36:12.213][Instance 1][Port 52492] 	at org.apache.http.impl.client.cache.CachingExec.handleCacheMiss(CachingExec.java:356)
[2016-05-16T19:36:12.214][Instance 1][Port 52492] 	at org.apache.http.impl.client.cache.CachingExec.execute(CachingExec.java:275)
[2016-05-16T19:36:12.214][Instance 1][Port 52492] 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
[2016-05-16T19:36:12.214][Instance 1][Port 52492] 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
[2016-05-16T19:36:12.214][Instance 1][Port 52492] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
[2016-05-16T19:36:12.214][Instance 1][Port 52492] 	at com.machinepublishers.jbrowserdriver.StreamConnectionClient.execute(StreamConnectionClient.java:162)
[2016-05-16T19:36:12.214][Instance 1][Port 52492] 	at com.machinepublishers.jbrowserdriver.StreamConnection.exec(StreamConnection.java:339)
[2016-05-16T19:36:12.214][Instance 1][Port 52492] 	... 11 more
[2016-05-16T19:36:12.214][Instance 1][Port 52492] Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[2016-05-16T19:36:12.215][Instance 1][Port 52492] 	at sun.security.validator.PKIXValidator.doBuild(Unknown Source)
[2016-05-16T19:36:12.215][Instance 1][Port 52492] 	at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
[2016-05-16T19:36:12.215][Instance 1][Port 52492] 	at sun.security.validator.Validator.validate(Unknown Source)
[2016-05-16T19:36:12.215][Instance 1][Port 52492] 	at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
[2016-05-16T19:36:12.215][Instance 1][Port 52492] 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
[2016-05-16T19:36:12.215][Instance 1][Port 52492] 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
[2016-05-16T19:36:12.215][Instance 1][Port 52492] 	... 34 more
[2016-05-16T19:36:12.215][Instance 1][Port 52492] Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[2016-05-16T19:36:12.215][Instance 1][Port 52492] 	at sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
[2016-05-16T19:36:12.216][Instance 1][Port 52492] 	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
[2016-05-16T19:36:12.216][Instance 1][Port 52492] 	at java.security.cert.CertPathBuilder.build(Unknown Source)
[2016-05-16T19:36:12.216][Instance 1][Port 52492] 	... 40 more
[2016-05-16T19:36:12.216][Instance 1][Port 52492] 
[2016-05-16T19:36:12.216][Instance 1][Port 52492] -Page-> https://runebet.com/ ** {timestamp: 1463427372213, state: load_failed, progress: 0.1, error: unknown_error, contentType: null, frame: 14088832}
[2016-05-16T19:36:12.369][Instance 1][Port 52492] Performing browser action, but HTTP status is 499.
[2016-05-16T19:36:12.380][Instance 1][Port 52492] Performing browser action, but HTTP status is 499.
Exception in thread "main" org.openqa.selenium.NoSuchElementException: Element not found or does not exist.
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'Ethan-PC', ip: '192.168.19.12', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_91'
Driver info: driver.version: unknown
	at com.machinepublishers.jbrowserdriver.ElementServer.validate(ElementServer.java:200)
	at com.machinepublishers.jbrowserdriver.ElementServer.access$000(ElementServer.java:61)
	at com.machinepublishers.jbrowserdriver.ElementServer$1.perform(ElementServer.java:137)
	at com.machinepublishers.jbrowserdriver.AppThread$Runner.run(AppThread.java:94)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(Unknown Source)
	at com.machinepublishers.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:94)
	at com.machinepublishers.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:53)
	at java.lang.Thread.run(Unknown Source)
`

**Comment by hollingsworthd** [comment]
I think the issue is that the SSL cert authority is not installed in your JRE by default. You can add `.ssl("compatible")` to your Settings Builder which will use Firefox's default certs pulled from https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt

**Comment by Ethan07Scape** [comment]
Sorry about that, thank you so much for the fast response!
