### ISSUE TITLE
Address is invalid on local machine, or port is not valid on remote machine

### ISSUE THREAD

**Issue by mmkaila** [MachinePublishers/jBrowserDriver#109]
Hello,

I am trying to login into https://adwords.google.co.in/KeywordPlanner via below code,

import com.machinepublishers.jbrowserdriver.Timezone;
import com.machinepublishers.jbrowserdriver.JBrowserDriver;
import com.machinepublishers.jbrowserdriver.Settings;
import org.openqa.selenium.By;

public class Example {
  public static void main(String[] args) {
    JBrowserDriver driver = new JBrowserDriver(Settings.builder().timezone(Timezone.AMERICA_NEWYORK).build());
    driver.get("https://adwords.google.co.in/KeywordPlanner");
    driver.findElement(By.linkText("Sign in to AdWords")).click();
    driver.findElement(By.id("Email")).clear();
    driver.findElement(By.id("Email")).sendKeys("XXXXXXXXXXX@gmail.com");
    driver.findElement(By.id("next")).click();
    driver.findElement(By.id("Passwd")).clear();
    driver.findElement(By.id("Passwd")).sendKeys("GOOGLE_PASSWORD");  
    driver.findElement(By.id("signIn")).click();
    System.out.println(driver.getStatusCode());
    System.out.println(driver.getPageSource());
    driver.quit();
  }
}

I am getting below error,

debug:
[2016-05-18T13:24:26.419][Instance 1][Port 50448] May 18, 2016 6:54:26 PM com.sun.webkit.network.URLLoader doRun
[2016-05-18T13:24:26.420][Instance 1][Port 50448] WARNING: Unexpected error
[2016-05-18T13:24:26.420][Instance 1][Port 50448] java.io.IOException: Connect to 224.32.32.245:443 [/224.32.32.245] failed: connect: Address is invalid on local machine, or port is not valid on remote machine: https://224.32.32.245/20310
[2016-05-18T13:24:26.421][Instance 1][Port 50448] 	at com.machinepublishers.jbrowserdriver.StreamConnection.exec(StreamConnection.java:373)
[2016-05-18T13:24:26.421][Instance 1][Port 50448] 	at com.machinepublishers.jbrowserdriver.StreamConnection.getResponseCode(StreamConnection.java:471)
[2016-05-18T13:24:26.421][Instance 1][Port 50448] 	at com.sun.webkit.network.URLLoader.receiveResponse(URLLoader.java:414)
[2016-05-18T13:24:26.421][Instance 1][Port 50448] 	at com.sun.webkit.network.URLLoader.doRun(URLLoader.java:163)
[2016-05-18T13:24:26.421][Instance 1][Port 50448] 	at com.sun.webkit.network.URLLoader.lambda$run$91(URLLoader.java:128)
[2016-05-18T13:24:26.421][Instance 1][Port 50448] 	at java.security.AccessController.doPrivileged(Native Method)
[2016-05-18T13:24:26.421][Instance 1][Port 50448] 	at com.sun.webkit.network.URLLoader.run(URLLoader.java:127)
[2016-05-18T13:24:26.421][Instance 1][Port 50448] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[2016-05-18T13:24:26.421][Instance 1][Port 50448] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[2016-05-18T13:24:26.422][Instance 1][Port 50448] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[2016-05-18T13:24:26.422][Instance 1][Port 50448] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[2016-05-18T13:24:26.423][Instance 1][Port 50448] 	at java.lang.Thread.run(Thread.java:745)
[2016-05-18T13:24:26.423][Instance 1][Port 50448] Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 224.32.32.245:443 [/224.32.32.245] failed: connect: Address is invalid on local machine, or port is not valid on remote machine
[2016-05-18T13:24:26.424][Instance 1][Port 50448] 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
[2016-05-18T13:24:26.424][Instance 1][Port 50448] 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
[2016-05-18T13:24:26.425][Instance 1][Port 50448] 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
[2016-05-18T13:24:26.425][Instance 1][Port 50448] 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
[2016-05-18T13:24:26.425][Instance 1][Port 50448] 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
[2016-05-18T13:24:26.425][Instance 1][Port 50448] 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
[2016-05-18T13:24:26.425][Instance 1][Port 50448] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
[2016-05-18T13:24:26.425][Instance 1][Port 50448] 	at com.machinepublishers.jbrowserdriver.StreamConnectionClient.execute(StreamConnectionClient.java:168)
[2016-05-18T13:24:26.425][Instance 1][Port 50448] 	at com.machinepublishers.jbrowserdriver.StreamConnection.exec(StreamConnection.java:339)
[2016-05-18T13:24:26.425][Instance 1][Port 50448] 	... 11 more
[2016-05-18T13:24:26.425][Instance 1][Port 50448] Caused by: java.net.ConnectException: connect: Address is invalid on local machine, or port is not valid on remote machine
[2016-05-18T13:24:26.425][Instance 1][Port 50448] 	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
[2016-05-18T13:24:26.425][Instance 1][Port 50448] 	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
[2016-05-18T13:24:26.426][Instance 1][Port 50448] 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[2016-05-18T13:24:26.426][Instance 1][Port 50448] 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[2016-05-18T13:24:26.428][Instance 1][Port 50448] 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[2016-05-18T13:24:26.428][Instance 1][Port 50448] 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
[2016-05-18T13:24:26.428][Instance 1][Port 50448] 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[2016-05-18T13:24:26.429][Instance 1][Port 50448] 	at java.net.Socket.connect(Socket.java:589)
[2016-05-18T13:24:26.443][Instance 1][Port 50448] 	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:337)
[2016-05-18T13:24:26.456][Instance 1][Port 50448] 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
[2016-05-18T13:24:26.456][Instance 1][Port 50448] 	... 19 more
[2016-05-18T13:24:26.456][Instance 1][Port 50448] 
[2016-05-18T13:24:26.456][Instance 1][Port 50448] May 18, 2016 6:54:26 PM com.sun.webkit.network.URLLoader doRun
[2016-05-18T13:24:26.456][Instance 1][Port 50448] WARNING: Unexpected error
[2016-05-18T13:24:26.457][Instance 1][Port 50448] java.io.IOException: Connect to 224.32.32.245:443 [/224.32.32.245] failed: connect: Address is invalid on local machine, or port is not valid on remote machine: https://224.32.32.245/20311
[2016-05-18T13:24:26.457][Instance 1][Port 50448] 	at com.machinepublishers.jbrowserdriver.StreamConnection.exec(StreamConnection.java:373)
[2016-05-18T13:24:26.457][Instance 1][Port 50448] 	at com.machinepublishers.jbrowserdriver.StreamConnection.getResponseCode(StreamConnection.java:471)
[2016-05-18T13:24:26.457][Instance 1][Port 50448] 	at com.sun.webkit.network.URLLoader.receiveResponse(URLLoader.java:414)
[2016-05-18T13:24:26.457][Instance 1][Port 50448] 	at com.sun.webkit.network.URLLoader.doRun(URLLoader.java:163)
[2016-05-18T13:24:26.457][Instance 1][Port 50448] 	at com.sun.webkit.network.URLLoader.lambda$run$91(URLLoader.java:128)
[2016-05-18T13:24:26.457][Instance 1][Port 50448] 	at java.security.AccessController.doPrivileged(Native Method)
[2016-05-18T13:24:26.458][Instance 1][Port 50448] 	at com.sun.webkit.network.URLLoader.run(URLLoader.java:127)
[2016-05-18T13:24:26.458][Instance 1][Port 50448] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[2016-05-18T13:24:26.458][Instance 1][Port 50448] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[2016-05-18T13:24:26.458][Instance 1][Port 50448] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[2016-05-18T13:24:26.458][Instance 1][Port 50448] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[2016-05-18T13:24:26.458][Instance 1][Port 50448] 	at java.lang.Thread.run(Thread.java:745)
[2016-05-18T13:24:26.458][Instance 1][Port 50448] Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 224.32.32.245:443 [/224.32.32.245] failed: connect: Address is invalid on local machine, or port is not valid on remote machine
[2016-05-18T13:24:26.458][Instance 1][Port 50448] 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
[2016-05-18T13:24:26.459][Instance 1][Port 50448] 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
[2016-05-18T13:24:26.459][Instance 1][Port 50448] 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
[2016-05-18T13:24:26.469][Instance 1][Port 50448] 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
[2016-05-18T13:24:26.469][Instance 1][Port 50448] 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
[2016-05-18T13:24:26.473][Instance 1][Port 50448] 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
[2016-05-18T13:24:26.473][Instance 1][Port 50448] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
[2016-05-18T13:24:26.474][Instance 1][Port 50448] 	at com.machinepublishers.jbrowserdriver.StreamConnectionClient.execute(StreamConnectionClient.java:168)
[2016-05-18T13:24:26.474][Instance 1][Port 50448] 	at com.machinepublishers.jbrowserdriver.StreamConnection.exec(StreamConnection.java:339)
[2016-05-18T13:24:26.474][Instance 1][Port 50448] 	... 11 more
[2016-05-18T13:24:26.474][Instance 1][Port 50448] Caused by: java.net.ConnectException: connect: Address is invalid on local machine, or port is not valid on remote machine
[2016-05-18T13:24:26.474][Instance 1][Port 50448] 	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
[2016-05-18T13:24:26.475][Instance 1][Port 50448] 	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
[2016-05-18T13:24:26.475][Instance 1][Port 50448] 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[2016-05-18T13:24:26.475][Instance 1][Port 50448] 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[2016-05-18T13:24:26.475][Instance 1][Port 50448] 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[2016-05-18T13:24:26.475][Instance 1][Port 50448] 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
[2016-05-18T13:24:26.475][Instance 1][Port 50448] 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[2016-05-18T13:24:26.475][Instance 1][Port 50448] 	at java.net.Socket.connect(Socket.java:589)
[2016-05-18T13:24:26.475][Instance 1][Port 50448] 	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:337)
[2016-05-18T13:24:26.476][Instance 1][Port 50448] 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
[2016-05-18T13:24:26.476][Instance 1][Port 50448] 	... 19 more
[2016-05-18T13:24:26.476][Instance 1][Port 50448] 
BUILD SUCCESSFUL (total time: 2 minutes 22 seconds)

**Comment by hollingsworthd** [comment]
Is everything else working?

That address is in a reserved IP range, http://www.iana.org/assignments/multicast-addresses/multicast-addresses.xhtml ... so it seems to me maybe requests should fail like that.

**Comment by mmkaila** [comment]
Nope, after that error application is being stopped and not executing next steps.
