### ISSUE TITLE
ArrayIndexOutOfBound while switch to window

### ISSUE THREAD

**Issue by anilreddy** [MachinePublishers/jBrowserDriver#116]
Hi,

While trying to switch to window observed following error.

```java
org.openqa.selenium.WebDriverException: java.lang.ArrayIndexOutOfBoundsException: -1
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'KMI-DS023474E', ip: '193.225.171.90', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_65'
Driver info: driver.version: unknown
	at com.machinepublishers.jbrowserdriver.Util.handleException(Util.java:128)
	at com.machinepublishers.jbrowserdriver.TargetLocator.window(TargetLocator.java:150)
	at com.codeborne.selenide.SelenideTargetLocator$2.apply(SelenideTargetLocator.java:105)
	at com.codeborne.selenide.SelenideTargetLocator$2.apply(SelenideTargetLocator.java:101)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
	at com.codeborne.selenide.SelenideTargetLocator.window(SelenideTargetLocator.java:162)
	at com.uprr.btp.pageobjects.BTTPageObjects.getBTTId(BTTPageObjects.java:42)
	at com.uprr.btp.regression.tests.CreateTrainAndCompareScheduleDetails.createTrainAndCompareScheduleDetails(CreateTrainAndCompareScheduleDetails.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at com.machinepublishers.jbrowserdriver.Context$4.perform(Context.java:160)
	at com.machinepublishers.jbrowserdriver.AppThread$Runner.run(AppThread.java:94)
	at com.sun.javafx.application.PlatformImpl.lambda$null$174(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$175(PlatformImpl.java:294)
	at com.machinepublishers.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:94)
	at com.machinepublishers.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:53)
	at java.lang.Thread.run(Thread.java:745)

org.openqa.selenium.WebDriverException: java.lang.ArrayIndexOutOfBoundsException: -1
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'KMI-DS023474E', ip: '193.225.171.90', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_65'
Driver info: driver.version: JBrowserDriver
	at com.machinepublishers.jbrowserdriver.Util.handleException(Util.java:128)
	at com.machinepublishers.jbrowserdriver.JBrowserDriver.quit(JBrowserDriver.java:1158)
	at com.uprr.btp.regression.tests.LoginTest.tearDownConfig(LoginTest.java:192)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at com.machinepublishers.jbrowserdriver.Context.init(Context.java:82)
	at com.machinepublishers.jbrowserdriver.JBrowserDriverServer.init(JBrowserDriverServer.java:170)
	at com.machinepublishers.jbrowserdriver.JBrowserDriverServer.getStatusCode(JBrowserDriverServer.java:252)
	at com.machinepublishers.jbrowserdriver.JBrowserDriverServer.getStatusCode(JBrowserDriverServer.java:248)
	at com.machinepublishers.jbrowserdriver.JBrowserDriverServer.quit(JBrowserDriverServer.java:583)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:323)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$256(TCPTransport.java:683)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:276)
	at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:253)
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:162)
	at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:227)
	at java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:179)
	at com.machinepublishers.jbrowserdriver.$Proxy9.quit(Unknown Source)
	at com.machinepublishers.jbrowserdriver.JBrowserDriver.quit(JBrowserDriver.java:1155)
	... 32 more
```
Thanks,
Anil

**Comment by hollingsworthd** [comment]
Can you share a test case to reproduce this? Thanks!

**Comment by hollingsworthd** [comment]
Can you share a test case to reproduce this? Thanks!

**Comment by anilreddy** [comment]
@hollingsworthd Here you go..!!

```java
	@Test
	public void windowTest() {
		driver = new JBrowserDriver(Settings.builder().ajaxWait(20000).build());
		driver.manage().window().maximize();
		driver.get("https://superdevresources.com/open-links-popup/");
		driver.findElement(By.partialLinkText("kanishkkunal")).click();
		driver.switchTo().window("Kanishk Kunal");
		if (StringUtils.equalsIgnoreCase(driver.getTitle(), "Kanishk Kunal") ) {
			System.out.println("pass");
		} else {
			System.out.println("fail");
		}
	}
```

**Comment by hollingsworthd** [comment]
@anilreddy, thank you. The `findElement(By.partialLinkText(..))` API searches for link text visible to the user, not the href. Also the `driver.switchTo().window(..)` API uses window handles as returned from `driver.getWindowHandles()`. And I don't think you need to set ajaxWait to 20000 (20 seconds), probably something like 1000 would be more than enough (the default is 150).

```java
      driver.manage().window().maximize();
      driver.get("https://superdevresources.com/open-links-popup/");
      driver.findElement(By.partialLinkText("Open Link in Popup")).click();
      driver.switchTo().window(driver.getWindowHandles().toArray(new String[0])[1]);
      driver.pageWait();
      if (StringUtils.equalsIgnoreCase(driver.getTitle(), "Kanishk Kunal")) {
        System.out.println("pass");
      } else {
        System.out.println("fail");
      }
```

I will add an enhancement to call `driver.pageWait()` automatically after `driver.switchTo(..)`, but calling it manually like above works too (or `Thread.sleep(..)` works as well).
