### ISSUE TITLE
when i move mouse to an webelement then an annother webelement will be appear but it doesn't work and throw ElementNotVisibleException

### ISSUE THREAD

**Issue by cwnuxiaocai** [MachinePublishers/jBrowserDriver#118]
when i move mouse to an webelement then an annother webelement will be appear but it doesn't work and throw ElementNotVisibleException

my code is 
listPageNew.adressSelect.click();
       // driver.executeScript("$(\"#store-selector\").addClass(\"hover\")");
        DriverBase.delay(1);
        int i = (Integer.parseInt(DriverBase.getRandomData("int", 1)) % 4) + 1;
         listPageNew.areaSlect.getElementByIndex(1).click();
        listPageNew.adressSelect.moveToElement();
        provinceId = listPageNew.province.getElementByIndex(i).getAttribute("data-value");//获取省的ID
        String province = listPageNew.province.getElementByIndex(i).getText();
        Logger.log("列表页地区切换:选择省"+province);
        listPageNew.province.getElementByIndex(i).click();
        listPageNew.adressSelect.moveToElement();
        cityId = listPageNew.city.getElementByIndex(1).getAttribute("data-value");//获取市的ID
        String city = listPageNew.city.getElementByIndex(1).getText();
        Logger.log("列表页地区切换:选择市"+city);
        listPageNew.city.getElementByIndex(1).click();
        listPageNew.adressSelect.moveToElement();
        townId = listPageNew.town.getElementByIndex(1).getAttribute("data-value");//获取县的ID
        String town = listPageNew.town.getElementByIndex(1).getText();
        Logger.log("列表页地区切换:选择县"+town);
        listPageNew.town.getElementByIndex(1).click();
        Logger.log("配送更换为:" + province + city + town + "区域ID:" +  provinceId +"_"+ cityId+"_" + townId);

org.openqa.selenium.ElementNotVisibleException: Element is not visible.
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'BJYF-CAIJIANM', ip: '192.168.0.3', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_91'
Driver info: driver.version: unknown
	at com.machinepublishers.jbrowserdriver.ElementServer.validate(ElementServer.java:216)
	at com.machinepublishers.jbrowserdriver.ElementServer.access$200(ElementServer.java:62)
	at com.machinepublishers.jbrowserdriver.ElementServer$5.perform(ElementServer.java:276)
	at com.machinepublishers.jbrowserdriver.AppThread$Runner.run(AppThread.java:94)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.machinepublishers.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:94)
	at com.machinepublishers.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:53)
	at java.lang.Thread.run(Thread.java:745)

**Comment by hollingsworthd** [comment]
Hi, can you provide an isolated test case to reproduce this, e.g., a sample HTML page and minimal set of driver commands? Thanks!

**Comment by hollingsworthd** [comment]
Closing this for now as it's hard to reproduce this without example HTML.
