### ISSUE TITLE
Bad chunk header

### ISSUE THREAD

**Issue by master2501** [MachinePublishers/jBrowserDriver#124]
After entered login/password and submit form, the page takes to long, and then this exception is thrown, but then it continues executing and finishes the page load.

**[2016-06-03T18:28:40.364][Instance 1][Port 49233] org.apache.http.MalformedChunkCodingException: Bad chunk header**
[2016-06-03T18:28:40.365][Instance 1][Port 49233] 	at org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:278)
[2016-06-03T18:28:40.365][Instance 1][Port 49233] 	at org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:227)
[2016-06-03T18:28:40.365][Instance 1][Port 49233] 	at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:186)
[2016-06-03T18:28:40.365][Instance 1][Port 49233] 	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:137)
[2016-06-03T18:28:40.365][Instance 1][Port 49233] 	at com.machinepublishers.jbrowserdriver.Util.toBytes(Util.java:94)
[2016-06-03T18:28:40.365][Instance 1][Port 49233] 	at com.machinepublishers.jbrowserdriver.ResponseHandler.handleResponse(ResponseHandler.java:52)
[2016-06-03T18:28:40.365][Instance 1][Port 49233] 	at com.machinepublishers.jbrowserdriver.StreamConnection.getInputStream(StreamConnection.java:431)
[2016-06-03T18:28:40.366][Instance 1][Port 49233] 	at com.sun.webkit.network.URLLoader.receiveResponse(URLLoader.java:472)
[2016-06-03T18:28:40.366][Instance 1][Port 49233] 	at com.sun.webkit.network.URLLoader.doRun(URLLoader.java:143)
[2016-06-03T18:28:40.366][Instance 1][Port 49233] 	at com.sun.webkit.network.URLLoader.access$000(URLLoader.java:43)
[2016-06-03T18:28:40.366][Instance 1][Port 49233] 	at com.sun.webkit.network.URLLoader$1.run(URLLoader.java:107)
[2016-06-03T18:28:40.366][Instance 1][Port 49233] 	at com.sun.webkit.network.URLLoader$1.run(URLLoader.java:104)
[2016-06-03T18:28:40.366][Instance 1][Port 49233] 	at java.security.AccessController.doPrivileged(Native Method)
[2016-06-03T18:28:40.366][Instance 1][Port 49233] 	at com.sun.webkit.network.URLLoader.run(URLLoader.java:104)
[2016-06-03T18:28:40.366][Instance 1][Port 49233] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[2016-06-03T18:28:40.367][Instance 1][Port 49233] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[2016-06-03T18:28:40.367][Instance 1][Port 49233] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[2016-06-03T18:28:40.367][Instance 1][Port 49233] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[2016-06-03T18:28:40.367][Instance 1][Port 49233] 	at java.lang.Thread.run(Thread.java:745)
[2016-06-03T18:28:40.367][Instance 1][Port 49233]

**Comment by hollingsworthd** [comment]
Hi, can you enable http wire logging and send those? You can enable that with `Settings.builder().logWire(true)` ... that will contain full headers which might have sensitive data that you should redact and/or email to me directly (see email in my profile). Or if you have a site where I can reproduce this that works too.

**Comment by master2501** [comment]
Hi! I will send you the traces to your email as i can see, they contain sensitive data.
As well as a site where you can reproduce this.
Thank you for your quick help!
