### ISSUE TITLE
Default ssl settings

### ISSUE THREAD

**Issue by dramer** [MachinePublishers/jBrowserDriver#130]
I have a simple test to create the jbrowser, and open yahoo.com... when I open yahoo it throws this exception:

[2016-06-08T22:15:54.925][Instance 1][Port 49434] Jun 08, 2016 6:15:54 PM com.sun.webkit.network.URLLoader doRun
[2016-06-08T22:15:54.925][Instance 1][Port 49434] WARNING: Unexpected error
[2016-06-08T22:15:54.926][Instance 1][Port 49434] java.io.IOException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target: https://pclick.yahoo.com/p/s=1197775342&t=3089668321077523990&szmk=6a62c5ad-6f93-41ff-bbc4-283fb42493a8-31
[2016-06-08T22:15:54.926][Instance 1][Port 49434] 	at com.machinepublishers.jbrowserdriver.StreamConnection.exec(StreamConnection.java:373)
[2016-06-08T22:15:54.926][Instance 1][Port 49434] 	at com.machinepublishers.jbrowserdriver.StreamConnection.getResponseCode(StreamConnection.java:471)
[2016-06-08T22:15:54.926][Instance 1][Port 49434] 	at com.sun.webkit.network.URLLoader.receiveResponse(Unknown Source)
[2016-06-08T22:15:54.926][Instance 1][Port 49434] 	at com.sun.webkit.network.URLLoader.doRun(Unknown Source)
[2016-06-08T22:15:54.926][Instance 1][Port 49434] 	at com.sun.webkit.network.URLLoader.lambda$run$91(Unknown Source)
[2016-06-08T22:15:54.926][Instance 1][Port 49434] 	at java.security.AccessController.doPrivileged(Native Method)
[2016-06-08T22:15:54.926][Instance 1][Port 49434] 	at com.sun.webkit.network.URLLoader.run(Unknown Source)
[2016-06-08T22:15:54.926][Instance 1][Port 49434] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2016-06-08T22:15:54.927][Instance 1][Port 49434] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2016-06-08T22:15:54.927][Instance 1][Port 49434] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2016-06-08T22:15:54.927][Instance 1][Port 49434] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2016-06-08T22:15:54.927][Instance 1][Port 49434] 	at java.lang.Thread.run(Unknown Source)
[2016-06-08T22:15:54.927][Instance 1][Port 49434] Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[2016-06-08T22:15:54.927][Instance 1][Port 49434] 	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
[2016-06-08T22:15:54.927][Instance 1][Port 49434] 	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
[2016-06-08T22:15:54.927][Instance 1][Port 49434] 	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
[2016-06-08T22:15:54.927][Instance 1][Port 49434] 	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
[2016-06-08T22:15:54.927][Instance 1][Port 49434] 	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
[2016-06-08T22:15:54.927][Instance 1][Port 49434] 	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
[2016-06-08T22:15:54.928][Instance 1][Port 49434] 	at sun.security.ssl.Handshaker.processLoop(Unknown Source)
[2016-06-08T22:15:54.928][Instance 1][Port 49434] 	at sun.security.ssl.Handshaker.process_record(Unknown Source)
[2016-06-08T22:15:54.928][Instance 1][Port 49434] 	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
[2016-06-08T22:15:54.928][Instance 1][Port 49434] 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
[2016-06-08T22:15:54.928][Instance 1][Port 49434] 	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
[2016-06-08T22:15:54.928][Instance 1][Port 49434] 	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
[2016-06-08T22:15:54.928][Instance 1][Port 49434] 	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394)
[2016-06-08T22:15:54.928][Instance 1][Port 49434] 	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353)
[2016-06-08T22:15:54.928][Instance 1][Port 49434] 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
[2016-06-08T22:15:54.928][Instance 1][Port 49434] 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
[2016-06-08T22:15:54.934][Instance 1][Port 49434] 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
[2016-06-08T22:15:54.934][Instance 1][Port 49434] 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
[2016-06-08T22:15:54.934][Instance 1][Port 49434] 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
[2016-06-08T22:15:54.934][Instance 1][Port 49434] 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
[2016-06-08T22:15:54.934][Instance 1][Port 49434] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
[2016-06-08T22:15:54.934][Instance 1][Port 49434] 	at com.machinepublishers.jbrowserdriver.StreamConnectionClient.execute(StreamConnectionClient.java:168)
[2016-06-08T22:15:54.934][Instance 1][Port 49434] 	at com.machinepublishers.jbrowserdriver.StreamConnection.exec(StreamConnection.java:339)
[2016-06-08T22:15:54.934][Instance 1][Port 49434] 	... 11 more
[2016-06-08T22:15:54.935][Instance 1][Port 49434] Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[2016-06-08T22:15:54.935][Instance 1][Port 49434] 	at sun.security.validator.PKIXValidator.doBuild(Unknown Source)
[2016-06-08T22:15:54.935][Instance 1][Port 49434] 	at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
[2016-06-08T22:15:54.935][Instance 1][Port 49434] 	at sun.security.validator.Validator.validate(Unknown Source)
[2016-06-08T22:15:54.935][Instance 1][Port 49434] 	at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
[2016-06-08T22:15:54.935][Instance 1][Port 49434] 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
[2016-06-08T22:15:54.935][Instance 1][Port 49434] 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
[2016-06-08T22:15:54.935][Instance 1][Port 49434] 	... 30 more
[2016-06-08T22:15:54.935][Instance 1][Port 49434] Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[2016-06-08T22:15:54.935][Instance 1][Port 49434] 	at sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
[2016-06-08T22:15:54.935][Instance 1][Port 49434] 	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
[2016-06-08T22:15:54.936][Instance 1][Port 49434] 	at java.security.cert.CertPathBuilder.build(Unknown Source)
[2016-06-08T22:15:54.936][Instance 1][Port 49434] 	... 36 more
[2016-06-08T22:15:54.936][Instance 1][Port 49434]

**Comment by hollingsworthd** [comment]
When constructing JBrowserDriver use the following setting: `new JBrowserDriver(Settings.builder().ssl("compatible").build());`

This confuses enough people I think I should probably make this the default setting and will leave this issue open as an enhancement.

**Comment by dramer** [comment]
Still getting the same error. I changed my code to look like:

 JBrowserDriver driver = new JBrowserDriver(Settings.builder().ssl("compatible").build());
	    return driver;


this returns to a RemoteWebDriver instance?  protected RemoteWebDriver driver;

does that matter?

**Comment by dramer** [comment]
If I change the code to be:
 RemoteWebDriver driver = new JBrowserDriver(Settings.builder().ssl("compatible").build());
return driver;



I get this error:

JBrowserDriver(Settings.builder().ssl("compatible").build());



[2016-06-09T14:37:21.972][Instance 1][Port 54953] Jun 09, 2016 10:37:21 AM com.sun.webkit.network.URLLoader doRun
[2016-06-09T14:37:21.972][Instance 1][Port 54953] WARNING: Unexpected error
[2016-06-09T14:37:21.973][Instance 1][Port 54953] java.io.IOException: Illegal character in path at index 81: https://ad.doubleclick.net/ddm/adj/N4694.IPN346/B8647593.117055707;sz=300x250;kw=[url_encoded_publisher_data];click0=http://insight.adsrvr.org/track/clk?imp=8f73b125-2b29-4945-801a-0fcdc7f15023&ag=bahyzon&crid=02ohc7py&cf=&fq=0&td_s=www.yahoo.com&rcats=&mcat=&mste=www.yahoo.com&mfld=2&mssi=42letxob&mfsi=359qz3nkok&sv=rightmedia&uhow=106&agsa=&rgco=United%2520States&rgre=Georgia&rgme=524&rgci=Atlanta&rgz=30319&dt=PC&osf=Windows&os=Windows7&br=Firefox&svpid=23351&rlangs=en&mlang=&did=&rcxt=&tmpc=&vrtd=&osi=&osv=&daid=&dnr=0&dur=CjAKDGNoYXJnZS1hbGwtMSIgCP%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252FwESE3R0ZF9kYXRhX2V4Y2x1c2lvbnMKNgodY2hhcmdlLWFsbEludGVncmFsQnJhbmRTYWZldHkiFQj5%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F8BEghpbnRlZ3JhbAo9CiRjaGFyZ2UtYWxsSW50ZWdyYWxTdXNwaWNpb3VzQWN0aXZpdHkiFQj1%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F8BEghpbnRlZ3JhbA%253D%253D&crrelr=&r=;ord=830993;dc_lat=;dc_rdid=;tag_for_child_directed_treatment=?: https://ad.doubleclick.net/ddm/adj/N4694.IPN346/B8647593.117055707;sz=300x250;kw=[url_encoded_publisher_data];click0=http://insight.adsrvr.org/track/clk?imp=8f73b125-2b29-4945-801a-0fcdc7f15023&ag=bahyzon&crid=02ohc7py&cf=&fq=0&td_s=www.yahoo.com&rcats=&mcat=&mste=www.yahoo.com&mfld=2&mssi=42letxob&mfsi=359qz3nkok&sv=rightmedia&uhow=106&agsa=&rgco=United%20States&rgre=Georgia&rgme=524&rgci=Atlanta&rgz=30319&dt=PC&osf=Windows&os=Windows7&br=Firefox&svpid=23351&rlangs=en&mlang=&did=&rcxt=&tmpc=&vrtd=&osi=&osv=&daid=&dnr=0&dur=CjAKDGNoYXJnZS1hbGwtMSIgCP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwESE3R0ZF9kYXRhX2V4Y2x1c2lvbnMKNgodY2hhcmdlLWFsbEludGVncmFsQnJhbmRTYWZldHkiFQj5%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BEghpbnRlZ3JhbAo9CiRjaGFyZ2UtYWxsSW50ZWdyYWxTdXNwaWNpb3VzQWN0aXZpdHkiFQj1%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BEghpbnRlZ3JhbA%3D%3D&crrelr=&r=;ord=830993;dc_lat=;dc_rdid=;tag_for_child_directed_treatment=?
[2016-06-09T14:37:21.973][Instance 1][Port 54953] 	at com.machinepublishers.jbrowserdriver.StreamConnection.connect(StreamConnection.java:325)
[2016-06-09T14:37:21.973][Instance 1][Port 54953] 	at com.sun.webkit.network.URLLoader.sendRequest(Unknown Source)
[2016-06-09T14:37:21.973][Instance 1][Port 54953] 	at com.sun.webkit.network.URLLoader.doRun(Unknown Source)
[2016-06-09T14:37:21.973][Instance 1][Port 54953] 	at com.sun.webkit.network.URLLoader.lambda$run$91(Unknown Source)
[2016-06-09T14:37:21.973][Instance 1][Port 54953] 	at java.security.AccessController.doPrivileged(Native Method)
[2016-06-09T14:37:21.973][Instance 1][Port 54953] 	at com.sun.webkit.network.URLLoader.run(Unknown Source)
[2016-06-09T14:37:21.973][Instance 1][Port 54953] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2016-06-09T14:37:21.974][Instance 1][Port 54953] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2016-06-09T14:37:21.974][Instance 1][Port 54953] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2016-06-09T14:37:21.974][Instance 1][Port 54953] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2016-06-09T14:37:21.974][Instance 1][Port 54953] 	at java.lang.Thread.run(Unknown Source)
[2016-06-09T14:37:21.974][Instance 1][Port 54953] Caused by: java.net.URISyntaxException: Illegal character in path at index 81: https://ad.doubleclick.net/ddm/adj/N4694.IPN346/B8647593.117055707;sz=300x250;kw=[url_encoded_publisher_data];click0=http://insight.adsrvr.org/track/clk?imp=8f73b125-2b29-4945-801a-0fcdc7f15023&ag=bahyzon&crid=02ohc7py&cf=&fq=0&td_s=www.yahoo.com&rcats=&mcat=&mste=www.yahoo.com&mfld=2&mssi=42letxob&mfsi=359qz3nkok&sv=rightmedia&uhow=106&agsa=&rgco=United%2520States&rgre=Georgia&rgme=524&rgci=Atlanta&rgz=30319&dt=PC&osf=Windows&os=Windows7&br=Firefox&svpid=23351&rlangs=en&mlang=&did=&rcxt=&tmpc=&vrtd=&osi=&osv=&daid=&dnr=0&dur=CjAKDGNoYXJnZS1hbGwtMSIgCP%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252FwESE3R0ZF9kYXRhX2V4Y2x1c2lvbnMKNgodY2hhcmdlLWFsbEludGVncmFsQnJhbmRTYWZldHkiFQj5%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F8BEghpbnRlZ3JhbAo9CiRjaGFyZ2UtYWxsSW50ZWdyYWxTdXNwaWNpb3VzQWN0aXZpdHkiFQj1%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F8BEghpbnRlZ3JhbA%253D%253D&crrelr=&r=;ord=830993;dc_lat=;dc_rdid=;tag_for_child_directed_treatment=?
[2016-06-09T14:37:21.974][Instance 1][Port 54953] 	at java.net.URI$Parser.fail(Unknown Source)
[2016-06-09T14:37:21.974][Instance 1][Port 54953] 	at java.net.URI$Parser.checkChars(Unknown Source)
[2016-06-09T14:37:21.974][Instance 1][Port 54953] 	at java.net.URI$Parser.parseHierarchical(Unknown Source)
[2016-06-09T14:37:21.974][Instance 1][Port 54953] 	at java.net.URI$Parser.parse(Unknown Source)
[2016-06-09T14:37:21.975][Instance 1][Port 54953] 	at java.net.URI.<init>(Unknown Source)
[2016-06-09T14:37:21.975][Instance 1][Port 54953] 	at com.machinepublishers.jbrowserdriver.StreamConnection.connect(StreamConnection.java:291)
[2016-06-09T14:37:21.975][Instance 1][Port 54953] 	... 10 more
[2016-06-09T14:37:21.975][Instance 1][Port 54953] 
[2016-06-09T14:37:22.034][Instance 1][Port 54953] Jun 09, 2016 10:37:22 AM com.sun.webkit.network.URLLoader doRun
[2016-06-09T14:37:22.034][Instance 1][Port 54953] WARNING: Unexpected error
[2016-06-09T14:37:22.034][Instance 1][Port 54953] java.io.IOException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target: https://pclick.yahoo.com/p/s=1197775342&t=6176834844317228840&szmk=460ee018-9278-4223-a65d-8ce411e2ba5b-31
[2016-06-09T14:37:22.034][Instance 1][Port 54953] 	at com.machinepublishers.jbrowserdriver.StreamConnection.exec(StreamConnection.java:373)
[2016-06-09T14:37:22.034][Instance 1][Port 54953] 	at com.machinepublishers.jbrowserdriver.StreamConnection.getResponseCode(StreamConnection.java:471)
[2016-06-09T14:37:22.034][Instance 1][Port 54953] 	at com.sun.webkit.network.URLLoader.receiveResponse(Unknown Source)
[2016-06-09T14:37:22.034][Instance 1][Port 54953] 	at com.sun.webkit.network.URLLoader.doRun(Unknown Source)
[2016-06-09T14:37:22.034][Instance 1][Port 54953] 	at com.sun.webkit.network.URLLoader.lambda$run$91(Unknown Source)
[2016-06-09T14:37:22.035][Instance 1][Port 54953] 	at java.security.AccessController.doPrivileged(Native Method)
[2016-06-09T14:37:22.035][Instance 1][Port 54953] 	at com.sun.webkit.network.URLLoader.run(Unknown Source)
[2016-06-09T14:37:22.035][Instance 1][Port 54953] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2016-06-09T14:37:22.036][Instance 1][Port 54953] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2016-06-09T14:37:22.036][Instance 1][Port 54953] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2016-06-09T14:37:22.036][Instance 1][Port 54953] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2016-06-09T14:37:22.036][Instance 1][Port 54953] 	at java.lang.Thread.run(Unknown Source)
[2016-06-09T14:37:22.036][Instance 1][Port 54953] Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[2016-06-09T14:37:22.036][Instance 1][Port 54953] 	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
[2016-06-09T14:37:22.036][Instance 1][Port 54953] 	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
[2016-06-09T14:37:22.036][Instance 1][Port 54953] 	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
[2016-06-09T14:37:22.036][Instance 1][Port 54953] 	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
[2016-06-09T14:37:22.036][Instance 1][Port 54953] 	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
[2016-06-09T14:37:22.036][Instance 1][Port 54953] 	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
[2016-06-09T14:37:22.045][Instance 1][Port 54953] 	at sun.security.ssl.Handshaker.processLoop(Unknown Source)
[2016-06-09T14:37:22.045][Instance 1][Port 54953] 	at sun.security.ssl.Handshaker.process_record(Unknown Source)
[2016-06-09T14:37:22.045][Instance 1][Port 54953] 	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
[2016-06-09T14:37:22.045][Instance 1][Port 54953] 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
[2016-06-09T14:37:22.045][Instance 1][Port 54953] 	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
[2016-06-09T14:37:22.045][Instance 1][Port 54953] 	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
[2016-06-09T14:37:22.047][Instance 1][Port 54953] 	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394)
[2016-06-09T14:37:22.047][Instance 1][Port 54953] 	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353)
[2016-06-09T14:37:22.047][Instance 1][Port 54953] 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
[2016-06-09T14:37:22.047][Instance 1][Port 54953] 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
[2016-06-09T14:37:22.114][Instance 1][Port 54953] 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
[2016-06-09T14:37:22.114][Instance 1][Port 54953] 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
[2016-06-09T14:37:22.114][Instance 1][Port 54953] 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
[2016-06-09T14:37:22.114][Instance 1][Port 54953] 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
[2016-06-09T14:37:22.114][Instance 1][Port 54953] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
[2016-06-09T14:37:22.114][Instance 1][Port 54953] 	at com.machinepublishers.jbrowserdriver.StreamConnectionClient.execute(StreamConnectionClient.java:168)
[2016-06-09T14:37:22.115][Instance 1][Port 54953] 	at com.machinepublishers.jbrowserdriver.StreamConnection.exec(StreamConnection.java:339)
[2016-06-09T14:37:22.115][Instance 1][Port 54953] 	... 11 more
[2016-06-09T14:37:22.115][Instance 1][Port 54953] Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[2016-06-09T14:37:22.115][Instance 1][Port 54953] 	at sun.security.validator.PKIXValidator.doBuild(Unknown Source)
[2016-06-09T14:37:22.115][Instance 1][Port 54953] 	at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
[2016-06-09T14:37:22.115][Instance 1][Port 54953] 	at sun.security.validator.Validator.validate(Unknown Source)
[2016-06-09T14:37:22.115][Instance 1][Port 54953] 	at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
[2016-06-09T14:37:22.115][Instance 1][Port 54953] 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
[2016-06-09T14:37:22.115][Instance 1][Port 54953] 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
[2016-06-09T14:37:22.115][Instance 1][Port 54953] 	... 30 more
[2016-06-09T14:37:22.115][Instance 1][Port 54953] Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[2016-06-09T14:37:22.115][Instance 1][Port 54953] 	at sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
[2016-06-09T14:37:22.115][Instance 1][Port 54953] 	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
[2016-06-09T14:37:22.115][Instance 1][Port 54953] 	at java.security.cert.CertPathBuilder.build(Unknown Source)
[2016-06-09T14:37:22.115][Instance 1][Port 54953] 	... 36 more
[2016-06-09T14:37:22.115][Instance 1][Port 54953]

**Comment by hollingsworthd** [comment]
Two errors here: one is unexpected character error which I will investigate. The other is the SSL cert error. Unfortunately, neither error happens for me.

You might have an older version of Apache HttpComponents another dependency is pulling in, or it might be a problem with Yahoo, your ISP, or your network.

To check your transitive dependencies, run `mvn dependency:tree` in your project root... that will print a list, and look for "org.apache.httpcomponents" which should all be at version 4.5.2. If there are alternate versions, google "maven dependency exclusion" or "maven dependency management conflicting versions" to see steps on resolving it.

Otherwise, try visiting https://pclick.yahoo.com/p/s=1197775342&t=6176834844317228840&szmk=460ee018-9278-4223-a65d-8ce411e2ba5b-31 in your browser and see if you get an untrusted SSL cert warning.

**Comment by hollingsworthd** [comment]
RemoteWebDriver vs JBrowserDriver won't matter. JBrowserDriver extends RemoteWebDriver as a convenience for projects which expect it. If you store it as a RemoteWebDriver you'll lose access to a few APIs in JBrowserDriver not present in RemoteWebDriver but everything under the hood is the same.

**Comment by dramer** [comment]
cut and pasted the URL into firefox and it seems to work if a black background shows up.  Let me check the maven part.

**Comment by dramer** [comment]
I changed from checking yahoo to google and all worked fine.... Not sure how much my framework will us this headless browser....
