### ISSUE TITLE
Getting NullPointerException at populateFontFileNameMap(MacFontFinder.java:85)

### ISSUE THREAD

**Issue by vijayansrinivasan** [MachinePublishers/jBrowserDriver#133]
**Code**

```java
driver = new JBrowserDriver(Settings.builder().timezone(Timezone.ASIA_CALCUTTA).build());
driver.manage().timeouts().implicitlyWait(ICICI_MAX_TIMEOUT, TimeUnit.SECONDS);
```

Getting the following Error

- **OS:** Mac
- **JBrowser Version**:
```
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
```
- **JBrowser Version**:
``` xml
<dependency>
 <groupId>com.machinepublishers</groupId>
 <artifactId>jbrowserdriver</artifactId>
 <version>0.14.5</version>
</dependency>
```
**Exception**
```
[2016-06-14T12:12:14.651][Instance 1][Port 51738] Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
[2016-06-14T12:12:14.652][Instance 1][Port 51738] 	at com.sun.javafx.font.MacFontFinder.populateFontFileNameMap(MacFontFinder.java:85)
[2016-06-14T12:12:14.652][Instance 1][Port 51738] 	at com.sun.javafx.font.PrismFontFactory.getFullNameToFileMap(PrismFontFactory.java:1740)
[2016-06-14T12:12:14.652][Instance 1][Port 51738] 	at com.sun.javafx.font.PrismFontFactory.getFontFamilyNames(PrismFontFactory.java:1279)
[2016-06-14T12:12:14.652][Instance 1][Port 51738] 	at com.sun.javafx.webkit.prism.WCFontImpl.getFont(WCFontImpl.java:63)
[2016-06-14T12:12:14.652][Instance 1][Port 51738] 	at com.sun.javafx.webkit.prism.PrismGraphicsManager.getWCFont(PrismGraphicsManager.java:79)
[2016-06-14T12:12:14.652][Instance 1][Port 51738] 	at com.sun.webkit.network.URLLoader.twkDidFinishLoading(Native Method)
[2016-06-14T12:12:14.652][Instance 1][Port 51738] 	at com.sun.webkit.network.URLLoader.notifyDidFinishLoading(URLLoader.java:838)
[2016-06-14T12:12:14.652][Instance 1][Port 51738] 	at com.sun.webkit.network.URLLoader.lambda$didFinishLoading$96(URLLoader.java:829)
[2016-06-14T12:12:14.653][Instance 1][Port 51738] 	at com.sun.javafx.application.PlatformImpl.lambda$null$174(PlatformImpl.java:295)
[2016-06-14T12:12:14.653][Instance 1][Port 51738] 	at java.security.AccessController.doPrivileged(Native Method)
[2016-06-14T12:12:14.653][Instance 1][Port 51738] 	at com.sun.javafx.application.PlatformImpl.lambda$runLater$175(PlatformImpl.java:294)
[2016-06-14T12:12:14.653][Instance 1][Port 51738] 	at com.machinepublishers.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:94)
[2016-06-14T12:12:14.653][Instance 1][Port 51738] 	at com.machinepublishers.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:53)
[2016-06-14T12:12:14.653][Instance 1][Port 51738] 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by hollingsworthd** [comment]
Thanks for the details. Can you let me know if this solves the problem: http://stackoverflow.com/questions/35893983/npe-on-javafx-applications-on-mac

**Comment by hollingsworthd** [comment]
I think this is probably nothing this project can fix and that it's a JRE bug as described in the previous link. Closing this issue for now.

**Comment by vijayan007** [comment]
- Restoring standard fonts in "Font Book" app solved this problem
- Source : https://bugs.openjdk.java.net/browse/JDK-8089900
- Note: This will remove all the microsoft fonts
