### ISSUE TITLE
Missing information in Exceptions/Stacktraces

### ISSUE THREAD

**Issue by sterfpaul** [MachinePublishers/jBrowserDriver#134]
I'm getting some ElementNotVisibleExceptions that don't contain a lot of useful information. I'm missing the xpath query used to look for the element.

Also missing the part of the stacktrace where my own code was running. This makes it hard to pinpoint what element was missing.

```
org.openqa.selenium.ElementNotVisibleException: Element is not visible.
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: ...
Driver info: driver.version: unknown
        at com.machinepublishers.jbrowserdriver.ElementServer.validate(ElementServer.java:216)
        at com.machinepublishers.jbrowserdriver.ElementServer.access$200(ElementServer.java:62)
        at com.machinepublishers.jbrowserdriver.ElementServer$5.perform(ElementServer.java:276)
        at com.machinepublishers.jbrowserdriver.AppThread$Runner.run(AppThread.java:94)
        at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
        at com.machinepublishers.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:94)
        at com.machinepublishers.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:53)
        at java.lang.Thread.run(Thread.java:745)
        at ✽.Given user is logged in as Account user(coupling-management.feature:37)

```

**Comment by sterfpaul** [comment]
This seems to happen when i use .switchTo().activeElement() and the element doesn't exist.

**Comment by Vistritium** [comment]
This issue may be fixed by removing those lines: https://github.com/MachinePublishers/jBrowserDriver/blob/a0b2fe51815e982f037ca3882a386fb1c2cb6ff0/src/com/machinepublishers/jbrowserdriver/Util.java#L120-L122
Or any other solution that will create new exception that wraps the selenium Exception.

**Comment by hollingsworthd** [comment]
@Vistritium, thanks! The Selenium exceptions are wrapped now in a class of their same subtype.
