### ISSUE TITLE
Problem parsing urls 

### ISSUE THREAD

**Issue by master2501** [MachinePublishers/jBrowserDriver#136]
[2016-06-16T18:25:26.408][Instance 1][Port 49751] jun 16, 2016 8:25:26 PM com.sun.webkit.network.URLLoader doRun
[2016-06-16T18:25:26.408][Instance 1][Port 49751] WARNING: Unexpected error
[2016-06-16T18:25:26.409][Instance 1][Port 49751] java.io.IOException: Illegal character in path at index 82: https://ad.doubleclick.net/ddm/activity/src=4816210;type=invmedia;cat=l9lvwsnk;u2=[2016516202526];u3=[https://trade.24option.com/24option/?lang=es];u4=[DefaultLangByPath];ord=1?&_rnd=0.3836657041683793: https://ad.doubleclick.net/ddm/activity/src=4816210;type=invmedia;cat=l9lvwsnk;u2=[2016516202526];u3=[https://trade.24option.com/24option/?lang=es];u4=[DefaultLangByPath];ord=1?&_rnd=0.3836657041683793
[2016-06-16T18:25:26.409][Instance 1][Port 49751] 	at com.machinepublishers.jbrowserdriver.StreamConnection.connect(StreamConnection.java:325)
[2016-06-16T18:25:26.409][Instance 1][Port 49751] 	at com.sun.webkit.network.URLLoader.sendRequest(URLLoader.java:326)
[2016-06-16T18:25:26.409][Instance 1][Port 49751] 	at com.sun.webkit.network.URLLoader.doRun(URLLoader.java:142)
[2016-06-16T18:25:26.409][Instance 1][Port 49751] 	at com.sun.webkit.network.URLLoader.access$000(URLLoader.java:43)
[2016-06-16T18:25:26.409][Instance 1][Port 49751] 	at com.sun.webkit.network.URLLoader$1.run(URLLoader.java:107)
[2016-06-16T18:25:26.410][Instance 1][Port 49751] 	at com.sun.webkit.network.URLLoader$1.run(URLLoader.java:104)
[2016-06-16T18:25:26.410][Instance 1][Port 49751] 	at java.security.AccessController.doPrivileged(Native Method)
[2016-06-16T18:25:26.410][Instance 1][Port 49751] 	at com.sun.webkit.network.URLLoader.run(URLLoader.java:104)
[2016-06-16T18:25:26.410][Instance 1][Port 49751] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[2016-06-16T18:25:26.410][Instance 1][Port 49751] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[2016-06-16T18:25:26.410][Instance 1][Port 49751] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[2016-06-16T18:25:26.411][Instance 1][Port 49751] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[2016-06-16T18:25:26.411][Instance 1][Port 49751] 	at java.lang.Thread.run(Thread.java:745)
**[2016-06-16T18:25:26.411][Instance 1][Port 49751] Caused by: java.net.URISyntaxException: Illegal character in path at index 82: https://ad.doubleclick.net/ddm/activity/src=4816210;type=invmedia;cat=l9lvwsnk;u2=[2016516202526];u3=[https://trade.24option.com/24option/?lang=es];u4=[DefaultLangByPath];ord=1?&_rnd=0.3836657041683793**
[2016-06-16T18:25:26.411][Instance 1][Port 49751] 	at java.net.URI$Parser.fail(URI.java:2848)
[2016-06-16T18:25:26.411][Instance 1][Port 49751] 	at java.net.URI$Parser.checkChars(URI.java:3021)
[2016-06-16T18:25:26.411][Instance 1][Port 49751] 	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
[2016-06-16T18:25:26.412][Instance 1][Port 49751] 	at java.net.URI$Parser.parse(URI.java:3053)
[2016-06-16T18:25:26.412][Instance 1][Port 49751] 	at java.net.URI.<init>(URI.java:588)
[2016-06-16T18:25:26.412][Instance 1][Port 49751] 	at com.machinepublishers.jbrowserdriver.StreamConnection.connect(StreamConnection.java:291)
[2016-06-16T18:25:26.412][Instance 1][Port 49751] 	... 12 more
[2016-06-16T18:25:26.412][Instance 1][Port 49751] 
[2016-06-16T18:25:26.476][Instance 1][Port 49751] jun 16, 2016 8:25:26 PM com.sun.webkit.network.URLLoader doRun
[2016-06-16T18:25:26.477][Instance 1][Port 49751] WARNING: Unexpected error
[2016-06-16T18:25:26.477][Instance 1][Port 49751] java.io.IOException: URI does not specify a valid host name: https:/: https:/
[2016-06-16T18:25:26.477][Instance 1][Port 49751] 	at com.machinepublishers.jbrowserdriver.StreamConnection.exec(StreamConnection.java:373)
[2016-06-16T18:25:26.477][Instance 1][Port 49751] 	at com.machinepublishers.jbrowserdriver.StreamConnection.getResponseCode(StreamConnection.java:471)
[2016-06-16T18:25:26.477][Instance 1][Port 49751] 	at com.sun.webkit.network.URLLoader.receiveResponse(URLLoader.java:387)
[2016-06-16T18:25:26.477][Instance 1][Port 49751] 	at com.sun.webkit.network.URLLoader.doRun(URLLoader.java:143)
[2016-06-16T18:25:26.477][Instance 1][Port 49751] 	at com.sun.webkit.network.URLLoader.access$000(URLLoader.java:43)
[2016-06-16T18:25:26.478][Instance 1][Port 49751] 	at com.sun.webkit.network.URLLoader$1.run(URLLoader.java:107)
[2016-06-16T18:25:26.478][Instance 1][Port 49751] 	at com.sun.webkit.network.URLLoader$1.run(URLLoader.java:104)
[2016-06-16T18:25:26.478][Instance 1][Port 49751] 	at java.security.AccessController.doPrivileged(Native Method)
[2016-06-16T18:25:26.478][Instance 1][Port 49751] 	at com.sun.webkit.network.URLLoader.run(URLLoader.java:104)
[2016-06-16T18:25:26.478][Instance 1][Port 49751] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[2016-06-16T18:25:26.478][Instance 1][Port 49751] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[2016-06-16T18:25:26.478][Instance 1][Port 49751] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[2016-06-16T18:25:26.478][Instance 1][Port 49751] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[2016-06-16T18:25:26.479][Instance 1][Port 49751] 	at java.lang.Thread.run(Thread.java:745)
[2016-06-16T18:25:26.479][Instance 1][Port 49751] Caused by: org.apache.http.client.ClientProtocolException: URI does not specify a valid host name: https:/
[2016-06-16T18:25:26.479][Instance 1][Port 49751] 	at org.apache.http.impl.client.CloseableHttpClient.determineTarget(CloseableHttpClient.java:94)
[2016-06-16T18:25:26.479][Instance 1][Port 49751] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
[2016-06-16T18:25:26.479][Instance 1][Port 49751] 	at com.machinepublishers.jbrowserdriver.StreamConnectionClient.execute(StreamConnectionClient.java:168)
[2016-06-16T18:25:26.479][Instance 1][Port 49751] 	at com.machinepublishers.jbrowserdriver.StreamConnection.exec(StreamConnection.java:339)
[2016-06-16T18:25:26.479][Instance 1][Port 49751] 	... 13 more
[2016-06-16T18:25:26.479][Instance 1][Port 49751] 
[2016-06-16T18:25:26.600][Instance 1][Port 49751] jun 16, 2016 8:25:26 PM com.sun.webkit.network.URLLoader doRun
[2016-06-16T18:25:26.601][Instance 1][Port 49751] WARNING: Unexpected error
[2016-06-16T18:25:26.601][Instance 1][Port 49751] java.io.IOException: URI does not specify a valid host name: https:/: https:/
[2016-06-16T18:25:26.601][Instance 1][Port 49751] 	at com.machinepublishers.jbrowserdriver.StreamConnection.exec(StreamConnection.java:373)
[2016-06-16T18:25:26.601][Instance 1][Port 49751] 	at com.machinepublishers.jbrowserdriver.StreamConnection.getResponseCode(StreamConnection.java:471)
[2016-06-16T18:25:26.601][Instance 1][Port 49751] 	at com.sun.webkit.network.URLLoader.receiveResponse(URLLoader.java:387)
[2016-06-16T18:25:26.601][Instance 1][Port 49751] 	at com.sun.webkit.network.URLLoader.doRun(URLLoader.java:143)
[2016-06-16T18:25:26.602][Instance 1][Port 49751] 	at com.sun.webkit.network.URLLoader.access$000(URLLoader.java:43)
[2016-06-16T18:25:26.602][Instance 1][Port 49751] 	at com.sun.webkit.network.URLLoader$1.run(URLLoader.java:107)
[2016-06-16T18:25:26.602][Instance 1][Port 49751] 	at com.sun.webkit.network.URLLoader$1.run(URLLoader.java:104)
[2016-06-16T18:25:26.602][Instance 1][Port 49751] 	at java.security.AccessController.doPrivileged(Native Method)
[2016-06-16T18:25:26.602][Instance 1][Port 49751] 	at com.sun.webkit.network.URLLoader.run(URLLoader.java:104)
[2016-06-16T18:25:26.602][Instance 1][Port 49751] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[2016-06-16T18:25:26.602][Instance 1][Port 49751] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[2016-06-16T18:25:26.602][Instance 1][Port 49751] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[2016-06-16T18:25:26.603][Instance 1][Port 49751] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[2016-06-16T18:25:26.603][Instance 1][Port 49751] 	at java.lang.Thread.run(Thread.java:745)
[2016-06-16T18:25:26.603][Instance 1][Port 49751] Caused by: org.apache.http.client.ClientProtocolException: URI does not specify a valid host name: https:/
[2016-06-16T18:25:26.603][Instance 1][Port 49751] 	at org.apache.http.impl.client.CloseableHttpClient.determineTarget(CloseableHttpClient.java:94)
[2016-06-16T18:25:26.603][Instance 1][Port 49751] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
[2016-06-16T18:25:26.603][Instance 1][Port 49751] 	at com.machinepublishers.jbrowserdriver.StreamConnectionClient.execute(StreamConnectionClient.java:168)
[2016-06-16T18:25:26.603][Instance 1][Port 49751] 	at com.machinepublishers.jbrowserdriver.StreamConnection.exec(StreamConnection.java:339)
[2016-06-16T18:25:26.603][Instance 1][Port 49751] 	... 13 more
[2016-06-16T18:25:26.603][Instance 1][Port 49751]

**Comment by master2501** [comment]
more logging...


[2016-06-16T18:25:45.888][Instance 1][Port 49751] jun 16, 2016 8:25:45 PM com.sun.webkit.network.URLLoader doRun
[2016-06-16T18:25:45.889][Instance 1][Port 49751] WARNING: Unexpected error
[2016-06-16T18:25:45.889][Instance 1][Port 49751] java.io.IOException: Illegal character in path at index 82: https://ad.doubleclick.net/ddm/activity/src=4816210;type=invmedia;cat=l9lvwsnk;u2=[2016516202545];u3=[https://trade.24option.com/24option/?lang=es];u4=[DefaultLangByPath];ord=1?&_rnd=0.4906241660937667: https://ad.doubleclick.net/ddm/activity/src=4816210;type=invmedia;cat=l9lvwsnk;u2=[2016516202545];u3=[https://trade.24option.com/24option/?lang=es];u4=[DefaultLangByPath];ord=1?&_rnd=0.4906241660937667
[2016-06-16T18:25:45.889][Instance 1][Port 49751] 	at com.machinepublishers.jbrowserdriver.StreamConnection.connect(StreamConnection.java:325)
[2016-06-16T18:25:45.889][Instance 1][Port 49751] 	at com.sun.webkit.network.URLLoader.sendRequest(URLLoader.java:326)
[2016-06-16T18:25:45.889][Instance 1][Port 49751] 	at com.sun.webkit.network.URLLoader.doRun(URLLoader.java:142)
[2016-06-16T18:25:45.889][Instance 1][Port 49751] 	at com.sun.webkit.network.URLLoader.access$000(URLLoader.java:43)
[2016-06-16T18:25:45.889][Instance 1][Port 49751] 	at com.sun.webkit.network.URLLoader$1.run(URLLoader.java:107)
[2016-06-16T18:25:45.889][Instance 1][Port 49751] 	at com.sun.webkit.network.URLLoader$1.run(URLLoader.java:104)
[2016-06-16T18:25:45.889][Instance 1][Port 49751] 	at java.security.AccessController.doPrivileged(Native Method)
[2016-06-16T18:25:45.889][Instance 1][Port 49751] 	at com.sun.webkit.network.URLLoader.run(URLLoader.java:104)
[2016-06-16T18:25:45.890][Instance 1][Port 49751] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[2016-06-16T18:25:45.890][Instance 1][Port 49751] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[2016-06-16T18:25:45.890][Instance 1][Port 49751] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[2016-06-16T18:25:45.890][Instance 1][Port 49751] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[2016-06-16T18:25:45.890][Instance 1][Port 49751] 	at java.lang.Thread.run(Thread.java:745)
[2016-06-16T18:25:45.890][Instance 1][Port 49751] Caused by: java.net.URISyntaxException: Illegal character in path at index 82: https://ad.doubleclick.net/ddm/activity/src=4816210;type=invmedia;cat=l9lvwsnk;u2=[2016516202545];u3=[https://trade.24option.com/24option/?lang=es];u4=[DefaultLangByPath];ord=1?&_rnd=0.4906241660937667
[2016-06-16T18:25:45.890][Instance 1][Port 49751] 	at java.net.URI$Parser.fail(URI.java:2848)
[2016-06-16T18:25:45.890][Instance 1][Port 49751] 	at java.net.URI$Parser.checkChars(URI.java:3021)
[2016-06-16T18:25:45.890][Instance 1][Port 49751] 	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
[2016-06-16T18:25:45.890][Instance 1][Port 49751] 	at java.net.URI$Parser.parse(URI.java:3053)
[2016-06-16T18:25:45.891][Instance 1][Port 49751] 	at java.net.URI.<init>(URI.java:588)
[2016-06-16T18:25:45.891][Instance 1][Port 49751] 	at com.machinepublishers.jbrowserdriver.StreamConnection.connect(StreamConnection.java:291)
[2016-06-16T18:25:45.891][Instance 1][Port 49751] 	... 12 more
[2016-06-16T18:25:45.891][Instance 1][Port 49751] 
[2016-06-16T18:25:45.956][Instance 1][Port 49751] jun 16, 2016 8:25:45 PM com.sun.webkit.network.URLLoader doRun
[2016-06-16T18:25:45.956][Instance 1][Port 49751] WARNING: Unexpected error
[2016-06-16T18:25:45.956][Instance 1][Port 49751] java.io.IOException: URI does not specify a valid host name: https:/: https:/
[2016-06-16T18:25:45.956][Instance 1][Port 49751] 	at com.machinepublishers.jbrowserdriver.StreamConnection.exec(StreamConnection.java:373)
[2016-06-16T18:25:45.956][Instance 1][Port 49751] 	at com.machinepublishers.jbrowserdriver.StreamConnection.getResponseCode(StreamConnection.java:471)
[2016-06-16T18:25:45.956][Instance 1][Port 49751] 	at com.sun.webkit.network.URLLoader.receiveResponse(URLLoader.java:387)
[2016-06-16T18:25:45.956][Instance 1][Port 49751] 	at com.sun.webkit.network.URLLoader.doRun(URLLoader.java:143)
[2016-06-16T18:25:45.957][Instance 1][Port 49751] 	at com.sun.webkit.network.URLLoader.access$000(URLLoader.java:43)
[2016-06-16T18:25:45.957][Instance 1][Port 49751] 	at com.sun.webkit.network.URLLoader$1.run(URLLoader.java:107)
[2016-06-16T18:25:45.957][Instance 1][Port 49751] 	at com.sun.webkit.network.URLLoader$1.run(URLLoader.java:104)
[2016-06-16T18:25:45.957][Instance 1][Port 49751] 	at java.security.AccessController.doPrivileged(Native Method)
[2016-06-16T18:25:45.957][Instance 1][Port 49751] 	at com.sun.webkit.network.URLLoader.run(URLLoader.java:104)
[2016-06-16T18:25:45.957][Instance 1][Port 49751] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[2016-06-16T18:25:45.957][Instance 1][Port 49751] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[2016-06-16T18:25:45.957][Instance 1][Port 49751] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[2016-06-16T18:25:45.957][Instance 1][Port 49751] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[2016-06-16T18:25:45.958][Instance 1][Port 49751] 	at java.lang.Thread.run(Thread.java:745)

**Comment by master2501** [comment]
If i block ads, this kind of errors doesn't happen.

Another problem are the websockets, having timeout errors like this one:

[2016-06-16T18:25:55.531][Instance 1][Port 49751] jun 16, 2016 8:25:55 PM com.sun.webkit.network.URLLoader doRun
[2016-06-16T18:25:55.531][Instance 1][Port 49751] WARNING: Unexpected error
[2016-06-16T18:25:55.531][Instance 1][Port 49751] java.io.IOException: Read timed out: https://ws.24option.com/userdata/GetLoggedinUser
[2016-06-16T18:25:55.531][Instance 1][Port 49751] 	at com.machinepublishers.jbrowserdriver.StreamConnection.exec(StreamConnection.java:373)
[2016-06-16T18:25:55.531][Instance 1][Port 49751] 	at com.machinepublishers.jbrowserdriver.StreamConnection.getResponseCode(StreamConnection.java:471)
[2016-06-16T18:25:55.531][Instance 1][Port 49751] 	at com.sun.webkit.network.URLLoader.receiveResponse(URLLoader.java:387)
[2016-06-16T18:25:55.531][Instance 1][Port 49751] 	at com.sun.webkit.network.URLLoader.doRun(URLLoader.java:143)
[2016-06-16T18:25:55.531][Instance 1][Port 49751] 	at com.sun.webkit.network.URLLoader.access$000(URLLoader.java:43)
[2016-06-16T18:25:55.532][Instance 1][Port 49751] 	at com.sun.webkit.network.URLLoader$1.run(URLLoader.java:107)
[2016-06-16T18:25:55.532][Instance 1][Port 49751] 	at com.sun.webkit.network.URLLoader$1.run(URLLoader.java:104)
[2016-06-16T18:25:55.532][Instance 1][Port 49751] 	at java.security.AccessController.doPrivileged(Native Method)
[2016-06-16T18:25:55.532][Instance 1][Port 49751] 	at com.sun.webkit.network.URLLoader.run(URLLoader.java:104)
[2016-06-16T18:25:55.532][Instance 1][Port 49751] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[2016-06-16T18:25:55.532][Instance 1][Port 49751] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[2016-06-16T18:25:55.532][Instance 1][Port 49751] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[2016-06-16T18:25:55.532][Instance 1][Port 49751] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[2016-06-16T18:25:55.532][Instance 1][Port 49751] 	at java.lang.Thread.run(Thread.java:745)
[2016-06-16T18:25:55.532][Instance 1][Port 49751] Caused by: java.net.SocketTimeoutException: Read timed out
[2016-06-16T18:25:55.532][Instance 1][Port 49751] 	at java.net.SocketInputStream.socketRead0(Native Method)
