### ISSUE TITLE
Can't create JBrowserDriver anymore since some hours

### ISSUE THREAD

**Issue by PatrickHuetter** [MachinePublishers/jBrowserDriver#137]
I'm building my software with clean java docker containers with all dependencies for jBrowserDriver installed (so there can't anything change) but since today i can't run newly built projects with jBrowserDriver anymore. When a JBrowserDriver instance get created while runtime i get the following exception.

```
Caused by: org.openqa.selenium.WebDriverException: java.lang.NoSuchMethodError: io.github.lukehutch.fastclasspathscanner.classpath.ClasspathFinder.getUniqueClasspathElements()Ljava/util/ArrayList;
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'Patricks-Macbook-Pro.local', ip: '192.168.188.21', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.5', java.version: '1.8.0_25'
Driver info: driver.version: JBrowserDriver
        at com.machinepublishers.jbrowserdriver.Util.handleException(Util.java:128)
        at com.machinepublishers.jbrowserdriver.JBrowserDriver.<clinit>(JBrowserDriver.java:161)
        ... 22 more
Caused by: java.lang.NoSuchMethodError: io.github.lukehutch.fastclasspathscanner.classpath.ClasspathFinder.getUniqueClasspathElements()Ljava/util/ArrayList;
        at com.machinepublishers.jbrowserdriver.JBrowserDriver.<clinit>(JBrowserDriver.java:128)
        ... 22 more
```
```
java.lang.NoClassDefFoundError: Could not initialize class com.machinepublishers.jbrowserdriver.JBrowserDriver
```

I think something has changed with the lukehutch fastclasspathscanner dependency as i also could figure out that you've already done some fixes within the current jBrowserDriver version 0.14.5 (which i am using). Or may this be because i'm using groovy?

**Comment by hollingsworthd** [comment]
Thanks for the info. Fixed in v0.14.6 which is released to Maven Central.
