### ISSUE TITLE
Exception during screenshot

### ISSUE THREAD

**Issue by oahzuw** [MachinePublishers/jBrowserDriver#16]
i try like this
driver.manage().addCookie(name, value);
but did not succeed

**Comment by hollingsworthd** [comment]
For now, use the constructor which sets domain, path and date too: `driver.manage().addCookie(new Cookie("name", "value", "example.com", "/", null));`

This is related to #10. Cookie validation is a little bit too strict.

**Comment by oahzuw** [comment]
thanks, really can be used

**Comment by oahzuw** [comment]
After setting cookie
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.sun.javafx.webkit.UIClientImpl.toBufferedImage(UIClientImpl.java:321)
	at com.sun.javafx.webkit.prism.PrismImage.toDataURL(PrismImage.java:67)
	at com.sun.webkit.network.URLLoader.twkDidFinishLoading(Native Method)
	at com.sun.webkit.network.URLLoader.notifyDidFinishLoading(URLLoader.java:838)
	at com.sun.webkit.network.URLLoader.lambda$didFinishLoading$96(URLLoader.java:829)
	at com.sun.javafx.application.PlatformImpl.lambda$null$174(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$175(PlatformImpl.java:294)
	at com.sun.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:93)
	at com.sun.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:51)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: sun.awt.image.IntegerInterleavedRaster cannot be cast to sun.awt.image.IntegerComponentRaster
	at javafx.embed.swing.SwingFXUtils.fromFXImage(SwingFXUtils.java:257)
	... 15 more
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.sun.javafx.webkit.UIClientImpl.toBufferedImage(UIClientImpl.java:321)
	at com.sun.javafx.webkit.prism.PrismImage.toDataURL(PrismImage.java:67)
	at com.sun.webkit.Timer.twkFireTimerEvent(Native Method)
	at com.sun.webkit.Timer.fireTimerEvent(Timer.java:83)
	at com.sun.webkit.Timer.notifyTick(Timer.java:64)
	at javafx.scene.web.WebEngine$PulseTimer.lambda$static$45(WebEngine.java:1201)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$31(Toolkit.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$405(QuantumToolkit.java:319)
	at com.sun.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:93)
	at com.sun.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:51)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: sun.awt.image.IntegerInterleavedRaster cannot be cast to sun.awt.image.IntegerComponentRaster
	at javafx.embed.swing.SwingFXUtils.fromFXImage(SwingFXUtils.java:257)
	... 20 more

Not set, no exceptions

**Comment by hollingsworthd** [comment]
I suspect there might be an issue taking screenshots on Windows OS. This is a bug of some sort, not sure yet.
