### ISSUE TITLE
Chaining findElement calls with 3rdparty locators fails with NotSerializableException

### ISSUE THREAD

**Issue by tfnico** [MachinePublishers/jBrowserDriver#170]
I'm using jBrowserDriver version 0.15.0.

Usually it's possible to chain findElement calls like this:

        driver.findElement(By.id("foo")).findElement(By.id("bar"));

Entering a foreign locator, like done in #114 and #151 (not sure if they are related) in the mix also works as long as it's called directly from the driver:

        driver.findElement(ByAngular.model("foo")).findElement(By.id("bar"));

But once I start using the result of the first locator to find more, I get the NotSerializableException:

        driver.findElement(ByAngular.model("foo")).findElement(ByAngular.model("bar"));

Here's the stacktrace (I think it's pretty much the same as the one I posted in #114):

```
org.openqa.selenium.WebDriverException: com.paulhammant.ngwebdriver.ByAngularModel
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'Thomass-MacBook-Pro-Gilon.local', ip: '192.168.11.71', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.5', java.version: '1.8.0_73'
Driver info: driver.version: unknown
  at com.machinepublishers.jbrowserdriver.Util.handleException(Util.java:140)
  at com.machinepublishers.jbrowserdriver.Element.findElement(Element.java:335)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:497)
  at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement$1.invoke(EventFiringWebDriver.java:335)
  at com.sun.proxy.$Proxy21.findElement(Unknown Source)
  at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.findElement(EventFiringWebDriver.java:410)
  at com.company.webtest.SubmissionStepDefs.iAddASampleLikeThis(SubmissionStepDefs.java:50)
  at ✽.And I add a sample like this(insert_technical_data.feature:13)
Caused by: java.io.NotSerializableException: com.paulhammant.ngwebdriver.ByAngularModel
  at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
  at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
  at sun.rmi.server.UnicastRef.marshalValue(UnicastRef.java:294)
  at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:153)
  at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:227)
  at java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:179)
  at com.machinepublishers.jbrowserdriver.$Proxy20.findElement(Unknown Source)
  at com.machinepublishers.jbrowserdriver.Element.findElement(Element.java:332)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:497)
  at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement$1.invoke(EventFiringWebDriver.java:335)
  at com.sun.proxy.$Proxy21.findElement(Unknown Source)
  at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.findElement(EventFiringWebDriver.java:410)
  at com.company.webtest.SubmissionStepDefs.iAddASampleLikeThis(SubmissionStepDefs.java:50)
```

**Comment by tfnico** [comment]
Just confirmed that this works now in the current 0.15.1-SNAPSHOT. Thanks a lot for the fast fix!
