### ISSUE TITLE
Cannot launch browser

### ISSUE THREAD

**Issue by aviszlay** [MachinePublishers/jBrowserDriver#171]
Trying to run the example code from the project homepage, getting this error:

> [2016-07-26T11:20:02.377] java.lang.ExceptionInInitializerError
[2016-07-26T11:20:02.377] 	at com.machinepublishers.jbrowserdriver.JBrowserDriverServer.main(JBrowserDriverServer.java:76)
[2016-07-26T11:20:02.377] Caused by: java.lang.ArrayStoreException: org.apache.http.impl.cookie.RFC2965VersionAttributeHandler
[2016-07-26T11:20:02.377] 	at org.apache.http.impl.cookie.JbdCookieSpecProvider.create(JbdCookieSpecProvider.java:74)
[2016-07-26T11:20:02.377] 	at com.machinepublishers.jbrowserdriver.CookieStore.<clinit>(CookieStore.java:44)
[2016-07-26T11:20:02.377] 	... 1 more
Exception in thread "main" org.openqa.selenium.WebDriverException: Could not launch browser.
Build info: version: '2.41.0', revision: '3192d8a6c4449dc285928ba024779344f5423c58', time: '2014-03-27 11:29:39'
System info: host: 'MacBook-Pro-Econ.local', ip: '172.17.116.15', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.2', java.version: '1.8.0_91'

**Comment by hollingsworthd** [comment]
This might be happening based specifically on how the app is being built and run. If you can provide either the IDE project files or build scripts or info about them it would make reproducing this easier. Thanks.

**Comment by aviszlay** [comment]
@hollingsworthd Your answer gave me a clue; i cleaned up the project, removed some unused dependencies and voila, everything works.  It seems there was some clash of dependencies. 
I'll slowly add more stuff to the project and see what happens but at this point i'm fairly convinced this isn't a bug in jBrowserDriver. Sorry for the false alarm.
