### ISSUE TITLE
NullPointerException closing client

### ISSUE THREAD

**Issue by nycoder67** [MachinePublishers/jBrowserDriver#189]
I'm getting NullPointerException on driver.close() as of 0.16.0. The problem persists through 0.16.4 while version 0.15.0 (immediately prior to 0.16.0) works. In case it matters, I'm using JDK 1.8.0_40 on Windows 7.

Partial stack trace:

```
Caused by: java.lang.NullPointerException
	at com.machinepublishers.jbrowserdriver.JBrowserDriverServer.getStatusCode(JBrowserDriverServer.java:253)
	at com.machinepublishers.jbrowserdriver.JBrowserDriverServer.getStatusCode(JBrowserDriverServer.java:247)
	at com.machinepublishers.jbrowserdriver.JBrowserDriverServer.quit(JBrowserDriverServer.java:589)
```

I suspect this commit may be a factor since it is ultimately the getStatusCode() method that fails:
https://github.com/MachinePublishers/jBrowserDriver/commit/39ff212ca48ebe1750f6fed18ecf361e2c807b0f

Thank you for all the work on the project!

**Comment by jackrusher** [comment]
I came to report this bug, but I'd also like to say thanks for the all the work you've put into this library!

**Comment by Zero3** [comment]
I'm seeing the same bug. For now, I'm just calling `.quit()` instead. Not sure what the difference between these methods are though.
