### ISSUE TITLE
What dependencies on centos 7.2?

### ISSUE THREAD

**Issue by caokaifang** [MachinePublishers/jBrowserDriver#193]
Graphics Device initialization failed for : sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:221)
at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:205)
at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:209)
at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:675)
at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:695)
at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$156(LauncherImpl.java:182)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)

**Comment by caokaifang** [comment]
jBrowserDriver:0.16.4

**Comment by hollingsworthd** [comment]
Try adding `-Djbd.rmi.prism.verbose=true` to the Java command line. That will print out a more detailed error about which lib fails to load. Googling the output name which help you track down which CentOS package you need. I think the dependencies are essentially libgtk2.0, libxtst6, libxslt1.1, fonts-freefont-ttf, and libasound2. Those are Ubuntu package names, not sure what the CentOS equivalent is.

**Comment by karlisSan** [comment]
Hi caokaifang,

I'm using CentOS 6.7 and installing ...

> yum install gtkhtml2 libXtst libxslt alsalib

It works. That's it!
Hope it helps!

Greetings!

**Comment by caokaifang** [comment]
Thank you very much，I  will try


发自网易邮箱大师
On 10/14/2016 15:20, karlisSan wrote:

Hi caokaifang,

I'm using CentOS 6.7 and installing ...

yum install gtkhtml2 libXtst libxslt alsalib

It works. That's it!
Hope it helps!

Greetings!
