### ISSUE TITLE
create JBrowserDrivier get blocked

### ISSUE THREAD

**Issue by Scisaga** [MachinePublishers/jBrowserDriver#199]
create JBrowserDrivier get blocked, 10 thread test run, after a while, 2 thread blocked, may be a bug?

code 

```
driver = new JBrowserDriver(
    Settings.builder()
    .timezone(Timezone.ASIA_SHANGHAI)
    .build()
);
```

exception

```
"Thread-989" #1943 prio=5 os_prio=0 tid=0x0000000020f47800 nid=0x2b98 waiting for monitor entry [0x00000000283bd000]
   java.lang.Thread.State: BLOCKED (on object monitor)
    at com.machinepublishers.jbrowserdriver.SocketFactory.createSocket(SocketFactory.java:95)
    - waiting to lock <0x00000006c0e00058> (a java.lang.Class for java.lang.Object)
    at com.machinepublishers.jbrowserdriver.SocketFactory.createSocket(SocketFactory.java:77)
    at sun.rmi.transport.tcp.TCPEndpoint.newSocket(Unknown Source)
    at sun.rmi.transport.tcp.TCPChannel.createConnection(Unknown Source)
    at sun.rmi.transport.tcp.TCPChannel.newConnection(Unknown Source)
    at sun.rmi.server.UnicastRef.newCall(Unknown Source)
    at sun.rmi.registry.RegistryImpl_Stub.lookup(Unknown Source)
    at com.machinepublishers.jbrowserdriver.JBrowserDriver.<init>(JBrowserDriver.java:326)
    - locked <0x00000007765a9898> (a com.machinepublishers.jbrowserdriver.SocketLock)
    at org.tfelab.crawler.wrapper.JBrowserDriverWrapper.<init>(JBrowserDriverWrapper.java:97)
```

**Comment by hollingsworthd** [comment]
Interesting. Thanks for submitting this. I'll consolidate this with #201 and quote your stack trace here:

`````
"RMI TCP Connection(3)-172.16.10.9" #283 daemon prio=5 os_prio=0 tid=0x0000000020982000 nid=0x3b5c runnable [0x000000002711d000]
   java.lang.Thread.State: RUNNABLE
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.socketRead(Unknown Source)
    at java.net.SocketInputStream.read(Unknown Source)
    at java.net.SocketInputStream.read(Unknown Source)
    at java.io.BufferedInputStream.fill(Unknown Source)
    at java.io.BufferedInputStream.read(Unknown Source)
    - locked <0x000000077195b9a8> (a java.io.BufferedInputStream)
    at java.io.FilterInputStream.read(Unknown Source)
    at sun.rmi.transport.tcp.TCPTransport.handleMessages(Unknown Source)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(Unknown Source)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$256(Unknown Source)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$$Lambda$1/1918409496.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

   Locked ownable synchronizers:
    - <0x000000077154cef8> (a java.util.concurrent.ThreadPoolExecutor$Worker)
````

**Comment by hollingsworthd** [comment]
I suspect that jBrowserDriver v0.17.0 fixes this. Can you try this again with the latest version?
