### ISSUE TITLE
RMI hang and blocked

### ISSUE THREAD

**Issue by Scisaga** [MachinePublishers/jBrowserDriver#201]
```
"RMI TCP Connection(3)-172.16.10.9" #283 daemon prio=5 os_prio=0 tid=0x0000000020982000 nid=0x3b5c runnable [0x000000002711d000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	- locked <0x000000077195b9a8> (a java.io.BufferedInputStream)
	at java.io.FilterInputStream.read(Unknown Source)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(Unknown Source)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(Unknown Source)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$256(Unknown Source)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$$Lambda$1/1918409496.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

   Locked ownable synchronizers:
	- <0x000000077154cef8> (a java.util.concurrent.ThreadPoolExecutor$Worker)
```

suppose add system property sun.rmi.transport.tcp.responseTimeout config to avoid RMI hang cases?

**Comment by hollingsworthd** [comment]
The browser instance hangs indefinitely? I'm assuming it's a flaky bug, but what situations tend to cause this?
