### ISSUE TITLE
Issue When Calling Quit in Selenium Using WebDriver

### ISSUE THREAD

**Issue by asevans48** [MachinePublishers/jBrowserDriver#213]
For the most part, everything runs smoothly with JBrowserDriver. However, when I call quit() the following appears.

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/thoughtworks/selenium/SeleniumException
	at com.machinepublishers.jbrowserdriver.Util.handleException(Util.java:129)
	at com.machinepublishers.jbrowserdriver.JBrowserDriver.quit(JBrowserDriver.java:1170)
	at org.aevans.goat.selenium.SeleniumBrowser.close(SeleniumBrowser.scala:1031)
```

Steps to reproduce. 

- Start JBrowserDriver without using a standalone server (not desired for this project)
- Get a few pages, click some elements
- Call browser.quit()

**Comment by Alex777UAE** [comment]
Upvoting the problem. I'm getting "Request path contains unescaped characters." exception trying to driver.quit() with selenium grid
