### ISSUE TITLE
Proxing https websites

### ISSUE THREAD

**Issue by arya6000** [MachinePublishers/jBrowserDriver#228]
I can proxy HTTP websites with no issues, but with HTTPS sites I get the following exception

```
[2016-12-15T10:27:44.253][Instance 1][Port 62071] Dec 15, 2016 5:27:44 PM com.sun.webkit.network.URLLoader doRun
[2016-12-15T10:27:44.254][Instance 1][Port 62071] WARNING: Unexpected error
[2016-12-15T10:27:44.254][Instance 1][Port 62071] java.io.IOException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target: https://somesite.com
[2016-12-15T10:27:44.254][Instance 1][Port 62071] 	at com.machinepublishers.jbrowserdriver.StreamConnection.exec(StreamConnection.java:361)
[2016-12-15T10:27:44.254][Instance 1][Port 62071] 	at com.machinepublishers.jbrowserdriver.StreamConnection.getResponseCode(StreamConnection.java:441)
[2016-12-15T10:27:44.255][Instance 1][Port 62071] 	at com.sun.webkit.network.URLLoader.receiveResponse(URLLoader.java:420)
[2016-12-15T10:27:44.255][Instance 1][Port 62071] 	at com.sun.webkit.network.URLLoader.doRun(URLLoader.java:164)
[2016-12-15T10:27:44.255][Instance 1][Port 62071] 	at com.sun.webkit.network.URLLoader.lambda$run$96(URLLoader.java:129)
[2016-12-15T10:27:44.255][Instance 1][Port 62071] 	at java.security.AccessController.doPrivileged(Native Method)
[2016-12-15T10:27:44.255][Instance 1][Port 62071] 	at com.sun.webkit.network.URLLoader.run(URLLoader.java:128)
[2016-12-15T10:27:44.255][Instance 1][Port 62071] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2016-12-15T10:27:44.255][Instance 1][Port 62071] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2016-12-15T10:27:44.256][Instance 1][Port 62071] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2016-12-15T10:27:44.256][Instance 1][Port 62071] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2016-12-15T10:27:44.256][Instance 1][Port 62071] 	at java.lang.Thread.run(Unknown Source)
[2016-12-15T10:27:44.256][Instance 1][Port 62071] Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[2016-12-15T10:27:44.256][Instance 1][Port 62071] 	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
[2016-12-15T10:27:44.256][Instance 1][Port 62071] 	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
[2016-12-15T10:27:44.256][Instance 1][Port 62071] 	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
[2016-12-15T10:27:44.257][Instance 1][Port 62071] 	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
[2016-12-15T10:27:44.257][Instance 1][Port 62071] 	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
[2016-12-15T10:27:44.257][Instance 1][Port 62071] 	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
[2016-12-15T10:27:44.257][Instance 1][Port 62071] 	at sun.security.ssl.Handshaker.processLoop(Unknown Source)
[2016-12-15T10:27:44.257][Instance 1][Port 62071] 	at sun.security.ssl.Handshaker.process_record(Unknown Source)
[2016-12-15T10:27:44.257][Instance 1][Port 62071] 	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
[2016-12-15T10:27:44.257][Instance 1][Port 62071] 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
[2016-12-15T10:27:44.257][Instance 1][Port 62071] 	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
[2016-12-15T10:27:44.257][Instance 1][Port 62071] 	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
[2016-12-15T10:27:44.257][Instance 1][Port 62071] 	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394)
[2016-12-15T10:27:44.258][Instance 1][Port 62071] 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.upgrade(DefaultHttpClientConnectionOperator.java:192)
[2016-12-15T10:27:44.258][Instance 1][Port 62071] 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.upgrade(PoolingHttpClientConnectionManager.java:369)
[2016-12-15T10:27:44.258][Instance 1][Port 62071] 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:415)
[2016-12-15T10:27:44.258][Instance 1][Port 62071] 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
[2016-12-15T10:27:44.258][Instance 1][Port 62071] 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
[2016-12-15T10:27:44.258][Instance 1][Port 62071] 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
[2016-12-15T10:27:44.258][Instance 1][Port 62071] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
[2016-12-15T10:27:44.258][Instance 1][Port 62071] 	at com.machinepublishers.jbrowserdriver.StreamConnectionClient.execute(StreamConnectionClient.java:175)
[2016-12-15T10:27:44.259][Instance 1][Port 62071] 	at com.machinepublishers.jbrowserdriver.StreamConnection.exec(StreamConnection.java:327)
[2016-12-15T10:27:44.259][Instance 1][Port 62071] 	... 11 more
[2016-12-15T10:27:44.259][Instance 1][Port 62071] Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[2016-12-15T10:27:44.259][Instance 1][Port 62071] 	at sun.security.validator.PKIXValidator.doBuild(Unknown Source)
[2016-12-15T10:27:44.259][Instance 1][Port 62071] 	at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
[2016-12-15T10:27:44.259][Instance 1][Port 62071] 	at sun.security.validator.Validator.validate(Unknown Source)
[2016-12-15T10:27:44.259][Instance 1][Port 62071] 	at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
[2016-12-15T10:27:44.259][Instance 1][Port 62071] 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
[2016-12-15T10:27:44.259][Instance 1][Port 62071] 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
[2016-12-15T10:27:44.260][Instance 1][Port 62071] 	... 29 more
[2016-12-15T10:27:44.260][Instance 1][Port 62071] Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[2016-12-15T10:27:44.260][Instance 1][Port 62071] 	at sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
[2016-12-15T10:27:44.260][Instance 1][Port 62071] 	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
[2016-12-15T10:27:44.260][Instance 1][Port 62071] 	at java.security.cert.CertPathBuilder.build(Unknown Source)
[2016-12-15T10:27:44.260][Instance 1][Port 62071] 	... 35 more
[2016-12-15T10:27:44.260][Instance 1][Port 62071] 
```

Is is there anyway to tell JBrowserDriver to ignore SSL certificate checking? I want to use proxy for many HTTPS sites.

**Comment by hollingsworthd** [comment]
One of these settings will fix it (here are all 3 ssl-related settings): `new JBrowserDriver(Settings.builder().ssl("compatible").javaOptions("-Djsse.enableSNIExtension=false").hostnameVerification(false).build())`

**Comment by arya6000** [comment]
This is what I have 

```
			ProxyConfig proxyConfig = new ProxyConfig(Type.HTTP, "127.0.0.1", 8888);
			JBrowserDriver driver = new JBrowserDriver((Settings.builder().timezone(Timezone.AMERICA_NEWYORK)
					.ssl("compatible").javaOptions("-Djsse.enableSNIExtension=false").hostnameVerification(false)
					.proxy(proxyConfig).build()));
```

But I am still getting the errors.

**Comment by Zero3** [comment]
The issue is likely that the default JRE/JDK does not include all the modern TLS cipher suites that many websites require nowadays. You can fix it by installing the "Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files" from http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html.

**Comment by sasajib** [comment]
you cant set `.ssl("compatible")` to `.ssl("trustanything")`

**Comment by zzvara** [comment]
@sasajib I have the same issue, althrough my SSL is `trustanything`.
