### ISSUE TITLE
JBrowserDriver Exception in thread

### ISSUE THREAD

**Issue by cyildirim** [MachinePublishers/jBrowserDriver#23]
When i execute code with 

```
mvn test -Djbd.browsergui=false -Djbd.quickrender=false -Djbd.traceconsole=true
```

and i take after execute code.

```
Exception in thread "Thread-3" java.lang.NullPointerException
	at com.machinepublishers.jbrowserdriver.JBrowserDriver$1.run(JBrowserDriver.java:284)
	at java.lang.Thread.run(Thread.java:745)

```
Using WebDriver Definition in my code

```
public class SeleniumUtils {
    private JBrowserDriver driver;

    public SeleniumUtils(){
        configureWebDriver();
    }
    public JBrowserDriver getDriver(){
        return this.driver;
    }
    public void configureWebDriver(){
        this.driver =new JBrowserDriver(Settings.builder().timezone(Timezone.EUROPE_ISTANBUL).build());
    }
}
```

I tried on Ubuntu and MacOS and i took same error. Did i make configuration mistake or someting?

**Comment by hollingsworthd** [comment]
Unfortunately, there's a bug in the logging code that affects logging of errors during initialization of a few parts of the lib. This will be fixed in the next release (it's in master now). v0.7.4 will be out today or tomorrow.

**Comment by hollingsworthd** [comment]
I decided to make a new release now. Can you update to 0.8.0 and let me know the stack trace?

**Comment by cyildirim** [comment]
thanks for fix.

Is there any thrust all option like ```-Djbd.pemfile``` ?
I take error this error below. I guess, there is a problem for ```https://``` url.
```
	... 11 more
Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:90)
	at sun.security.validator.Validator.getInstance(Validator.java:179)
	at sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:312)
	at sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:171)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:184)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1488)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	... 22 more
Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
	at java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)
	at java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)
	at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:88)
	... 34 more

Jan 21, 2016 9:12:21 AM com.sun.webkit.network.URLLoader doRun
WARNING: Unexpected error
java.io.IOException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty: https://imagessl.evidea.com/v2/st/cards/96x96_maximum.png
	at com.machinepublishers.jbrowserdriver.StreamConnection.exec(StreamConnection.java:447)
	at com.machinepublishers.jbrowserdriver.StreamConnection.getResponseCode(StreamConnection.java:555)
	at com.sun.webkit.network.URLLoader.receiveResponse(URLLoader.java:414)
	at com.sun.webkit.network.URLLoader.doRun(URLLoader.java:163)
	at com.sun.webkit.network.URLLoader.lambda$run$91(URLLoader.java:128)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.webkit.network.URLLoader.run(URLLoader.java:127)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1906)
	at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1889)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1410)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at com.machinepublishers.jbrowserdriver.StreamConnection.exec(StreamConnection.java:439)
	... 11 more
```

**Comment by hollingsworthd** [comment]
Yes, you can use -Djbd.pemfile=trustanything ... or instead of losing all SSL benefits, you can use -Djbd.pemfile=compatible which will trust the same certs that Firefox does. Not the best name for that parameter I know

**Comment by cyildirim** [comment]
It Works well with -Djbd.pemfile=trustanything Thanks !
