### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by coyun** [MachinePublishers/jBrowserDriver#243]
[2017-01-19T06:12:57.965][Instance 1][Port 55477] java.lang.OutOfMemoryError: Java heap space
[2017-01-19T06:12:57.966][Instance 1][Port 55477] 	at com.sun.javafx.iio.png.PNGImageLoader2.decodePalette(PNGImageLoader2.java:592)
[2017-01-19T06:12:57.966][Instance 1][Port 55477] 	at com.sun.javafx.iio.png.PNGImageLoader2.load(PNGImageLoader2.java:666)
[2017-01-19T06:12:57.966][Instance 1][Port 55477] 	at com.sun.javafx.iio.ImageStorage.loadAll(ImageStorage.java:363)
[2017-01-19T06:12:57.966][Instance 1][Port 55477] 	at com.sun.javafx.iio.ImageStorage.loadAll(ImageStorage.java:274)
[2017-01-19T06:12:57.966][Instance 1][Port 55477] 	at com.sun.javafx.webkit.prism.WCImageDecoderImpl.loadFrames(WCImageDecoderImpl.java:173)
[2017-01-19T06:12:57.966][Instance 1][Port 55477] 	at com.sun.javafx.webkit.prism.WCImageDecoderImpl.loadFrames(WCImageDecoderImpl.java:186)
[2017-01-19T06:12:57.967][Instance 1][Port 55477] 	at com.sun.javafx.webkit.prism.WCImageDecoderImpl.addImageData(WCImageDecoderImpl.java:109)
[2017-01-19T06:12:57.967][Instance 1][Port 55477] 	at com.sun.webkit.network.URLLoader.twkDidFinishLoading(Native Method)
[2017-01-19T06:12:57.967][Instance 1][Port 55477] 	at com.sun.webkit.network.URLLoader.notifyDidFinishLoading(URLLoader.java:830)
[2017-01-19T06:12:57.967][Instance 1][Port 55477] 	at com.sun.webkit.network.URLLoader.lambda$didFinishLoading$95(URLLoader.java:821)
[2017-01-19T06:12:57.967][Instance 1][Port 55477] 	at com.sun.webkit.network.URLLoader$$Lambda$153/14692923.run(Unknown Source)
[2017-01-19T06:12:57.967][Instance 1][Port 55477] 	at com.sun.javafx.application.PlatformImpl.lambda$null$170(PlatformImpl.java:295)
[2017-01-19T06:12:57.967][Instance 1][Port 55477] 	at com.sun.javafx.application.PlatformImpl$$Lambda$51/11023049.run(Unknown Source)
[2017-01-19T06:12:57.967][Instance 1][Port 55477] 	at java.security.AccessController.doPrivileged(Native Method)
[2017-01-19T06:12:57.967][Instance 1][Port 55477] 	at com.sun.javafx.application.PlatformImpl.lambda$runLater$171(PlatformImpl.java:294)
[2017-01-19T06:12:57.967][Instance 1][Port 55477] 	at com.sun.javafx.application.PlatformImpl$$Lambda$50/7902909.run(Unknown Source)
[2017-01-19T06:12:57.968][Instance 1][Port 55477] 	at com.machinepublishers.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:94)
[2017-01-19T06:12:57.968][Instance 1][Port 55477] 	at com.machinepublishers.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:53)
[2017-01-19T06:12:57.968][Instance 1][Port 55477] 	at java.lang.Thread.run(Thread.java:745)

**Comment by hollingsworthd** [comment]
Try upgrading to the latest version of Java 8 which is u121 now. If that's not possible then construct the driver using `new JBrowserDriver(Settings.builder().quickRender(true))` ... that API exists specifically to work around this bug which had been part of many older JDK versions.
