### ISSUE TITLE
Error running for a period of time

### ISSUE THREAD

**Issue by coyun** [MachinePublishers/jBrowserDriver#244]
[2017-01-19T08:08:26.057][Instance 1][Port 59069] java.lang.OutOfMemoryError: Java heap space
[2017-01-19T08:08:26.057][Instance 1][Port 59069] 	at com.sun.prism.sw.SWArgbPreTexture.allocateBuffer(SWArgbPreTexture.java:182)
[2017-01-19T08:08:26.058][Instance 1][Port 59069] 	at com.sun.prism.sw.SWTexture.allocate(SWTexture.java:268)
[2017-01-19T08:08:26.058][Instance 1][Port 59069] 	at com.sun.prism.sw.SWArgbPreTexture.update(SWArgbPreTexture.java:87)
[2017-01-19T08:08:26.058][Instance 1][Port 59069] 	at com.sun.prism.sw.SWTexture.update(SWTexture.java:215)
[2017-01-19T08:08:26.058][Instance 1][Port 59069] 	at com.sun.prism.impl.BaseResourceFactory.createTexture(BaseResourceFactory.java:236)
[2017-01-19T08:08:26.058][Instance 1][Port 59069] 	at com.sun.prism.impl.BaseResourceFactory.createTexture(BaseResourceFactory.java:221)
[2017-01-19T08:08:26.058][Instance 1][Port 59069] 	at com.sun.javafx.webkit.prism.WCImageImpl.draw(WCImageImpl.java:114)
[2017-01-19T08:08:26.058][Instance 1][Port 59069] 	at com.sun.javafx.webkit.prism.WCGraphicsPrismContext$7.doPaint(WCGraphicsPrismContext.java:782)
[2017-01-19T08:08:26.058][Instance 1][Port 59069] 	at com.sun.javafx.webkit.prism.WCGraphicsPrismContext$Composite.paint(WCGraphicsPrismContext.java:1395)
[2017-01-19T08:08:26.058][Instance 1][Port 59069] 	at com.sun.javafx.webkit.prism.WCGraphicsPrismContext$Composite.paint(WCGraphicsPrismContext.java:1380)
[2017-01-19T08:08:26.058][Instance 1][Port 59069] 	at com.sun.javafx.webkit.prism.WCGraphicsPrismContext.drawImage(WCGraphicsPrismContext.java:789)
[2017-01-19T08:08:26.058][Instance 1][Port 59069] 	at com.sun.webkit.graphics.GraphicsDecoder.drawImage(GraphicsDecoder.java:430)
[2017-01-19T08:08:26.058][Instance 1][Port 59069] 	at com.sun.webkit.graphics.GraphicsDecoder.decode(GraphicsDecoder.java:188)
[2017-01-19T08:08:26.058][Instance 1][Port 59069] 	at com.sun.webkit.graphics.WCRenderQueue.decode(WCRenderQueue.java:91)
[2017-01-19T08:08:26.058][Instance 1][Port 59069] 	at com.sun.webkit.WebPage.paint2GC(WebPage.java:686)
[2017-01-19T08:08:26.058][Instance 1][Port 59069] 	at com.sun.webkit.WebPage.paint(WebPage.java:653)
[2017-01-19T08:08:26.058][Instance 1][Port 59069] 	at com.sun.javafx.sg.prism.NGWebView.renderContent(NGWebView.java:95)
[2017-01-19T08:08:26.058][Instance 1][Port 59069] 	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2067)
[2017-01-19T08:08:26.059][Instance 1][Port 59069] 	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1959)
[2017-01-19T08:08:26.059][Instance 1][Port 59069] 	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
[2017-01-19T08:08:26.059][Instance 1][Port 59069] 	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:576)
[2017-01-19T08:08:26.059][Instance 1][Port 59069] 	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2067)
[2017-01-19T08:08:26.060][Instance 1][Port 59069] 	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1959)
[2017-01-19T08:08:26.060][Instance 1][Port 59069] 	at com.sun.javafx.tk.quantum.ViewPainter.doPaint(ViewPainter.java:474)
[2017-01-19T08:08:26.060][Instance 1][Port 59069] 	at com.sun.javafx.tk.quantum.ViewPainter.paintImpl(ViewPainter.java:327)
[2017-01-19T08:08:26.060][Instance 1][Port 59069] 	at com.sun.javafx.tk.quantum.UploadingPainter.run(UploadingPainter.java:133)
[2017-01-19T08:08:26.060][Instance 1][Port 59069] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[2017-01-19T08:08:26.060][Instance 1][Port 59069] 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
[2017-01-19T08:08:26.067][Instance 1][Port 59069] 	at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
[2017-01-19T08:08:26.068][Instance 1][Port 59069] 	at com.sun.javafx.tk.quantum.QuantumToolkit.addRenderJob(QuantumToolkit.java:464)
[2017-01-19T08:08:26.068][Instance 1][Port 59069] 	at com.sun.javafx.tk.quantum.ViewScene.repaint(ViewScene.java:140)
[2017-01-19T08:08:26.068][Instance 1][Port 59069] 	at com.sun.javafx.tk.quantum.PaintCollector.renderAll(PaintCollector.java:407)
[2017-01-19T08:08:26.148][Instance 1][Port 59069] java.lang.OutOfMemoryError: Java heap space
[2017-01-19T08:08:26.148][Instance 1][Port 59069] 	at com.sun.prism.sw.SWArgbPreTexture.allocateBuffer(SWArgbPreTexture.java:182)
[2017-01-19T08:08:26.148][Instance 1][Port 59069] 	at com.sun.prism.sw.SWTexture.allocate(SWTexture.java:268)
[2017-01-19T08:08:26.149][Instance 1][Port 59069] 	at com.sun.prism.sw.SWArgbPreTexture.update(SWArgbPreTexture.java:87)
[2017-01-19T08:08:26.149][Instance 1][Port 59069] 	at com.sun.prism.sw.SWTexture.update(SWTexture.java:215)
[2017-01-19T08:08:26.149][Instance 1][Port 59069] 	at com.sun.prism.impl.BaseResourceFactory.createTexture(BaseResourceFactory.java:236)
[2017-01-19T08:08:26.149][Instance 1][Port 59069] 	at com.sun.prism.impl.BaseResourceFactory.createTexture(BaseResourceFactory.java:221)
[2017-01-19T08:08:26.149][Instance 1][Port 59069] 	at com.sun.javafx.webkit.prism.WCImageImpl.draw(WCImageImpl.java:114)
[2017-01-19T08:08:26.149][Instance 1][Port 59069] 	at com.sun.javafx.webkit.prism.WCGraphicsPrismContext$7.doPaint(WCGraphicsPrismContext.java:782)
[2017-01-19T08:08:26.149][Instance 1][Port 59069] 	at com.sun.javafx.webkit.prism.WCGraphicsPrismContext$Composite.paint(WCGraphicsPrismContext.java:1395)
[2017-01-19T08:08:26.149][Instance 1][Port 59069] 	at com.sun.javafx.webkit.prism.WCGraphicsPrismContext$Composite.paint(WCGraphicsPrismContext.java:1380)
[2017-01-19T08:08:26.149][Instance 1][Port 59069] 	at com.sun.javafx.webkit.prism.WCGraphicsPrismContext.drawImage(WCGraphicsPrismContext.java:789)
[2017-01-19T08:08:26.149][Instance 1][Port 59069] 	at com.sun.webkit.graphics.GraphicsDecoder.drawImage(GraphicsDecoder.java:430)
[2017-01-19T08:08:26.149][Instance 1][Port 59069] 	at com.sun.webkit.graphics.GraphicsDecoder.decode(GraphicsDecoder.java:188)
[2017-01-19T08:08:26.149][Instance 1][Port 59069] 	at com.sun.webkit.graphics.WCRenderQueue.decode(WCRenderQueue.java:91)
[2017-01-19T08:08:26.149][Instance 1][Port 59069] 	at com.sun.webkit.WebPage.paint2GC(WebPage.java:686)
[2017-01-19T08:08:26.149][Instance 1][Port 59069] 	at com.sun.webkit.WebPage.paint(WebPage.java:653)
[2017-01-19T08:08:26.149][Instance 1][Port 59069] 	at com.sun.javafx.sg.prism.NGWebView.renderContent(NGWebView.java:95)
[2017-01-19T08:08:26.149][Instance 1][Port 59069] 	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2067)
[2017-01-19T08:08:26.150][Instance 1][Port 59069] 	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1959)
[2017-01-19T08:08:26.150][Instance 1][Port 59069] 	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
[2017-01-19T08:08:26.150][Instance 1][Port 59069] 	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:576)
[2017-01-19T08:08:26.150][Instance 1][Port 59069] 	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2067)
[2017-01-19T08:08:26.150][Instance 1][Port 59069] 	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1959)
[2017-01-19T08:08:26.150][Instance 1][Port 59069] 	at com.sun.javafx.tk.quantum.ViewPainter.doPaint(ViewPainter.java:474)
[2017-01-19T08:08:26.150][Instance 1][Port 59069] 	at com.sun.javafx.tk.quantum.ViewPainter.paintImpl(ViewPainter.java:327)
[2017-01-19T08:08:26.150][Instance 1][Port 59069] 	at com.sun.javafx.tk.quantum.UploadingPainter.run(UploadingPainter.java:133)
[2017-01-19T08:08:26.150][Instance 1][Port 59069] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[2017-01-19T08:08:26.150][Instance 1][Port 59069] 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
[2017-01-19T08:08:26.150][Instance 1][Port 59069] 	at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
[2017-01-19T08:08:26.150][Instance 1][Port 59069] 	at com.sun.javafx.tk.quantum.QuantumToolkit.addRenderJob(QuantumToolkit.java:464)
[2017-01-19T08:08:26.150][Instance 1][Port 59069] 	at com.sun.javafx.tk.quantum.ViewScene.repaint(ViewScene.java:140)
[2017-01-19T08:08:26.150][Instance 1][Port 59069] 	at com.sun.javafx.tk.quantum.PaintCollector.renderAll(PaintCollector.java:407)
[2017-01-19T08:08:26.239][Instance 1][Port 59069] java.lang.OutOfMemoryError: Java heap space
[2017-01-19T08:08:26.239][Instance 1][Port 59069] 	at com.sun.prism.sw.SWArgbPreTexture.allocateBuffer(SWArgbPreTexture.java:182)
[2017-01-19T08:08:26.258][Instance 1][Port 59069] 	at com.sun.prism.sw.SWTexture.allocate(SWTexture.java:268)
[2017-01-19T08:08:26.259][Instance 1][Port 59069] 	at com.sun.prism.sw.SWArgbPreTexture.update(SWArgbPreTexture.java:87)
[2017-01-19T08:08:26.259][Instance 1][Port 59069] 	at com.sun.prism.sw.SWTexture.update(SWTexture.java:215)
[2017-01-19T08:08:26.259][Instance 1][Port 59069] 	at com.sun.prism.impl.BaseResourceFactory.createTexture(BaseResourceFactory.java:236)
[2017-01-19T08:08:26.259][Instance 1][Port 59069] 	at com.sun.prism.impl.BaseResourceFactory.createTexture(BaseResourceFactory.java:221)
[2017-01-19T08:08:26.259][Instance 1][Port 59069] 	at com.sun.javafx.webkit.prism.WCImageImpl.draw(WCImageImpl.java:114)
[2017-01-19T08:08:26.259][Instance 1][Port 59069] 	at com.sun.javafx.webkit.prism.WCGraphicsPrismContext$7.doPaint(WCGraphicsPrismContext.java:782)
[2017-01-19T08:08:26.259][Instance 1][Port 59069] 	at com.sun.javafx.webkit.prism.WCGraphicsPrismContext$Composite.paint(WCGraphicsPrismContext.java:1395)
[2017-01-19T08:08:26.260][Instance 1][Port 59069] 	at com.sun.javafx.webkit.prism.WCGraphicsPrismContext$Composite.paint(WCGraphicsPrismContext.java:1380)
[2017-01-19T08:08:26.260][Instance 1][Port 59069] 	at com.sun.javafx.webkit.prism.WCGraphicsPrismContext.drawImage(WCGraphicsPrismContext.java:789)
[2017-01-19T08:08:26.260][Instance 1][Port 59069] 	at com.sun.webkit.graphics.GraphicsDecoder.drawImage(GraphicsDecoder.java:430)
[2017-01-19T08:08:26.260][Instance 1][Port 59069] 	at com.sun.webkit.graphics.GraphicsDecoder.decode(GraphicsDecoder.java:188)
[2017-01-19T08:08:26.260][Instance 1][Port 59069] 	at com.sun.webkit.graphics.WCRenderQueue.decode(WCRenderQueue.java:91)
[2017-01-19T08:08:26.260][Instance 1][Port 59069] 	at com.sun.webkit.WebPage.paint2GC(WebPage.java:686)
[2017-01-19T08:08:26.260][Instance 1][Port 59069] 	at com.sun.webkit.WebPage.paint(WebPage.java:653)
[2017-01-19T08:08:26.260][Instance 1][Port 59069] 	at com.sun.javafx.sg.prism.NGWebView.renderContent(NGWebView.java:95)
[2017-01-19T08:08:26.260][Instance 1][Port 59069] 	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2067)
[2017-01-19T08:08:26.260][Instance 1][Port 59069] 	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1959)
[2017-01-19T08:08:26.260][Instance 1][Port 59069] 	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
[2017-01-19T08:08:26.260][Instance 1][Port 59069] 	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:576)
[2017-01-19T08:08:26.260][Instance 1][Port 59069] 	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2067)
[2017-01-19T08:08:26.261][Instance 1][Port 59069] 	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1959)
[2017-01-19T08:08:26.261][Instance 1][Port 59069] 	at com.sun.javafx.tk.quantum.ViewPainter.doPaint(ViewPainter.java:474)
[2017-01-19T08:08:26.261][Instance 1][Port 59069] 	at com.sun.javafx.tk.quantum.ViewPainter.paintImpl(ViewPainter.java:327)
[2017-01-19T08:08:26.261][Instance 1][Port 59069] 	at com.sun.javafx.tk.quantum.UploadingPainter.run(UploadingPainter.java:133)
[2017-01-19T08:08:26.261][Instance 1][Port 59069] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[2017-01-19T08:08:26.261][Instance 1][Port 59069] 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
[2017-01-19T08:08:26.261][Instance 1][Port 59069] 	at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
[2017-01-19T08:08:26.261][Instance 1][Port 59069] 	at com.sun.javafx.tk.quantum.QuantumToolkit.addRenderJob(QuantumToolkit.java:464)
[2017-01-19T08:08:26.261][Instance 1][Port 59069] 	at com.sun.javafx.tk.quantum.ViewScene.repaint(ViewScene.java:140)
[2017-01-19T08:08:26.261][Instance 1][Port 59069] 	at com.sun.javafx.tk.quantum.PaintCollector.renderAll(PaintCollector.java:407)
[2017-01-19T08:08:26.336][Instance 1][Port 59069] java.lang.OutOfMemoryError: Java heap space
[2017-01-19T08:08:26.336][Instance 1][Port 59069] 	at com.sun.prism.sw.SWArgbPreTexture.allocateBuffer(SWArgbPreTexture.java:182)
[2017-01-19T08:08:26.336][Instance 1][Port 59069] 	at com.sun.prism.sw.SWTexture.allocate(SWTexture.java:268)
[2017-01-19T08:08:26.336][Instance 1][Port 59069] 	at com.sun.prism.sw.SWArgbPreTexture.update(SWArgbPreTexture.java:87)
[2017-01-19T08:08:26.336][Instance 1][Port 59069] 	at com.sun.prism.sw.SWTexture.update(SWTexture.java:215)
[2017-01-19T08:08:26.336][Instance 1][Port 59069] 	at com.sun.prism.impl.BaseResourceFactory.createTexture(BaseResourceFactory.java:236)
[2017-01-19T08:08:26.336][Instance 1][Port 59069] 	at com.sun.prism.impl.BaseResourceFactory.createTexture(BaseResourceFactory.java:221)
[2017-01-19T08:08:26.336][Instance 1][Port 59069] 	at com.sun.javafx.webkit.prism.WCImageImpl.draw(WCImageImpl.java:114)
[2017-01-19T08:08:26.337][Instance 1][Port 59069] 	at com.sun.javafx.webkit.prism.WCGraphicsPrismContext$7.doPaint(WCGraphicsPrismContext.java:782)
[2017-01-19T08:08:26.337][Instance 1][Port 59069] 	at com.sun.javafx.webkit.prism.WCGraphicsPrismContext$Composite.paint(WCGraphicsPrismContext.java:1395)
[2017-01-19T08:08:26.337][Instance 1][Port 59069] 	at com.sun.javafx.webkit.prism.WCGraphicsPrismContext$Composite.paint(WCGraphicsPrismContext.java:1380)
[2017-01-19T08:08:26.337][Instance 1][Port 59069] 	at com.sun.javafx.webkit.prism.WCGraphicsPrismContext.drawImage(WCGraphicsPrismContext.java:789)
[2017-01-19T08:08:26.337][Instance 1][Port 59069] 	at com.sun.webkit.graphics.GraphicsDecoder.drawImage(GraphicsDecoder.java:430)
[2017-01-19T08:08:26.337][Instance 1][Port 59069] 	at com.sun.webkit.graphics.GraphicsDecoder.decode(GraphicsDecoder.java:188)
[2017-01-19T08:08:26.337][Instance 1][Port 59069] 	at com.sun.webkit.graphics.WCRenderQueue.decode(WCRenderQueue.java:91)
[2017-01-19T08:08:26.337][Instance 1][Port 59069] 	at com.sun.webkit.WebPage.paint2GC(WebPage.java:686)
[2017-01-19T08:08:26.337][Instance 1][Port 59069] 	at com.sun.webkit.WebPage.paint(WebPage.java:653)
[2017-01-19T08:08:26.337][Instance 1][Port 59069] 	at com.sun.javafx.sg.prism.NGWebView.renderContent(NGWebView.java:95)
[2017-01-19T08:08:26.337][Instance 1][Port 59069] 	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2067)
[2017-01-19T08:08:26.337][Instance 1][Port 59069] 	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1959)
[2017-01-19T08:08:26.337][Instance 1][Port 59069] 	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
[2017-01-19T08:08:26.337][Instance 1][Port 59069] 	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:576)
[2017-01-19T08:08:26.338][Instance 1][Port 59069] 	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2067)
[2017-01-19T08:08:26.338][Instance 1][Port 59069] 	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1959)
[2017-01-19T08:08:26.338][Instance 1][Port 59069] 	at com.sun.javafx.tk.quantum.ViewPainter.doPaint(ViewPainter.java:474)
[2017-01-19T08:08:26.338][Instance 1][Port 59069] 	at com.sun.javafx.tk.quantum.ViewPainter.paintImpl(ViewPainter.java:327)
[2017-01-19T08:08:26.338][Instance 1][Port 59069] 	at com.sun.javafx.tk.quantum.UploadingPainter.run(UploadingPainter.java:133)
[2017-01-19T08:08:26.338][Instance 1][Port 59069] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[2017-01-19T08:08:26.338][Instance 1][Port 59069] 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
[2017-01-19T08:08:26.338][Instance 1][Port 59069] 	at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
[2017-01-19T08:08:26.338][Instance 1][Port 59069] 	at com.sun.javafx.tk.quantum.QuantumToolkit.addRenderJob(QuantumToolkit.java:464)
[2017-01-19T08:08:26.338][Instance 1][Port 59069] 	at com.sun.javafx.tk.quantum.ViewScene.repaint(ViewScene.java:140)
[2017-01-19T08:08:26.338][Instance 1][Port 59069] 	at com.sun.javafx.tk.quantum.PaintCollector.renderAll(PaintCollector.java:407)
[2017-01-19T08:08:26.440][Instance 1][Port 59069] java.lang.OutOfMemoryError: Java heap space
[2017-01-19T08:08:26.562][Instance 1][Port 59069] java.lang.OutOfMemoryError: Java heap space
[2017-01-19T08:08:26.628][Instance 1][Port 59069] java.lang.OutOfMemoryError: Java heap space
[2017-01-19T08:08:26.690][Instance 1][Port 59069] java.lang.OutOfMemoryError: Java heap space
[2017-01-19T08:08:26.758][Instance 1][Port 59069] java.lang.OutOfMemoryError: Java heap space
[2017-01-19T08:08:26.841][Instance 1][Port 59069] java.lang.OutOfMemoryError: Java heap space

[2017-01-19T08:08:56.474][Instance 1][Port 59069] java.lang.OutOfMemoryError: Java heap space
[2017-01-19T08:08:58.205][Instance 1][Port 59069] java.lang.OutOfMemoryError: Java heap space
[2017-01-19T08:08:59.022][Instance 1][Port 59069] java.lang.OutOfMemoryError: Java heap space

[2017-01-19T08:09:29.493][Instance 1][Port 59069] java.lang.OutOfMemoryError: Java heap space
[2017-01-19T08:09:29.643][Instance 1][Port 59069] java.lang.OutOfMemoryError: Java heap space
[2017-01-19T08:09:29.704][Instance 1][Port 59069] java.lang.OutOfMemoryError: Java heap space
[2017-01-19T08:09:29.827][Instance 1][Port 59069] java.lang.OutOfMemoryError: Java heap space
[2017-01-19T08:09:29.887][Instance 1][Port 59069] java.lang.OutOfMemoryError: Java heap space
[2017-01-19T08:09:30.051][Instance 1][Port 59069] java.lang.OutOfMemoryError: Java heap space
[2017-01-19T08:09:30.284][Instance 1][Port 59069] java.lang.OutOfMemoryError: Java heap space
[2017-01-19T08:09:30.417][Instance 1][Port 59069] java.lang.OutOfMemoryError: Java heap space
[2017-01-19T08:09:30.476][Instance 1][Port 59069] java.lang.OutOfMemoryError: Java heap space
[2017-01-19T08:09:30.790][Instance 1][Port 59069] java.lang.OutOfMemoryError: Java heap space
[2017-01-19T08:09:31.569][Instance 1][Port 59069] java.lang.OutOfMemoryError: Java heap space
[2017-01-19T08:09:31.678][Instance 1][Port 59069] #
[2017-01-19T08:09:31.702][Instance 1][Port 59069] # A fatal error has been detected by the Java Runtime Environment:
[2017-01-19T08:09:31.703][Instance 1][Port 59069] #
[2017-01-19T08:09:31.703][Instance 1][Port 59069] #  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x621a963a, pid=9264, tid=7784
[2017-01-19T08:09:31.703][Instance 1][Port 59069] #
[2017-01-19T08:09:31.703][Instance 1][Port 59069] # JRE version: Java(TM) SE Runtime Environment (8.0_40-b23) (build 1.8.0_40-ea-b23)
[2017-01-19T08:09:31.703][Instance 1][Port 59069] # Java VM: Java HotSpot(TM) Client VM (25.40-b25 mixed mode windows-x86 )
[2017-01-19T08:09:31.703][Instance 1][Port 59069] # Problematic frame:
[2017-01-19T08:09:31.808][Instance 1][Port 59069] # C  [jfxwebkit.dll+0xa8963a]
[2017-01-19T08:09:31.809][Instance 1][Port 59069] #
[2017-01-19T08:09:31.809][Instance 1][Port 59069] # Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
[2017-01-19T08:09:31.809][Instance 1][Port 59069] #
[2017-01-19T08:09:31.855][Instance 1][Port 59069] # An error report file with more information is saved as:
[2017-01-19T08:09:31.855][Instance 1][Port 59069] # D:\items\iampayed\hs_err_pid9264.log
[2017-01-19T08:09:31.899][Instance 1][Port 59069] #
[2017-01-19T08:09:31.899][Instance 1][Port 59069] # If you would like to submit a bug report, please visit:
[2017-01-19T08:09:31.899][Instance 1][Port 59069] #   http://bugreport.java.com/bugreport/crash.jsp
[2017-01-19T08:09:31.899][Instance 1][Port 59069] # The crash happened outside the Java Virtual Machine in native code.
[2017-01-19T08:09:31.899][Instance 1][Port 59069] # See problematic frame for where to report the bug.
[2017-01-19T08:09:31.899][Instance 1][Port 59069] #

**Comment by hollingsworthd** [comment]
I suspect the cause of this is the same as mentioned in #243. Let me know if the suggestion there gets you past these issues. Thanks.
