### ISSUE TITLE
CreateProcess error=206, The filename or extension is too long 

### ISSUE THREAD

**Issue by hbrackmann** [MachinePublishers/jBrowserDriver#25]
good idea for a framework. i currently use phantomjs but its is slow and buggy this looks like a better solution.

executing a test i get:

java.io.IOException: Cannot run program "C:\Program Files\Java\jdk1.8.0_60\jre\bin\java.exe": CreateProcess error=206, Der Dateiname oder die Erweiterung ist zu lang
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at org.zeroturnaround.exec.ProcessExecutor.invokeStart(ProcessExecutor.java:931)
	at org.zeroturnaround.exec.ProcessExecutor.startInternal(ProcessExecutor.java:910)
	at org.zeroturnaround.exec.ProcessExecutor.execute(ProcessExecutor.java:860)
	at com.machinepublishers.jbrowserdriver.JBrowserDriver$1.run(JBrowserDriver.java:282)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: CreateProcess error=206, Der Dateiname oder die Erweiterung ist zu lang
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)

I dont want to start another process anyway. Is there a way to disable it?

**Comment by hollingsworthd** [comment]
This bug is that the command line arg is too long. I will fix this.

I do plan to add an option to not start a second process. But it will be limited to running a single browser instance at a time. It's intended for people who prefer to manage the processes themselves. There are no plans to support multi-tasking multiple browsers (it used to work that way and was not a good solution because the occasional native browser crash takes down your whole JVM).

Thanks for the bug report.

**Comment by Howardbrooks1** [comment]
Use "Long path tool" to solve the error like deleting, renaming, copying etc.......Try " Long Path Tool " is also useful in situations where you see these error messages:

**Comment by fostersanders** [comment]
Well, I had the same problem. 
But then I searched on the internet for a solution and I ran into 

L 
o 
n 
g 


P 
a 
t 
h 

T 
o 
o 
l. 

It´s really effective and you can solve your problem in less than 2 minutes

**Comment by Mar11b** [comment]
Hi, could I ask how this Long Path Tool works in order to fix this issue?
Thanks.

**Comment by hbrackmann** [comment]
It's just spam for malware. The "tool" is useless.

**Comment by hollingsworthd** [comment]
Thanks for the heads up, @hbrackmann ... will remove these comments when I see them.

**Comment by hollingsworthd** [comment]
Also for the record the comments removed weren't necessarily hyping the tool that shall not be named. People were asking questions about it. If this bug is really still an issue please open a new issue.
