### ISSUE TITLE
Cookie format

### ISSUE THREAD

**Issue by JeffBolle** [MachinePublishers/jBrowserDriver#266]
I've noticed some minor differences in how the cookies are being sent in the HTTP headers between jBrowserDriver and Chrome (as an example).

This is reproducable for me when I set one of the cookie values in jBrowserDriver via driver.manage().addCookie(...)

Sent by Chrome (and also jBrowser if not set manually):
Cookie: field=ae508a45e0c46fe3154db6e8f2a18ad1a51e58ff\r\n
    Cookie pair: field=ae508a45e0c46fe3154db6e8f2a18ad1a51e58ff

When I set the Cookie in jBrowserDriver and reload the page:
Cookie: $Version=1; field="6ed8249a27953cb30d0e760c908886fe309ee9a1"\r\n
    Cookie pair: $Version=1
    Cookie pair: field="6ed8249a27953cb30d0e760c908886fe309ee9a1"

You can see that the $Version cookie is added, and the value is now quoted.
The quoting of the value breaks Cookie handling on the server side.  I can replicate when I send the quoted version of the value through Chrome as well.

This appears to be related to the way Cookies are handled in Apache's HTTP client.  For some, calling Cookie.setVersion(0) resolved the issue (when using BasicClientCookie2).  

Selenium's Cookies don't appear to have a provision for setting a version. Could this option be exposed during configuration?

**Comment by JeffBolle** [comment]
Having dug in some, the offending line (for me) is in OptionsServer.java,  private org.apache.http.cookie.Cookie convert(Cookie in) 
`private org.apache.http.cookie.Cookie convert(Cookie in) {`
`<snip>`
`    out.setVersion(0); //changed to 0 from 1.`
`}`

Clearly this is making up for the larger problem that Selenium's cookie reimplementation doesn't take versioning into account.  

Does this need to be hardcoded?  Can the CookieSpec implementations not figure out when cookies need to be sent as Version 0 or Version 1?

**Comment by hollingsworthd** [comment]
Thanks for the context here. I think the easiest thing to do is probably remove the line in question so that it defaults to 0. For people who want something else, they should probably set it on the UserAgent object that can be specified on the Settings. It seems there's some additional bug that setting it to version 1 results in the extra cookie being added.

How's that sound?

**Comment by hollingsworthd** [comment]
> Does this need to be hardcoded? Can the CookieSpec implementations not figure out when cookies need to be sent as Version 0 or Version 1?

Not sure on this. We do set the HttpComponents cookie handling policy to a custom one defined in the project by the class LaxCookieSpecProvider. I figured that was mostly responsible for how cookies are parsed but it might also be affecting how cookies get sent too. Apache does allow for cookies to be explicitly set too rather than rely on these manager/spec classes.

**Comment by JeffBolle** [comment]
As a test I changed to the default cookie spec providers and had no
substantive change in my one test case. Changing the version solved my
issue. I don't know what the more wideranging side effects of changing that
will be. I think a check to see if a cookie value contains whitespace and
then setting it to version 1 might help some future compatibility issues.

On Mar 22, 2017 11:17 PM, "D. Hollingsworth" <notifications@github.com>
wrote:

Does this need to be hardcoded? Can the CookieSpec implementations not
figure out when cookies need to be sent as Version 0 or Version 1?

Not sure on this. We do set the HttpComponents cookie handling policy to a
custom one defined in the project by the class LaxCookieSpecProvider. I
figured that was mostly responsible for how cookies are parsed but it might
also be affecting how cookies get sent too. Apache does allow for cookies
to be explicitly set too rather than rely on these manager/spec classes.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/MachinePublishers/jBrowserDriver/issues/266#issuecomment-288606025>,
or mute the thread

**Comment by JeffBolle** [comment]
I reverted my changes to the CookieSpec provider, and simply commented out the line to set the version. My single test passed just fine now, but I don't have a good test case that requires Version 1 cookies to successfully complete.

**Comment by jackrusher** [comment]
Possibly related, I get an exception like this every time I start JBD:
```
[2017-04-20T13:45:25.693] java.lang.ExceptionInInitializerError
[2017-04-20T13:45:25.693] 	at com.machinepublishers.jbrowserdriver.JBrowserDriverServer.main(JBrowserDriverServer.java:81)
[2017-04-20T13:45:25.703] Caused by: org.openqa.selenium.WebDriverException: org.apache.http.impl.cookie.RFC2965Spec.<init>(boolean, [Lorg.apache.http.cookie.CommonCookieAttributeHandler;)
[2017-04-20T13:45:25.703] Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
[2017-04-20T13:45:25.703] System info: host: 'calvino.fritz.box', ip: '192.168.178.54', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.3', java.version: '1.8.0_45'
[2017-04-20T13:45:25.703] Driver info: driver.version: unknown
[2017-04-20T13:45:25.704] 	at com.machinepublishers.jbrowserdriver.Util.handleException(Util.java:139)
[2017-04-20T13:45:25.704] 	at com.machinepublishers.jbrowserdriver.LaxCookieSpecProvider.create(LaxCookieSpecProvider.java:170)
[2017-04-20T13:45:25.704] 	at com.machinepublishers.jbrowserdriver.CookieStore.<clinit>(CookieStore.java:42)
[2017-04-20T13:45:25.704] 	... 1 more
[2017-04-20T13:45:25.704] Caused by: java.lang.NoSuchMethodException: org.apache.http.impl.cookie.RFC2965Spec.<init>(boolean, [Lorg.apache.http.cookie.CommonCookieAttributeHandler;)
[2017-04-20T13:45:25.704] 	at java.lang.Class.getConstructor0(Class.java:3082)
[2017-04-20T13:45:25.704] 	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
[2017-04-20T13:45:25.704] 	at com.machinepublishers.jbrowserdriver.LaxCookieSpecProvider.create(LaxCookieSpecProvider.java:95)
```
... although things run more or less normally thereafter. Any ideas?

**Comment by JeffBolle** [comment]
Thats interesting. I'm also running on OS X and have never seen that
exception.

Jeff Bolle

*SVP Technology*
*Q6 Cyber*
*(e)* jbolle@q6cyber.com
*(o)* 954-361-3535
*(c) *757-301-1775 <617%20519%209288>

**Comment by plexus** [comment]
I'm seeing the same error @jackrusher reported, this time on Linux.

```
[2017-08-12T15:47:48.235] java.lang.ExceptionInInitializerError
[2017-08-12T15:47:48.241] 	at com.machinepublishers.jbrowserdriver.JBrowserDriverServer.main(JBrowserDriverServer.java:81)
[2017-08-12T15:47:48.244] Caused by: org.openqa.selenium.WebDriverException: org.apache.http.impl.cookie.RFC2965Spec.<init>(boolean, [Lorg.apache.http.cookie.CommonCookieAttributeHandler;)
[2017-08-12T15:47:48.245] Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
[2017-08-12T15:47:48.246] System info: host: 'bmo', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.10.1-041001-generic', java.version: '1.8.0_91'
[2017-08-12T15:47:48.247] Driver info: driver.version: unknown
[2017-08-12T15:47:48.248] 	at com.machinepublishers.jbrowserdriver.Util.handleException(Util.java:139)
[2017-08-12T15:47:48.248] 	at com.machinepublishers.jbrowserdriver.LaxCookieSpecProvider.create(LaxCookieSpecProvider.java:170)
[2017-08-12T15:47:48.250] 	at com.machinepublishers.jbrowserdriver.CookieStore.<clinit>(CookieStore.java:42)
[2017-08-12T15:47:48.251] 	... 1 more
[2017-08-12T15:47:48.251] Caused by: java.lang.NoSuchMethodException: org.apache.http.impl.cookie.RFC2965Spec.<init>(boolean, [Lorg.apache.http.cookie.CommonCookieAttributeHandler;)
[2017-08-12T15:47:48.252] 	at java.lang.Class.getConstructor0(Class.java:3082)
[2017-08-12T15:47:48.252] 	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
[2017-08-12T15:47:48.252] 	at com.machinepublishers.jbrowserdriver.LaxCookieSpecProvider.create(LaxCookieSpecProvider.java:95)
[2017-08-12T15:47:48.253] 	... 2 more
```

**Comment by jarcane** [comment]
I'm encountering the same issue on Windows, using @jackrusher's Sparkledriver in Clojure:

```
[2018-05-23T09:10:13.914] java.lang.ExceptionInInitializerError
[2018-05-23T09:10:13.915]       at com.machinepublishers.jbrowserdriver.JBrowserDriverServer.main(JBrowserDriverServer.java:80)

[2018-05-23T09:10:13.928] Caused by: org.openqa.selenium.WebDriverException: org.apache.http.impl.cookie.RFC2965Spec.<init>(boolean, [Lorg.apache.http.cookie.CommonCookieAttributeHandler;)
[2018-05-23T09:10:13.929] Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
[2018-05-23T09:10:13.930] System info: host: 'FL204', ip: '10.6.2.133', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_171'
[2018-05-23T09:10:13.931] Driver info: driver.version: unknown
[2018-05-23T09:10:13.932]       at com.machinepublishers.jbrowserdriver.Util.handleException(Util.java:139)
[2018-05-23T09:10:13.932]       at com.machinepublishers.jbrowserdriver.LaxCookieSpecProvider.create(LaxCookieSpecProvider.java:170)
[2018-05-23T09:10:13.934]       at com.machinepublishers.jbrowserdriver.CookieStore.<clinit>(CookieStore.java:42)
[2018-05-23T09:10:13.934]       ... 1 more
[2018-05-23T09:10:13.935] Caused by: java.lang.NoSuchMethodException: org.apache.http.impl.cookie.RFC2965Spec.<init>(boolean, [Lorg.apache.http.cookie.CommonCookieAttributeHandler;)
[2018-05-23T09:10:13.935]       at java.lang.Class.getConstructor0(Unknown Source)
[2018-05-23T09:10:13.936]       at java.lang.Class.getDeclaredConstructor(Unknown Source)
[2018-05-23T09:10:13.936]       at com.machinepublishers.jbrowserdriver.LaxCookieSpecProvider.create(LaxCookieSpecProvider.java:95)
[2018-05-23T09:10:13.937]       ... 2 more
```

As mentioned, it still runs, the tests even pass, I just get this error after creating the browser object.
