### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by cyildirim** [MachinePublishers/jBrowserDriver#27]
Hello,

when i execute my code like this 

```
foreach(Urls:url){
  driver.get(url)
}
```
I get OutOfMemoryError after ~200 iteration;

```
Exception in thread "JavaFX Application Thread" java.lang.OutOfMemoryError: Java heap space
	at com.sun.javafx.iio.png.PNGImageLoader2.decodePalette(PNGImageLoader2.java:588)
	at com.sun.javafx.iio.png.PNGImageLoader2.load(PNGImageLoader2.java:669)
	at com.sun.javafx.iio.ImageStorage.loadAll(ImageStorage.java:364)
	at com.sun.javafx.iio.ImageStorage.loadAll(ImageStorage.java:274)
	at com.sun.javafx.webkit.prism.WCImageDecoderImpl.loadFrames(WCImageDecoderImpl.java:173)
	at com.sun.javafx.webkit.prism.WCImageDecoderImpl.loadFrames(WCImageDecoderImpl.java:186)
	at com.sun.javafx.webkit.prism.WCImageDecoderImpl.addImageData(WCImageDecoderImpl.java:109)
	at com.sun.webkit.network.URLLoader.twkDidFinishLoading(Native Method)
	at com.sun.webkit.network.URLLoader.notifyDidFinishLoading(URLLoader.java:838)
	at com.sun.webkit.network.URLLoader.lambda$didFinishLoading$96(URLLoader.java:829)
	at com.sun.webkit.network.URLLoader$$Lambda$157/718162111.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$null$174(PlatformImpl.java:295)
	at com.sun.javafx.application.PlatformImpl$$Lambda$52/1933809392.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$175(PlatformImpl.java:294)
	at com.sun.javafx.application.PlatformImpl$$Lambda$51/315822528.run(Unknown Source)
	at com.sun.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:93)
	at com.sun.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:51)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "JavaFX Application Thread" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:57)
	at java.nio.ByteBuffer.allocate(ByteBuffer.java:335)
	at com.sun.javafx.iio.png.PNGImageLoader2.load(PNGImageLoader2.java:652)
	at com.sun.javafx.iio.ImageStorage.loadAll(ImageStorage.java:364)
	at com.sun.javafx.iio.ImageStorage.loadAll(ImageStorage.java:274)
	at com.sun.javafx.webkit.prism.WCImageDecoderImpl.loadFrames(WCImageDecoderImpl.java:173)
	at com.sun.javafx.webkit.prism.WCImageDecoderImpl.loadFrames(WCImageDecoderImpl.java:186)
	at com.sun.javafx.webkit.prism.WCImageDecoderImpl.addImageData(WCImageDecoderImpl.java:109)
	at com.sun.webkit.network.URLLoader.twkDidFinishLoading(Native Method)
	at com.sun.webkit.network.URLLoader.notifyDidFinishLoading(URLLoader.java:838)
	at com.sun.webkit.network.URLLoader.lambda$didFinishLoading$96(URLLoader.java:829)
	at com.sun.webkit.network.URLLoader$$Lambda$157/718162111.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$null$174(PlatformImpl.java:295)
	at com.sun.javafx.application.PlatformImpl$$Lambda$52/1933809392.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$175(PlatformImpl.java:294)
	at com.sun.javafx.application.PlatformImpl$$Lambda$51/315822528.run(Unknown Source)
	at com.sun.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:93)
	at com.sun.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:51)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "JavaFX Application Thread" java.lang.OutOfMemoryError: GC overhead limit exceeded
```

My Configuration on maven for memory 

```
 <configuration>
...
            <argLine>-Xms512m -Xmx512m</argLine>
...
</configuration>
```

**Comment by hollingsworthd** [comment]
Unfortunately this is a JVM bug. They've had reports of this for several years now. Expecting a fix in Java 9. I added the -Djbd.quickrender=true to work around it (which is the default). Did you set it to false? If you need all the images rendered, then maybe try driver.reset(..) after driver.get(..) which is approximately equivalent to close a browser window and opening a new one. Let me know how it goes.

**Comment by cyildirim** [comment]
I did set ```-Djbd.quickrender``` false before and i switch to true it. It solved. Thank you so much.
