### ISSUE TITLE
Unexpected error when loading content with POST method

### ISSUE THREAD

**Issue by vrosu** [MachinePublishers/jBrowserDriver#31]
I have an heavy HTML5 page which generates 87 requests, a variety of GET and POST.
The page uses jquery a lot.

Except 3 POST request, all requests complete OK.

Those 3 POST requests have the following headers when executed from Firefox:

Host: localhost:8443
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Referer: https://localhost:8443/edited
Cookie: JSESSIONID=someID
Connection: keep-alive
Content-Length: 0

The error which is thrown up by JBrowserDriver is the following:

Feb 02, 2016 5:43:10 PM com.sun.webkit.network.URLLoader doRun
WARNING: Unexpected error
java.io.IOException: null: https://localhost:8443/edited/GetEffectiveTokens
	at com.machinepublishers.jbrowserdriver.StreamConnection.exec(StreamConnection.java:498)
	at com.machinepublishers.jbrowserdriver.StreamConnection.getResponseCode(StreamConnection.java:606)
	at com.sun.webkit.network.URLLoader.receiveResponse(Unknown Source)
	at com.sun.webkit.network.URLLoader.doRun(Unknown Source)
	at com.sun.webkit.network.URLLoader.lambda$run$91(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.webkit.network.URLLoader.run(Unknown Source)[2016-02-02T17:43:10+0200] 
	at com.sun.webkit.network.NetworkContext.fwkLoad(Unknown Source)
	at com.sun.webkit.network.URLLoader.twkDidFinishLoading(Native Method)
	at com.sun.webkit.network.URLLoader.notifyDidFinishLoading(Unknown Source)
	at com.sun.webkit.network.URLLoader.lambda$didFinishLoading$96(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(Unknown Source)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.http.client.ClientProtocolException
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at com.machinepublishers.jbrowserdriver.StreamConnection.exec(StreamConnection.java:488)
	... 17 more
Caused by: org.apache.http.ProtocolException: Content-Length header already present
	at org.apache.http.protocol.RequestContent.process(RequestContent.java:96)
	at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:132)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:182)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	... 19 more

The parameters of the VM are:
-Djbd.ports=11000-11007
-Djbd.browsergui=true
-Djbd.maxrouteconnections=800
-Djbd.quickrender=false
-Djbd.traceconsole=true
-Djbd.blockads=false

The certificate I use has SAN extension with localhost and 127.0.0.1 inside and is imported in cacerts.
I used also jbd.pemfile with compatible or anything with no change.

Any idea how I could troubleshoot this better?

**Comment by vrosu** [comment]
It seems all those 3 POST methods have 0 content length, and all those who execute successfully have a content-length more than 0.
Also of some interest might be the line from the error message:
Caused by: org.apache.http.ProtocolException: Content-Length header already present

**Comment by hollingsworthd** [comment]
That's helpful. Thanks, I'll try to fix it.

**Comment by hollingsworthd** [comment]
I think this is fixed recently by work done for #29. Can you try version 0.8.4 and confirm? Thanks.

**Comment by vrosu** [comment]
Hi,

I cleaned the project after I imported the 0.8.4 jars, but the error didn't change at all. Same as in my initial description.

**Comment by hollingsworthd** [comment]
I added a logging option -Djbd.wireconsole=true which will log the full requests to std out. Also might have fixed this in the just released version 0.8.5 (only available via Maven Central... will take a few minutes for their repo to sync up).

If this doesn't fix the issue, can you help provide a test case so I can reproduce this locally? If that's not possible, please copy/paste the full logging output including wire logging.

**Comment by hollingsworthd** [comment]
Edit: I mean v0.8.6

**Comment by vrosu** [comment]
Issue solved in 0.8.6! (didn't try 0.8.5)
Many thanks!
