### ISSUE TITLE
Selenium 3 and JBrowser

### ISSUE THREAD

**Issue by dramer** [MachinePublishers/jBrowserDriver#326]
<dependency>
			<groupId>com.machinepublishers</groupId>
			<artifactId>jbrowserdriver</artifactId>
			<version>0.17.11</version>
		</dependency>

<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>3.11.0</version>
		</dependency>

calling:

driver = new JBrowserDriver(Settings.builder().ssl("compatible").build());

Exception:

[2018-06-10T23:33:39.706] java.lang.NoClassDefFoundError: org/apache/http/cookie/CommonCookieAttributeHandler
[2018-06-10T23:33:39.707] 	at com.machinepublishers.jbrowserdriver.CookieStore.<clinit>(CookieStore.java:42)
[2018-06-10T23:33:39.707] 	at com.machinepublishers.jbrowserdriver.JBrowserDriverServer.main(JBrowserDriverServer.java:80)
[2018-06-10T23:33:39.707] Caused by: java.lang.ClassNotFoundException: org.apache.http.cookie.CommonCookieAttributeHandler
[2018-06-10T23:33:39.707] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[2018-06-10T23:33:39.707] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[2018-06-10T23:33:39.708] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
[2018-06-10T23:33:39.709] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[2018-06-10T23:33:39.709] 	... 2 more
[2018-06-10T23:33:40.407] java.lang.NoClassDefFoundError: org/apache/http/cookie/CommonCookieAttributeHandler
[2018-06-10T23:33:40.407] 	at com.machinepublishers.jbrowserdriver.CookieStore.<clinit>(CookieStore.java:42)
[2018-06-10T23:33:40.408] 	at com.machinepublishers.jbrowserdriver.JBrowserDriverServer.main(JBrowserDriverServer.java:80)
[2018-06-10T23:33:40.408] Caused by: java.lang.ClassNotFoundException: org.apache.http.cookie.CommonCookieAttributeHandler
[2018-06-10T23:33:40.408] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[2018-06-10T23:33:40.408] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[2018-06-10T23:33:40.408] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
[2018-06-10T23:33:40.408] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[2018-06-10T23:33:40.408] 	... 2 more
Exception in thread "main" org.openqa.selenium.WebDriverException: Could not launch browser.
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'XPO-77WHP72', ip: '192.168.56.1', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_91'
Driver info: driver.version: JBrowserDriver
	at com.machinepublishers.jbrowserdriver.Util.handleException(Util.java:139)
	at com.machinepublishers.jbrowserdriver.JBrowserDriver.<init>(JBrowserDriver.java:338)
	at bichromate.core.sTestWebDriverFactory.ceateJBrowserDriver(sTestWebDriverFactory.java:767)
	at bichromate.core.sTestWebDriverFactory.createBrowserWebDriver(sTestWebDriverFactory.java:1266)
	at bichromate.core.sTestWebDriverFactory.selfTestWindows(sTestWebDriverFactory.java:2021)
	at bichromate.core.sTestWebDriverFactory.selfTest(sTestWebDriverFactory.java:2076)
	at bichromate.core.sTestWebDriverFactory$Test.main(sTestWebDriverFactory.java:2111)
Caused by: java.lang.IllegalStateException: Could not launch browser.
	... 6 more

Thank you for the support?

**Comment by hollingsworthd** [comment]
Version 3 should be supported now and we're actually onto 4.0 alpha.
