### ISSUE TITLE
Error on <init> : Could not find or load main class com.machinepublishers.jbrowserdriver.JBrowserDriverServer

### ISSUE THREAD

**Issue by valer-roman** [MachinePublishers/jBrowserDriver#338]
Hi

  I am trying to create an instance of JBrowserDriver and got into this error:

> [2018-11-05T18:13:34.265] Error: Could not find or load main class com.machinepublishers.jbrowserdriver.JBrowserDriverServer
[2018-11-05T18:13:38.206] Error: Could not find or load main class com.machinepublishers.jbrowserdriver.JBrowserDriverServer
Exception in thread "main" org.openqa.selenium.WebDriverException: Could not launch browser.
Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:25:02.294Z'
System info: host: 'valer-dell', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-38-generic', java.version: '1.8.0_181'
Driver info: driver.version: JBrowserDriver
	at com.machinepublishers.jbrowserdriver.Util.handleException(Util.java:139)
	at com.machinepublishers.jbrowserdriver.JBrowserDriver.<init>(JBrowserDriver.java:344)

  I am using ubuntu Xenial , openjdk 1.8 with JavaFX and jbrowserdriver 1.0.0

Thanks for any help

**Comment by JeffBolle** [comment]
I was also seeing this, though the 1.0.1 release mitigated it on my linux development machine.  However, in our deployed environment, I'm still getting an exception that the browser couldn't be launched:
`at com.machinepublishers.jbrowserdriver.Util.handleException(Util.java:136)
        at com.machinepublishers.jbrowserdriver.JBrowserDriver.<init>(JBrowserDriver.java:340)
`
Ubuntu 16.04, latest oracle java 8:
`java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
`
Are there any recommended troubleshooting steps?

**Comment by liushan150** [comment]
what is jbrowser-uberjar.jar?

**Comment by liushan150** [comment]
> I was also seeing this, though the 1.0.1 release mitigated it on my linux development machine. However, in our deployed environment, I'm still getting an exception that the browser couldn't be launched:
> `at com.machinepublishers.jbrowserdriver.Util.handleException(Util.java:136) at com.machinepublishers.jbrowserdriver.JBrowserDriver.<init>(JBrowserDriver.java:340) `
> Ubuntu 16.04, latest oracle java 8:
> `java version "1.8.0_191" Java(TM) SE Runtime Environment (build 1.8.0_191-b12) Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode) `
> **EDIT**
> In case anyone else stumbles across this thread. My solution was adding the below in the Settings
> `.javaOptions("-classpath", "./path/to/jbrowser-uberjar.jar`
> and then making sure that the user that was running the application owned that uberjar.

what is jbrowser-uberjar.jar?
