### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Ityan** [MachinePublishers/jBrowserDriver#357]
OS info:

> NAME="Amazon Linux"
> VERSION="2"
> ID="amzn"
> ID_LIKE="centos rhel fedora"
> VERSION_ID="2"
> PRETTY_NAME="Amazon Linux 2"

```
Exception in thread "Thread-181" java.lang.NullPointerException
        at java.util.ArrayList.addAll(ArrayList.java:581)
        at com.machinepublishers.jbrowserdriver.JBrowserDriver.lambda$launchProcess$2(JBrowserDriver.java:403)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by hollingsworthd** [comment]
Thanks for reporting this. Looks like a thread safety issue. I am preparing some revisions that might fix this.
