### ISSUE TITLE
Linux Could not launch browser

### ISSUE THREAD

**Issue by 2507483326** [MachinePublishers/jBrowserDriver#370]
[2020-09-11T02:08:40.825] java.lang.NoClassDefFoundError: com/sun/webkit/network/CookieManager
[2020-09-11T02:08:40.826] 	at com.machinepublishers.jbrowserdriver.JBrowserDriverServer.main(JBrowserDriverServer.java:74)
[2020-09-11T02:08:40.826] Caused by: java.lang.ClassNotFoundException: com.sun.webkit.network.CookieManager
[2020-09-11T02:08:40.826] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[2020-09-11T02:08:40.827] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[2020-09-11T02:08:40.827] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
[2020-09-11T02:08:40.827] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[2020-09-11T02:08:40.827] 	... 1 more
Exception in thread "main" org.openqa.selenium.WebDriverException: Could not launch browser.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: '192-168-110-134', ip: '192.168.110.134', os.name: 'Linux', os.arch: 'aarch64', os.version: '4.18.0-193.1.2.el7.aarch64', java.version: '1.8.0_262'
Driver info: driver.version: JBrowserDriver
	at com.machinepublishers.jbrowserdriver.Util.handleException(Util.java:140)
	at com.machinepublishers.jbrowserdriver.JBrowserDriver.<init>(JBrowserDriver.java:282)
	at test.WebFirst.main(WebFirst.java:10)
Caused by: java.lang.IllegalStateException: Could not launch browser.
	... 2 more

**Comment by kNoAPP** [comment]
Hello, I am also having this same issue:
`SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" org.openqa.selenium.WebDriverException: Could not launch browser.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'vps3', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-117-generic', java.version: '1.8.0_265'
Driver info: driver.version: JBrowserDriver
        at com.machinepublishers.jbrowserdriver.Util.handleException(Util.java:136)
        at com.machinepublishers.jbrowserdriver.JBrowserDriver.<init>(JBrowserDriver.java:340)
        at com.knoban.rtx.Main.main(Main.java:38)
Caused by: java.lang.IllegalStateException: Could not launch browser.
        ... 2 more`

**Comment by leemgk** [comment]
com.sun.webkit.network.CookieManager is a class in javaFX

**Comment by Werior** [comment]
Hello, I am also having this same issue,how to solve it,you know?

**Comment by Werior** [comment]
org.openqa.selenium.WebDriverException: Could not launch browser.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'er-receipt-delivery-center-base-7d4c56db69-dpxjg', ip: '192.168.128.149', os.name: 'Linux', os.arch: 'amd64', os.version: '4.19.91-24.1.al7.x86_64', java.version: '1.8.0_352'
Driver info: driver.version: JBrowserDriver
how to fix it?
