### ISSUE TITLE
 use by.xpath , error 

### ISSUE THREAD

**Issue by coyun** [MachinePublishers/jBrowserDriver#4]
java  code ---------------------------------------------------------------

WebElement link  = driver.findElement(By.xpath("//a[contains(@href,'43590350906')]"));

error    --------------------------------------------------------------------

Exception in thread "main" com.machinepublishers.browser.Browser$Retry: java.lang.NullPointerException
	at com.machinepublishers.jbrowserdriver.Element.<init>(Element.java:79)
	at com.machinepublishers.jbrowserdriver.Element$14.perform(Element.java:332)
	at com.machinepublishers.jbrowserdriver.Element$14.perform(Element.java:1)
	at com.machinepublishers.jbrowserdriver.Util$Runner.run(Util.java:104)
	at com.sun.javafx.application.PlatformImpl.lambda$null$170(Unknown Source)
	at com.sun.javafx.application.PlatformImpl$$Lambda$47/18938442.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$171(Unknown Source)
	at com.sun.javafx.application.PlatformImpl$$Lambda$46/12275192.run(Unknown Source)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$145(Unknown Source)
	at com.sun.glass.ui.win.WinApplication$$Lambda$36/3406560.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.machinepublishers.jbrowserdriver.Element.<init>(Element.java:74)
	... 13 more

**Comment by hollingsworthd** [comment]
Thank you for the stack trace and example. I'll take a look at this.
