### ISSUE TITLE
Exception on most basic spock test from Groovy

### ISSUE THREAD

**Issue by jerrywiltse** [MachinePublishers/jBrowserDriver#45]
This simple groovy script works as expected, but when the same exact code is put into a spock test, it causes the exception shown below. It also causes the unit test to run until manually stopped. 

//working script
```
import com.machinepublishers.jbrowserdriver.JBrowserDriver
println 'start'
def driver = new JBrowserDriver()
driver.quit();
println 'finish'
```

//failing spock spec
```
import com.machinepublishers.jbrowserdriver.JBrowserDriver
import spock.lang.Specification

class SandboxSpec extends Specification {

    def "Can we create an instance?"() {
        when:
        println 'start'
        def driver = new JBrowserDriver();
        driver.quit();
        println 'finish'

        then:
        true

    }
}
```

//Output from spock spec
```
[Port 10000] Exception in thread "main" java.lang.ExceptionInInitializerError
[Port 10000] 	at com.machinepublishers.jbrowserdriver.JBrowserDriverServer.main(JBrowserDriverServer.java:70)
[Port 10000] Caused by: java.lang.ArrayStoreException: org.apache.http.impl.cookie.RFC2965VersionAttributeHandler
[Port 10000] 	at org.apache.http.impl.cookie.LaxCookieSpecProvider.create(LaxCookieSpecProvider.java:74)
[Port 10000] 	at com.machinepublishers.jbrowserdriver.CookieStore.<clinit>(CookieStore.java:44)
[Port 10000] 	... 1 more
```

**Comment by hollingsworthd** [comment]
Groovy is not supported. I'm available for consulting if that's a priority for you. Also I'm happy to accept pull requests.
