### ISSUE TITLE
Connect to stream

### ISSUE THREAD

**Issue by dbertels** [MachinePublishers/jBrowserDriver#68]
Sorry, I'm new to this library (and Selenium). I previously worked with HtmlUnit and JSoup and managed to connect to a stream in a loop, using something like
```
   webClient = new WebClient(BrowserVersion.INTERNET_EXPLORER);
   webClient.setAjaxController(new NicelyResynchronizingAjaxController());
   HtmlPage authorisedPage = webClient.getPage(url_st);
   ...
   // 'authorisedPage' updates its DOM values regularly ...
   Document jPage;
   while (is_busy) {
      jPage = Jsoup.parse(authorisedPage.asXml()); 
      if (jPage != null) {
         .. //do my stuff here
      } 
	  ...
	  synchronized (authorisedPage) {
	  try {
	     authorisedPage.wait(2000);
	  }
   }
```
I've been trying to apply this logic to the jBrowserDriver but didn't get anywhere. Looks like it needs a different approach here. Can you please put me on the right track?

**Comment by hollingsworthd** [comment]
Hi, it will work differently in this project than with other Selenium web driver, as we have built-in handling of ajax. If you want to wait 2 seconds for requests to be idle before you consider a page load to be complete, then use `new JBrowserDriver(Settings.builder().ajaxWait(2000).build())` ... however I might be missing something... do you have an example page you could point me to?

**Comment by hollingsworthd** [comment]
... and then the code would look more like:

```java
  JBrowserDriver driver = new JBrowserDriver(Settings.builder().ajaxWait(2000).build());
  driver.get(url_st);
  //do stuff here
  Document jPage = Jsoup.parse(driver.getPageSource());
  driver.quit();
```

**Comment by dbertels** [comment]
Hi, thanks for your prompt response. 

When connecting to a page such as http://sports.williamhill.com/bet/en-gb/betlive/all , you get a page with continuously updating values (using Ajax). 
I want to stay connected to this page in order to keep receiving these updated values. I then use a loop to capture these updated values at regular intervals. If I do a `driver.getPageSource()` once, will this driver stay connected to the stream? I've tried the following 
```
driver = new JBrowserDriver(Settings.builder()
   .timezone(Timezone.EUROPE_LONDON)
   .userAgent(UserAgent.CHROME)
   .ajaxWait(10000)
   .build());
driver.get(url_st);
String page;
while (is_busy) {
   page = driver.getPageSource();
   if (page != null && !page.isEmpty()) {
      List<WebElement> we = driver.findElementsByClassName("a.Score");
      // read the values
   }
   synchronized (page) {
      try {
         page.wait(Utilities.calculateInterval());
      }
      catch (InterruptedException e) {
         log.log(Level.SEVERE, "Process interrupted", e);
      }
   }
}	  
```
This was resulting in a serious crash before. But now I get serious warnings even WITHOUT going into the while loop:
```
[Port 19963] Mar 18, 2016 10:25:39 AM com.sun.webkit.network.URLLoader doRun
[Port 19963] WARNING: Unexpected error
[Port 19963] java.io.IOException: The target server failed to respond: http://whdn.williamhill.com/core/ob/static/cust/images/en/topx_tooltip_top.png?ver=e5ea03cc06bb4a6139e6b50cc3a6493f
[Port 19963] 	at com.machinepublishers.jbrowserdriver.StreamConnection.exec(StreamConnection.java:320)
[Port 19963] 	at com.machinepublishers.jbrowserdriver.StreamConnection.getResponseCode(StreamConnection.java:427)
[Port 19963] 	at com.sun.webkit.network.URLLoader.receiveResponse(Unknown Source)
[Port 19963] 	at com.sun.webkit.network.URLLoader.doRun(Unknown Source)
[Port 19963] 	at com.sun.webkit.network.URLLoader.lambda$run$87(Unknown Source)
[Port 19963] 	at com.sun.webkit.network.URLLoader$$Lambda$136/2112696159.run(Unknown Source)
[Port 19963] 	at java.security.AccessController.doPrivileged(Native Method)
[Port 19963] 	at com.sun.webkit.network.URLLoader.run(Unknown Source)
[Port 19963] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[Port 19963] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[Port 19963] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[Port 19963] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[Port 19963] 	at java.lang.Thread.run(Unknown Source)
[Port 19963] Caused by: org.apache.http.NoHttpResponseException: The target server failed to respond
[Port 19963] 	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
[Port 19963] 	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
[Port 19963] 	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
[Port 19963] 	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
[Port 19963] 	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
[Port 19963] 	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
[Port 19963] 	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
[Port 19963] 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
[Port 19963] 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
[Port 19963] 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
[Port 19963] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
[Port 19963] 	at com.machinepublishers.jbrowserdriver.StreamConnectionClient.execute(StreamConnectionClient.java:151)
[Port 19963] 	at com.machinepublishers.jbrowserdriver.StreamConnection.exec(StreamConnection.java:312)
[Port 19963] 	... 12 more
[Port 19963] 
```

**Comment by dbertels** [comment]
This last error happens when allocating the driver. I should really have written a separate post for this. For now, I'm mainly interested in the initial question.

**Comment by hollingsworthd** [comment]
Oh I understand better what you want. I would write the code like this... no need to adjust the ajax wait I think and to wait, just call Thread.sleep. The page will remain loaded and running in the browser. I'd recommend you turn on trace logging to see exactly what's going on (there's also wire logging which has more detail). Not sure of any way to detect whether the page is busy/idle, so maybe look to see merely if the DOM changed.

On the exception you received, it may just be a legitimate error, that the server didn't respond. If you think it's more than that, please open an issue.

````java
driver = new JBrowserDriver(Settings.builder()
   .timezone(Timezone.EUROPE_LONDON)
   .userAgent(UserAgent.CHROME)
   .traceConsole(true)
   .build());
driver.get(url_st);
String page = null;
String prevPage = null;
while(true){
   page = driver.getPageSource();
   if (page != null && !page.isEmpty()) {
      if(page.equals(prevPage)){
        break;
      }
      prevPage = page;
      List<WebElement> we = driver.findElementsByClassName("a.Score");
      // read the values
   }
   synchronized (page) {
      try {
         Thread.sleep(Utilities.calculateInterval());
      }
      catch (InterruptedException e) {
         log.log(Level.SEVERE, "Process interrupted", e);
      }
   }
} 
````

**Comment by dbertels** [comment]
Thanks again.
 
Looks like I only need to call driver.getPageSource() once before starting the loop. I also don't seem to need the second page at the moment since I'm operating on the driver directly. The following simplified code seems to work
``` 
String page = null;
boolean is_busy = true;
page = driver.getPageSource();
while (true) {
   synchronized (page) {
      try {
	      log.log(Level.INFO, "waiting ...");
          page.wait(5000);
      }catch (InterruptedException e) {
		  log.log(Level.SEVERE, "Process interrupted", e);
      }
   }
   if (page != null && !page.isEmpty()) {
      List<WebElement> we_lt = driver.findElementsByClassName("Score");
      if(we_lt != null && we_lt.size()>0){
         StringBuilder sb = new StringBuilder();
         for (WebElement el : we_lt) {
            sb.append(el.getText() + " | ");
         }
         log.log(Level.INFO, sb.toString());
      }
      else{
         log.log(Level.INFO, "No Score elements found");
      }
   }
 } // end for loop
```			
But I do get a lot of warnings between each run of the loop:
```
...
| Thread 16 | waiting ...
 | Thread 16 | loop: 5
 | Thread 16 | 72:38 | 3-0 | 1st | 0-0 | 
               Live | 0-0 | 1st | 0-0 | 1st | 0-0 | 2nd | 1-0 | 2nd | 0-1 | 				
			   Live | 0-1 | 2nd | 0-1 | 2nd Half | 53-43 | 
			   Live | 8-3 | 3rd Pd | 1-1 | 3rd Pd | 2-1 | 
 | Thread 16 | waiting ...
[Port 10000] Mar 18, 2016 3:32:59 PM com.sun.webkit.network.URLLoader doRun
[Port 10000] WARNING: Unexpected error
[Port 10000] java.io.IOException: The target server failed to respond: http://pushsc1.williamhill.com/push
[Port 10000] 	at com.machinepublishers.jbrowserdriver.StreamConnection.exec(StreamConnection.java:320)
[Port 10000] 	at com.machinepublishers.jbrowserdriver.StreamConnection.getResponseCode(StreamConnection.java:427)
[Port 10000] 	at com.sun.webkit.network.URLLoader.receiveResponse(Unknown Source)
[Port 10000] 	at com.sun.webkit.network.URLLoader.doRun(Unknown Source)
[Port 10000] 	at com.sun.webkit.network.URLLoader.lambda$run$87(Unknown Source)
[Port 10000] 	at com.sun.webkit.network.URLLoader$$Lambda$136/1557464011.run(Unknown Source)
[Port 10000] 	at java.security.AccessController.doPrivileged(Native Method)
[Port 10000] 	at com.sun.webkit.network.URLLoader.run(Unknown Source)
[Port 10000] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[Port 10000] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[Port 10000] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[Port 10000] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[Port 10000] 	at java.lang.Thread.run(Unknown Source)
[Port 10000] Caused by: org.apache.http.NoHttpResponseException: The target server failed to respond
[Port 10000] 	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
[Port 10000] 	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
[Port 10000] 	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
[Port 10000] 	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
[Port 10000] 	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
[Port 10000] 	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
[Port 10000] 	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
[Port 10000] 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
[Port 10000] 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
[Port 10000] 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
[Port 10000] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
[Port 10000] 	at com.machinepublishers.jbrowserdriver.StreamConnectionClient.execute(StreamConnectionClient.java:151)
[Port 10000] 	at com.machinepublishers.jbrowserdriver.StreamConnection.exec(StreamConnection.java:312)
[Port 10000] 	... 12 more
[Port 10000] 
 | Thread 16 | loop: 6
 | Thread 16 | 72:43 | 3-0 | 1st | 0-0 | 
               Live | 0-0 | 1st | 0-0 | 1st | 0-0 | 2nd | 1-0 | 2nd | 0-1 | 				
			   Live	| 0-1 | 2nd | 0-1 | 2nd Half | 53-43 | 
			   Live | 8-3 | 3rd Pd | 1-1 | 3rd Pd | 2-1 | 
 | Thread 16 | waiting ...
```
