### ISSUE TITLE
Selenium Grid

### ISSUE THREAD

**Issue by 0x4321** [MachinePublishers/jBrowserDriver#69]
Is it possible to use jBrowserDriver together with Selenium grid to distribute headless selenium tests to registered nodes?
In the documentation I didn't find anything obvious to provide a url/ip to tell where the Grid server is running. It works just fine with Firefox or Chrome using this code:

```
DesiredCapabilities capability = DesiredCapabilities.firefox(); 
capability.setBrowserName("firefox"); 
capability.setPlatform(Platform.LINUX); 
Url = "http://127.0.0.1:4444/wd/hub"; 
driver = new RemoteWebDriver(new URL(Url), capability);
```

However, I didn't see any way to do something similar with jBrowserDriver.

**Comment by hollingsworthd** [comment]
I know it will work with Selenium Server. I haven't tried it like this, but can you modify the code to be:

  DesiredCapabilities capability = new DesiredCapabilities("jbrowserdriver", "", Platform.ANY); 
  Url = "http://127.0.0.1:4444/wd/hub"; 
  driver = new RemoteWebDriver(new URL(Url), capability);

And then when you start Selenium Grid, you'll need the jBrowserDriver JAR and dependencies on your classpath.

**Comment by 0x4321** [comment]
Ok, I'll play around with that tomorrow.
But I forgot about something:
When you're registering nodes to the grid you have to specify the driver for the different browsers you want to use. Firefox works out of the box, but if you want to execute test let's say with chrome you need to specify the [chromedriver](https://sites.google.com/a/chromium.org/chromedriver/getting-started) when starting the node, like this:

`java -jar selenium-server-standalone-2.52.0.jar -role node -hub http://localhost/grid/register -Dwebdriver.chrome.driver=./path-to-chromedriver`

**Comment by hollingsworthd** [comment]
You won't need to add any option like that. Just make sure the classpath includes all (17?) jars.

**Comment by 0x4321** [comment]
I'm not sure if I did everything correctly, but I haven't got it working.

I changed the code in my test case to 
```java
DesiredCapabilities capability = new DesiredCapabilities("jbrowserdriver", "", Platform.LINUX); 
  Url = "http://127.0.0.1:4444/wd/hub"; 
  driver = new RemoteWebDriver(new URL(Url), capability);
```
and then started the grid server and node with these commands
`java -cp "." -jar selenium-server-standalone-2.53.0.jar -role hub`
`java -cp "." -jar selenium-server-standalone-2.53.0.jar -role node -hub https://localhost:4444/grid/register`
(I have all the jars in the same folder.)

When I tried to run my test case from eclipse I got these errors:
```
org.openqa.selenium.WebDriverException: Error forwarding the new session cannot find : Capabilities [{browserName=jbrowserdriver, version=, platform=LINUX}]
Command duration or timeout: 289 milliseconds
Build info: version: '2.52.0', revision: '4c2593cfc3689a7fcd7be52549167e5ccc93ad28', time: '2016-02-11 11:22:43'
System info: host: 'ubuntu', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.2.0-34-generic', java.version: '1.8.0_66-internal'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:158)
	at testcases.TestCase.setUp(TestCase.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:178)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: org.openqa.grid.common.exception.GridException: Error forwarding the new session cannot find : Capabilities [{browserName=jbrowserdriver, version=, platform=LINUX}]
	at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:115)
	at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:83)
	at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:67)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:499)
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:310)
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.seleniumhq.jetty9.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)

FAILED CONFIGURATION: @AfterClass tearDown
java.lang.NullPointerException
	at testcases.TestCase.tearDown(TestCase.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:232)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:115)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
```

When I tried starting the node with this command:
`java -cp "." -jar selenium-server-standalone-2.53.0.jar -role node -hub https://localhost:4444/grid/register -browser "browserName=jbrowserdriver,maxInstances=3,platform=LINUX"
`

the errors changed to:
```
org.openqa.selenium.WebDriverException: The best matching driver provider org.openqa.selenium.chrome.ChromeDriver can't create a new driver instance for Capabilities [{browserName=jbrowserdriver, version=, platform=LINUX}]
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'ubuntu', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.2.0-34-generic', java.version: '1.8.0_66-internal'
Driver info: driver.version: unknown
Command duration or timeout: 456 milliseconds
Build info: version: '2.52.0', revision: '4c2593cfc3689a7fcd7be52549167e5ccc93ad28', time: '2016-02-11 11:22:43'
System info: host: 'ubuntu', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.2.0-34-generic', java.version: '1.8.0_66-internal'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:158)
	at testcases.TestCase.setUp(TestCase.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:178)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: org.openqa.selenium.WebDriverException: The best matching driver provider org.openqa.selenium.chrome.ChromeDriver can't create a new driver instance for Capabilities [{browserName=jbrowserdriver, version=, platform=LINUX}]
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'ubuntu', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.2.0-34-generic', java.version: '1.8.0_66-internal'
Driver info: driver.version: unknown
Build info: version: '2.52.0', revision: '4c2593cfc3689a7fcd7be52549167e5ccc93ad28', time: '2016-02-11 11:22:43'
System info: host: 'ubuntu', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.2.0-34-generic', java.version: '1.8.0_66-internal'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:62)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:222)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

FAILED CONFIGURATION: @AfterClass tearDown
java.lang.NullPointerException
	at testcases.TestCase.tearDown(TestCase.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:232)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:115)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
```

**Comment by hollingsworthd** [comment]
Can you try Platform.ANY?

**Comment by hollingsworthd** [comment]
Also for the classpath, you'd need to use `./*` I think.

**Comment by 0x4321** [comment]
Ok, I changed it to `Platform.ANY` in my test case and started the grid server and node with the corrected commands:
```
java -cp "./*" -jar selenium-server-standalone-2.53.0.jar -role node -hub https://localhost:4444/grid/register
```
```
java -cp "./*" -jar selenium-server-standalone-2.53.0.jar -role hub
```
I got the same error. (Copied them to pastebin in case I missed something: http://pastebin.com/8uV0eH7P)

Then I tried to start the node with
```
java -cp "./*" -jar selenium-server-standalone-2.53.0.jar -role node -hub https://localhost:4444/grid/register -browser "browserName=jbrowserdriver,maxInstances=3,platform=ANY"
```
and again the same error as in my previous post. (http://pastebin.com/tWNJ1RTa)

**Comment by rezrov** [comment]
Just wanted to chime in and mention I'm trying to do the same thing @0x4321 is and seeing the exact same error. I've got a selenium grid configured, with the node running like this:
```
java -cp "./jBrowserDriver/dist/*" -Djava.net.preferIPv4Stack=true -jar selenium-server-standalone.jar -Dwebdriver.chrome.driver=chromedriver -role node -nodeConfig node.json
```
node.json contains the following:
```javascript
{
    "capabilities":[
        {
            "browserName": "firefox",
            "acceptSslCerts": true,
            "javascriptEnabled": true,
            "takesScreenshot": true,
            "maxInstances": 5,
            "platform": "LINUX",
            "seleniumProtocol": "WebDriver"
        },
        {
            "browserName": "jbrowserdriver",
            "acceptSslCerts": true,
            "javascriptEnabled": true,
            "takesScreenshot": true,
            "maxInstances": 5,
            "platform": "LINUX",
            "seleniumProtocol": "WebDriver"
        }

    ],
    "configuration":{
        "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
        "maxSession": 5,
        "host": localhost,
        "port": 5555,
        "register": true,
        "registerCycle": 5000,
        "hubPort": 4444,
        "hubHost": localhost
    }
}
```
Requesting a session with the browser set to "firefox" works as expected. Requesting a session with the browser set to "jbrowserdriver" produces the following error:
```
11:25:15.323 WARN - Exception: The best matching driver provider org.openqa.selenium.chrome.ChromeDriver can't create a new driver instance for Capabilities [{count=1, browserName=jbrowserdriver, maxInstances=1, shardTestFiles=false}]
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'localhost', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.0.9-gentoo', java.version: '1.8.0_72'
Driver info: driver.version: unknown
```

**Comment by hollingsworthd** [comment]
Thanks for all the info. I'll install Grid and take a look. Previously I only tested Selenium Server.

**Comment by hollingsworthd** [comment]
This has been supported but to get it to work the command to launch the Node needs to be like this:

`java -classpath "selenium-server-standalone-2.53.0.jar:jBrowserDriver-v0.13.0/dist/*" org.openqa.grid.selenium.GridLauncher -role node http://localhost:4444/grid/register -browser browserName=jbrowserdriver,version=1,platform=ANY

The hub is started as normal.

Note on Linux/Mac classpath elements are separated with colons and on Windows with semi-colons.

Then in the Java code use something like this:

```java
DesiredCapabilities capabilities = new DesiredCapabilities("jbrowserdriver", "1", Platform.ANY);
capabilities.merge(Settings.builder().cache(true).buildCapabilities()); //this is optional
WebDriver driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), capabilities);
```

**Comment by j-manu** [comment]
This doesn't work when I'm using selenium from ruby. I'm getting this error

```
[remote server] org.openqa.grid.web.servlet.handler.RequestHandler(RequestHandler.java):115:in `process': Error forwarding the new session cannot find : Capabilities [{rotatable=false, nativeEvents=false, browserName=jbrowserdriver, takesScreenshot=false, javascriptEnabled=false, version=1, platform=ANY, cssSelectorsEnabled=false}] (org.openqa.grid.common.exception.GridException) (Selenium::WebDriver::Error::UnknownError)
```

Full backtrace, code to reproduce, hub & node logs are here - https://gist.github.com/anonymous/92fb2830040e0f03fa6f7d0fe4fbe9f1

**Comment by hollingsworthd** [comment]
@j-manu is it possible the command to launch it is wrong? I forgot to update the instructions with the latest release to update the name of the dist dir... should be 

`java -classpath "selenium-server-standalone-2.53.0.jar:jBrowserDriver-v0.14.0/dist/*" org.openqa.grid.selenium.GridLauncher -role node http://localhost:4444/grid/register -browser browserName=jbrowserdriver,version=1,platform=ANY`

**Comment by j-manu** [comment]
No. I was actually launching it from inside the dist directory with the selenium-server-standalone-2.53.0.jar placed inside it. Just to be sure I also tried it using the code above. It launches correctly just like before but unable to use it

**Comment by hollingsworthd** [comment]
@j-manu ok, then the command would be `java -classpath "./*" org.openqa.grid.selenium.GridLauncher -role node http://localhost:4444/grid/register -browser browserName=jbrowserdriver,version=1,platform=ANY`

**Comment by j-manu** [comment]
No change. If it was a classpath issue I would expect the node to not start at all. But the node starts, registers with the hub. I can even see it in the hub console but unable to use it.
![screen shot 2016-06-06 at 7 03 17 pm](https://cloud.githubusercontent.com/assets/72501/15823695/7582f558-2c19-11e6-985d-6e515b47583b.png)
![screen shot 2016-06-06 at 7 03 36 pm](https://cloud.githubusercontent.com/assets/72501/15823696/75892144-2c19-11e6-88b3-ba28a460a43c.png)

**Comment by hollingsworthd** [comment]
@j-manu Thanks very much for the detailed info. I'll try it out.

**Comment by j-manu** [comment]
Do you need any help with reproducing this?

**Comment by 0x4321** [comment]
I'm available again. So if you need help testing some things let me know.

**Comment by hollingsworthd** [comment]
@j-manu @0x4321 I haven't tried this yet. My thinking is that there's something about the Ruby binding which breaks things. When I tried this originally I only used the Java binding. If you want, it might be useful to try the ruby and the Java binding and see if they're different.

**Comment by j-manu** [comment]
Do you have a self contained java project that I can download and test? I'm not experienced in Java, so don't know how to set it up and test it.

**Comment by hollingsworthd** [comment]
@j-manu within the `dist` directory of the (this release)[https://github.com/MachinePublishers/jBrowserDriver/releases/download/v0.14.0/jBrowserDriver-v0.14.0.zip] create a file named Example.java with this content:

````java
import java.net.MalformedURLException;
import java.net.URL;
import org.openqa.selenium.Platform;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import com.machinepublishers.jbrowserdriver.Settings;
import com.machinepublishers.jbrowserdriver.Timezone;

public class Example {
  public static void main(String[] args) throws MalformedURLException {

    DesiredCapabilities capabilities = 
        new DesiredCapabilities("jbrowserdriver", "1", Platform.ANY);

    // Optionally customize the settings
    capabilities.merge(
        Settings.builder().
        timezone(Timezone.AMERICA_NEWYORK).
        buildCapabilities());

    RemoteWebDriver driver = new RemoteWebDriver(
        new URL("http://localhost:4444/wd/hub"), capabilities);

    driver.get("http://example.com");

    System.out.println(driver.getPageSource());

    driver.quit();
  }
}
````

Also download [selenium standalone 2.53.0](http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.0.jar) and place it in the `dist` directory.

Then in a command prompt at the `dist` directory, run `javac -classpath "./*" Example.java`

Then in 3 separate command prompts at the `dist` directory run the following in order, one command per command prompt:

`java -jar selenium-server-standalone-2.53.0.jar -role hub`

`java -classpath "./*" org.openqa.grid.selenium.GridLauncher -role node http://localhost:4444/grid/register -browser browserName=jbrowserdriver,version=1,platform=ANY`

`java -classpath "./:./*" Example`

The last command should print out the source HTML of http://example.com

**Comment by hollingsworthd** [comment]
The above assumes Mac or Linux. On Windows, you need to use semicolons (not colons) in the classpath, `java -classpath "./;./*" Example` ... I think forward slashes still work but you may need backslashes.

**Comment by abdavid** [comment]
@hollingsworthd I have tested the solution you provided and I can like the others in the thread successfully make the selenium node register itself to the hub, but when I try to send commands through the RemoteWebDriver i would still get the WebDriverException.

```bash
org.openqa.selenium.WebDriverException: The best matching driver provider org.openqa.selenium.phantomjs.PhantomJSDriver can't create a new driver instance for Capabilities [{browserName=jbrowserdriver, version=, platform=ANY}]
```

Command for starting the node and register with the hub. 
_(mind you that I am symlinking the selenium jar into the jbrowser/dist catalogue)._


```bash
java -classpath "/opt/jbrowser/dist/*" org.openqa.grid.selenium.GridLauncher -role node \ 
     -hub http://$HUB_PORT_4444_TCP_ADDR:$HUB_PORT_4444_TCP_PORT/grid/register \
     -nodeConfig /opt/selenium/config.json
```

And my config.json for nodeConfig:

```json
{
  "capabilities": [
    {
      "browserName": "jbrowserdriver",
      "maxInstances": 10,
      "seleniumProtocol": "WebDriver"
    }
  ],
  "configuration": {
    "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
    "maxSession": 5,
    "port": 5555,
    "register": true,
    "registerCycle": 5000,
    "hubPort": 4444
  }
}
```

- Ubuntu 16.04
- jBrowserDriver-v0.14.12
- Selenium standalone 2.53.0
- openjdk version "1.8.0_03-Ubuntu"
- OpenJDK Runtime Environment (build 1.8.0_03-Ubuntu-8u77-b03-3ubuntu3-b03)
- OpenJDK 64-Bit Server VM (build 25.03-b03, mixed mode)

The above stack is dockerized. 


What I havent tested is this bit of merging DesiredCapabilities, and this should be optional yes?

```java
 // Optionally customize the settings
    capabilities.merge(
        Settings.builder().
        timezone(Timezone.AMERICA_NEWYORK).
        buildCapabilities());
```

**Comment by hollingsworthd** [comment]
Hi, the merging is optional. Does it work when you use `-browser browserName=jbrowserdriver,version=1,platform=ANY` instead of `-nodeConfig...`

**Comment by abdavid** [comment]
I have tried that aswell with no luck.

**Comment by abdavid** [comment]
@hollingsworthd I got it working now. 

First issue was that I was using another base image for my Dockerfile, which in turn did alittle more than I wanted it to do, so my start command for the node had executed, but the wrong one. **ps aux** gave that away. 

The second issue was that the org.openqa.grid.selenium.GridLauncher class did not recognise cli arguments over multiple lines. Had to enable JVM debugging to catch that one. 

Testing your implementation now 👍

**Comment by hollingsworthd** [comment]
Thanks. I think this bug can be closed. Future enhancements should probably make this all more user friendly to run.

**Comment by j-manu** [comment]
Confirmed that it is working now with the steps outlined in https://github.com/MachinePublishers/jBrowserDriver/issues/69#issuecomment-230856582 with both Java and Ruby. Thanks!
