### ISSUE TITLE
Behaviour when missing Content-Type header

### ISSUE THREAD

**Issue by shaneargo** [MachinePublishers/jBrowserDriver#88]
When the server doesn't define a Content-Type header in the response, jBrowserDriver fails to render the page (not exactly unexpected) but doesn't throw any exceptions or anything.

It's not exactly a show stopping bug, but it does mean that it behaves slightly differently to other Selenium  drivers. Actual browsers handle not having a Content-Type by assuming it's "text/html". We were using htmlUnit before switching to jBrowserDriver and it also assumed "text/html". So when we switched driver, some of our tests broke. (No Content-Type was being sent because the page was a page served by a Java HttpServer for testing purposes - I've added one now and it's fixed our tests.)

Here is some code to reproduce the issue:
```Java
import com.machinepublishers.jbrowserdriver.JBrowserDriver;
import com.machinepublishers.jbrowserdriver.Settings;
import com.sun.net.httpserver.HttpContext;
import com.sun.net.httpserver.HttpServer;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.OutputStream;
import java.io.UnsupportedEncodingException;
import java.net.InetSocketAddress;

public class ContentTypeTest {

    private static Logger logger = LoggerFactory.getLogger(ContentTypeTest.class);
    private static final byte[] CONTENT;

    static {
        try {
            CONTENT = "<html><body><div id='content'></div></body></html>".getBytes("UTF-8");
        } catch (UnsupportedEncodingException e) {
            throw new RuntimeException(e);
        }
    }

    private static int port;
    private static HttpServer httpServer;

    public static void main(String[] args) throws Exception {

        port = (int) (Math.random() * 40000 + 10000);
        httpServer = HttpServer.create(new InetSocketAddress(port), 0);

        HttpContext with = httpServer.createContext("/with-content-type");
        with.setHandler((he) -> {
            he.getResponseHeaders().add("Content-Type", "text/html");
            he.sendResponseHeaders(200, CONTENT.length);
            final OutputStream body = he.getResponseBody();
            body.write(CONTENT);
            body.flush();
            he.close();
        });

        HttpContext without = httpServer.createContext("/without-content-type");
        without.setHandler((he) -> {
            he.sendResponseHeaders(200, CONTENT.length);
            final OutputStream body = he.getResponseBody();
            body.write(CONTENT);
            body.flush();
            he.close();
        });

        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            httpServer.stop(0);
        }));

        httpServer.start();

        testCase("with-content-type");
        testCase("without-content-type");

        httpServer.stop(0);

    }

    private static void testCase(String useCase) {
        final JBrowserDriver jBrowserDriver = new JBrowserDriver(Settings.builder().build());
        jBrowserDriver.get(String.format("http://localhost:%s/%s", port, useCase));

        final WebElement element = jBrowserDriver.findElement(By.id("content"));

        if(element == null) {
            logger.info("{} IS null", useCase);
        } else {
            logger.info("{} IS NOT null", useCase);
        }

        jBrowserDriver.quit();
    }

}
```

The result of which is:
```
[main] INFO ContentTypeTest - with-content-type IS NOT null
[Port 56336; Process 1] [2016-04-12T14:58:55+1000] [WARNING] java.lang.NullPointerException
[Port 56336; Process 1] 	at com.machinepublishers.jbrowserdriver.ElementServer$1.perform(ElementServer.java:136)
[Port 56336; Process 1] 	at com.machinepublishers.jbrowserdriver.AppThread$Runner.run(AppThread.java:91)
[Port 56336; Process 1] 	at com.sun.javafx.application.PlatformImpl.lambda$null$170(PlatformImpl.java:295)
[Port 56336; Process 1] 	at com.sun.javafx.application.PlatformImpl$$Lambda$51/2057811603.run(Unknown Source)
[Port 56336; Process 1] 	at java.security.AccessController.doPrivileged(Native Method)
[Port 56336; Process 1] 	at com.sun.javafx.application.PlatformImpl.lambda$runLater$171(PlatformImpl.java:294)
[Port 56336; Process 1] 	at com.sun.javafx.application.PlatformImpl$$Lambda$50/452864399.run(Unknown Source)
[Port 56336; Process 1] 	at com.machinepublishers.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:94)
[Port 56336; Process 1] 	at com.machinepublishers.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:53)
[Port 56336; Process 1] 	at java.lang.Thread.run(Thread.java:745)
[Port 56336; Process 1] 
[Port 56336; Process 1] Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
[main] INFO ContentTypeTest - without-content-type IS null
[Port 56336; Process 1] 	at com.machinepublishers.jbrowserdriver.ElementServer$18.perform(ElementServer.java:707)
[Port 56336; Process 1] 	at com.machinepublishers.jbrowserdriver.ElementServer$18.perform(ElementServer.java:704)
[Port 56336; Process 1] 	at com.machinepublishers.jbrowserdriver.AppThread$Runner.run(AppThread.java:91)
[Port 56336; Process 1] 	at com.sun.javafx.application.PlatformImpl.lambda$null$170(PlatformImpl.java:295)
[Port 56336; Process 1] 	at com.sun.javafx.application.PlatformImpl$$Lambda$51/2057811603.run(Unknown Source)
[Port 56336; Process 1] 	at java.security.AccessController.doPrivileged(Native Method)
[Port 56336; Process 1] 	at com.sun.javafx.application.PlatformImpl.lambda$runLater$171(PlatformImpl.java:294)
[Port 56336; Process 1] 	at com.sun.javafx.application.PlatformImpl$$Lambda$50/452864399.run(Unknown Source)
[Port 56336; Process 1] 	at com.machinepublishers.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:94)
[Port 56336; Process 1] 	at com.machinepublishers.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:53)
[Port 56336; Process 1] 	at java.lang.Thread.run(Thread.java:745)
```

Obviously, my log messages are mixing with jBrowserDriver's because of the separate threads, but it still demonstrates the issue.

I don't know how you'd like to handle this. It's not a big deal, because we should've been sending a Content-Type, but it is also kind of strange that the behaviour is that elements cannot be located.

Please let me know if there is any other information I can provide.

**Comment by hollingsworthd** [comment]
Thanks for the detailed report! Yes, I think it should default to text/html. Generally I'll always support behaving like real browsers or other drivers. I'll add this.
