### ISSUE TITLE
Problems in some https sites

### ISSUE THREAD

**Issue by javitorres** [MachinePublishers/jBrowserDriver#96]
Hi, I can't access some sites with HTTPS protocol (example: https://web.wechat.com/).

I've tried with JVM parameters and setting system property jsse.enableSNIExtension (Java 8):

System.setProperty("jsse.enableSNIExtension", "false");
JBrowserDriver driver = new JBrowserDriver(Settings.builder()
    			.timezone(Timezone.EUROPE_MADRID)
    			.userAgent(UserAgent.CHROME)
    			.ssl("https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt")
    			.build());

driver.get("https://web.wechat.com/");

The error I get:

[2016-04-29T19:37:34.161][Instance 1][Port 50653] [2016-04-29T19:37:34.160]Connecting socket to web.wechat.com/203.205.151.162:443 with timeout 0
[2016-04-29T19:37:34.711][Instance 1][Port 50653] [2016-04-29T19:37:34.711]Enabled protocols: [TLSv1, TLSv1.1, TLSv1.2]
[2016-04-29T19:37:34.711][Instance 1][Port 50653] [2016-04-29T19:37:34.711]Enabled cipher suites:[TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA256, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_DSS_WITH_AES_128_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_DSS_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA, SSL_RSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA, TLS_ECDHE_ECDSA_WITH_RC4_128_SHA, TLS_ECDHE_RSA_WITH_RC4_128_SHA, SSL_RSA_WITH_RC4_128_SHA, TLS_ECDH_ECDSA_WITH_RC4_128_SHA, TLS_ECDH_RSA_WITH_RC4_128_SHA, SSL_RSA_WITH_RC4_128_MD5, TLS_EMPTY_RENEGOTIATION_INFO_SCSV]
[2016-04-29T19:37:34.711][Instance 1][Port 50653] [2016-04-29T19:37:34.711]Starting handshake
[2016-04-29T19:37:35.088][Instance 1][Port 50653] abr 29, 2016 9:37:35 PM com.sun.webkit.network.URLLoader doRun
[2016-04-29T19:37:35.088][Instance 1][Port 50653] ADVERTENCIA: Unexpected error
[2016-04-29T19:37:35.088][Instance 1][Port 50653] java.io.IOException: handshake alert:  unrecognized_name: https://web.wechat.com/
[2016-04-29T19:37:35.089][Instance 1][Port 50653] 	at com.machinepublishers.jbrowserdriver.StreamConnection.exec(StreamConnection.java:343)
[2016-04-29T19:37:35.089][Instance 1][Port 50653] 	at com.machinepublishers.jbrowserdriver.StreamConnection.getResponseCode(StreamConnection.java:441)
[2016-04-29T19:37:35.089][Instance 1][Port 50653] 	at com.sun.webkit.network.URLLoader.receiveResponse(URLLoader.java:406)
[2016-04-29T19:37:35.089][Instance 1][Port 50653] 	at com.sun.webkit.network.URLLoader.doRun(URLLoader.java:162)
[2016-04-29T19:37:35.089][Instance 1][Port 50653] 	at com.sun.webkit.network.URLLoader.lambda$run$90(URLLoader.java:127)
[2016-04-29T19:37:35.090][Instance 1][Port 50653] 	at com.sun.webkit.network.URLLoader$$Lambda$151/1369914768.run(Unknown Source)
[2016-04-29T19:37:35.090][Instance 1][Port 50653] 	at java.security.AccessController.doPrivileged(Native Method)
[2016-04-29T19:37:35.090][Instance 1][Port 50653] 	at com.sun.webkit.network.URLLoader.run(URLLoader.java:126)
[2016-04-29T19:37:35.090][Instance 1][Port 50653] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[2016-04-29T19:37:35.090][Instance 1][Port 50653] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[2016-04-29T19:37:35.090][Instance 1][Port 50653] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[2016-04-29T19:37:35.091][Instance 1][Port 50653] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[2016-04-29T19:37:35.091][Instance 1][Port 50653] 	at java.lang.Thread.run(Thread.java:745)
[2016-04-29T19:37:35.091][Instance 1][Port 50653] Caused by: javax.net.ssl.SSLProtocolException: handshake alert:  unrecognized_name
[2016-04-29T19:37:35.091][Instance 1][Port 50653] 	at sun.security.ssl.ClientHandshaker.handshakeAlert(ClientHandshaker.java:1410)
[2016-04-29T19:37:35.091][Instance 1][Port 50653] 	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2004)
[2016-04-29T19:37:35.091][Instance 1][Port 50653] 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1113)
[2016-04-29T19:37:35.091][Instance 1][Port 50653] 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1363)
[2016-04-29T19:37:35.091][Instance 1][Port 50653] 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1391)
[2016-04-29T19:37:35.091][Instance 1][Port 50653] 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1375)
[2016-04-29T19:37:35.091][Instance 1][Port 50653] 	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394)
[2016-04-29T19:37:35.091][Instance 1][Port 50653] 	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353)
[2016-04-29T19:37:35.092][Instance 1][Port 50653] 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
[2016-04-29T19:37:35.092][Instance 1][Port 50653] 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
[2016-04-29T19:37:35.092][Instance 1][Port 50653] 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
[2016-04-29T19:37:35.092][Instance 1][Port 50653] 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
[2016-04-29T19:37:35.092][Instance 1][Port 50653] 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
[2016-04-29T19:37:35.092][Instance 1][Port 50653] 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
[2016-04-29T19:37:35.092][Instance 1][Port 50653] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
[2016-04-29T19:37:35.092][Instance 1][Port 50653] 	at com.machinepublishers.jbrowserdriver.StreamConnectionClient.execute(StreamConnectionClient.java:162)
[2016-04-29T19:37:35.092][Instance 1][Port 50653] 	at com.machinepublishers.jbrowserdriver.StreamConnection.exec(StreamConnection.java:335)
[2016-04-29T19:37:35.092][Instance 1][Port 50653] 	... 12 more

**Comment by hollingsworthd** [comment]
Java system properties aren't passed to the forked JRE process where the http request is actually made. Prepend the property with "jbd.rmi." to have it passed to the child process. `System.setProperty("jbd.rmi.jsse.enableSNIExtension", "false");` ... this is an unpublished feature and may change in the future, but I'll probably keep things backwards compatible.

Also turn hostname verification off, `Settings.builder().hostnameVerification(false)` (this doesn't address the error in question, but another one after the initial request works).

**Comment by javitorres** [comment]
Yes! Now it works! Thank you for your INSTANT answer. Regards

**Comment by igor-rubis** [comment]
Hello. I'm new to your tool.
I'm getting the same error despite I set things you suggested:
> def driver = new JBrowserDriver(Settings.builder()
>                 .hostnameVerification(false)
>                 .userAgent(UserAgent.CHROME)
>                 .build())
> System.setProperty("jbd.rmi.jsse.enableSNIExtension", "false")
> driver.get('https://www.some_url.com')

Seems like the error occurs when the page tries to load js script from other location.
The error is:
> [2016-10-22T10:55:20.154][Instance 1][Port 4485] ��� 22, 2016 1:55:20 PM com.sun.webkit.network.URLLoader doRun
> [2016-10-22T10:55:20.155][Instance 1][Port 4485] WARNING: Unexpected error
> [2016-10-22T10:55:20.156][Instance 1][Port 4485] java.io.IOException: handshake alert:  unrecognized_name: https://static.ads-twitter.com/uwt.js
> [2016-10-22T10:55:20.156][Instance 1][Port 4485] 	at com.machinepublishers.jbrowserdriver.StreamConnection.exec(StreamConnection.java:361)
> [2016-10-22T10:55:20.156][Instance 1][Port 4485] 	at com.machinepublishers.jbrowserdriver.StreamConnection.getResponseCode(StreamConnection.java:441)
> [2016-10-22T10:55:20.156][Instance 1][Port 4485] 	at com.sun.webkit.network.URLLoader.receiveResponse(URLLoader.java:406)
> [2016-10-22T10:55:20.156][Instance 1][Port 4485] 	at com.sun.webkit.network.URLLoader.doRun(URLLoader.java:162)
> [2016-10-22T10:55:20.156][Instance 1][Port 4485] 	at com.sun.webkit.network.URLLoader.lambda$run$90(URLLoader.java:127)
> [2016-10-22T10:55:20.156][Instance 1][Port 4485] 	at com.sun.webkit.network.URLLoader$$Lambda$149/377016614.run(Unknown Source)
> [2016-10-22T10:55:20.157][Instance 1][Port 4485] 	at java.security.AccessController.doPrivileged(Native Method)
> [2016-10-22T10:55:20.157][Instance 1][Port 4485] 	at com.sun.webkit.network.URLLoader.run(URLLoader.java:126)
> [2016-10-22T10:55:20.157][Instance 1][Port 4485] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [2016-10-22T10:55:20.157][Instance 1][Port 4485] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [2016-10-22T10:55:20.157][Instance 1][Port 4485] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> [2016-10-22T10:55:20.157][Instance 1][Port 4485] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> [2016-10-22T10:55:20.157][Instance 1][Port 4485] 	at java.lang.Thread.run(Thread.java:745)
> [2016-10-22T10:55:20.158][Instance 1][Port 4485] Caused by: javax.net.ssl.SSLProtocolException: handshake alert:  unrecognized_name
> [2016-10-22T10:55:20.158][Instance 1][Port 4485] 	at sun.security.ssl.ClientHandshaker.handshakeAlert(ClientHandshaker.java:1410)
> [2016-10-22T10:55:20.158][Instance 1][Port 4485] 	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2004)
> [2016-10-22T10:55:20.158][Instance 1][Port 4485] 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1113)
> [2016-10-22T10:55:20.158][Instance 1][Port 4485] 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1363)
> [2016-10-22T10:55:20.158][Instance 1][Port 4485] 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1391)
> [2016-10-22T10:55:20.159][Instance 1][Port 4485] 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1375)
> [2016-10-22T10:55:20.159][Instance 1][Port 4485] 	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394)
> [2016-10-22T10:55:20.159][Instance 1][Port 4485] 	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353)
> [2016-10-22T10:55:20.159][Instance 1][Port 4485] 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
> [2016-10-22T10:55:20.159][Instance 1][Port 4485] 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
> [2016-10-22T10:55:20.159][Instance 1][Port 4485] 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
> [2016-10-22T10:55:20.159][Instance 1][Port 4485] 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
> [2016-10-22T10:55:20.160][Instance 1][Port 4485] 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
> [2016-10-22T10:55:20.160][Instance 1][Port 4485] 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
> [2016-10-22T10:55:20.160][Instance 1][Port 4485] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
> [2016-10-22T10:55:20.161][Instance 1][Port 4485] 	at com.machinepublishers.jbrowserdriver.StreamConnectionClient.execute(StreamConnectionClient.java:175)
> [2016-10-22T10:55:20.161][Instance 1][Port 4485] 	at com.machinepublishers.jbrowserdriver.StreamConnection.exec(StreamConnection.java:327)
> [2016-10-22T10:55:20.162][Instance 1][Port 4485] 	... 12 more
> [2016-10-22T10:55:20.162][Instance 1][Port 4485] 

Could you please help with this?

In the page source code the link looks like this:
> <script type="text/javascript" async="" src="//static.ads-twitter.com/uwt.js"></script>
