### ISSUE TITLE
Is JBrowserDriver has Mobile user agent support ?

### ISSUE THREAD

**Issue by karunakaranvrv** [MachinePublishers/jBrowserDriver#97]
@hollingsworthd 
Currently I am running my test on Firefox or Chrome browser with userAgent override.

Is there option available in JBrowserDriver for Mobile User Agent Support ?

If it is available. How to use it ?

**Comment by hollingsworthd** [comment]
Hi, you can pass a [UserAgent](http://machinepublishers.github.io/jBrowserDriver/com/machinepublishers/jbrowserdriver/UserAgent.html) object to the Settings Builder. Probably also pass [Chrome RequestHeaders](http://machinepublishers.github.io/jBrowserDriver/com/machinepublishers/jbrowserdriver/RequestHeaders.html#CHROME) to the Settings Builder. You can also construct a custom RequestHeaders object too.

**Comment by karunakaranvrv** [comment]
I am trying to pass userAgent in browser. I am getting following error.

```
java.lang.NoClassDefFoundError: org/openqa/selenium/remote/internal/CircularOutputStream
	at org.openqa.selenium.firefox.FirefoxBinary.<init>(FirefoxBinary.java:60)
	at org.openqa.selenium.firefox.FirefoxBinary.<init>(FirefoxBinary.java:56)
	at org.openqa.selenium.firefox.FirefoxDriver.getBinary(FirefoxDriver.java:203)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:128)	
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.remote.internal.CircularOutputStream
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 43 more
```

Following is my code:-

		```
UserAgent userAgent = new UserAgent(UserAgent.Family.WEBKIT, "", "Android", "", "5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36", "Mozilla/5.0 (Linux; U; Android 6.0.1; en-gb; SM-N920G Build/MMB29K) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1");
		JBrowserDriver driver = new JBrowserDriver(Settings.builder().headless(true).userAgent(userAgent).
				timezone(Timezone.AMERICA_NEWYORK).build());
```


How to solve this ?
