### ISSUE TITLE
Screenshots are black when screen dimension are setted 

### ISSUE THREAD

**Issue by FeanDoe** [MachinePublishers/jBrowserDriver#98]
When I set the screen dimension on the driver settings 
```
Dimension screendim = new Dimension(1366,768);
JBrowserDriver driver = new JBrowserDriver(Settings.builder().  timezone(Timezone.AMERICA_NEWYORK).screen(screendim).requestHeaders(RequestHeaders.CHROME).quickRender(false).cache(true).cacheDir(theDir).saveMedia(true).userAgent(UserAgent.CHROME).build());
```

And then take an screenshot
```
 File screen = ((TakesScreenshot)driver).getScreenshotAs(OutputType.FILE);
```
The file is a black image, but if I don't set the screen dimension the image is saved correctly.
Is a bug or am I doing something wrong?

**Comment by hollingsworthd** [comment]
It's probably that the page doesn't totally finish rendering/painting before it attempts to screenshot it. The screen dimensions can affect this timing indirectly. Best solution is probably to set Settings.builder().ajaxWait(int) to something higher than 150 ms (which is the default).

**Comment by BlueIce** [comment]
I have a similar/the same issue. For bigger screen dimensions i get the following stacktrace in the `Robot#screenshot` method:

```java
java.lang.IllegalArgumentException: Unrecognized image loader: null
 at javafx.scene.image.WritableImage.loadTkImage(WritableImage.java:240)
 at javafx.scene.image.WritableImage.access$000(WritableImage.java:46)
 at javafx.scene.image.WritableImage$1.loadTkImage(WritableImage.java:51)
 at javafx.scene.Scene.doSnapshot(Scene.java:1236)
 at javafx.scene.Node.doSnapshot(Node.java:1862)
 at javafx.scene.Node.snapshot(Node.java:1940)
 at com.machinepublishers.jbrowserdriver.Robot$12.perform(Robot.java:593)
 at com.machinepublishers.jbrowserdriver.Robot$12.perform(Robot.java:1)
 at com.machinepublishers.jbrowserdriver.AppThread$Runner.run(AppThread.java:98)
 at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
 at java.security.AccessController.doPrivileged(Native Method)
 at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
 at com.machinepublishers.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:94)
 at com.machinepublishers.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:53)
 at java.lang.Thread.run(Thread.java:745)
```

I found out that increasing the property `prism.maxvram` in the `SettingsManager` allowed me to take non-back screenshots with bigger screen dimensions.

**Comment by hollingsworthd** [comment]
Thanks @BlueIce !

I increased it to 16 MB and made a snapshot release to Maven. @FeanDoe try version 0.12.1-SNAPSHOT

**Comment by FeanDoe** [comment]
Hi!
How do I set the snapshot release on Maven?
Thanks!

**Comment by hollingsworthd** [comment]
Something like 

````
<dependency>
  <groupId>com.machinepublishers</groupId>
  <artifactId>jbrowserdriver</artifactId>
  <version>0.12.1-SNAPSHOT</version>
</dependency>
````

**Comment by FeanDoe** [comment]
"The POM for com.machinepublishers:jbrowserdriver:jar:0.12.1-SNAPSHOT is missing, no dependency information available"

I can't access to the snapshot release (if there is one) :(

**Comment by hollingsworthd** [comment]
Not sure how exactly why snapshot releases aren't available like others. Anyhow I just made an actual release v0.13.0. I think this is fixed now.

Thanks @FeanDoe for reporting this and @BlueIce pointing me to the fix. I removed the vram setting altogether so it uses the Prism default. Eventually these Prism settings should be configurable by users which I'll address in #83

**Comment by FeanDoe** [comment]
Anyway, with the new release works like a charm!

Thanks! :)
